### ISSUE TITLE
SetParentHandle Win32ExpException

### ISSUE THREAD

**Issue by GebitMattias** [dotnet/winforms#10014]
### .NET version

net 6.0.22

### Did it work in .NET Framework?

Yes

### Issue description

A customer is reporting a fatal Win32Exception when trying to open a window in our application. It only happens when opening certain windows.
Exception:
`Message: Fehler beim Festlegen des übergeordneten Win32-Fensters des Steuerelements`

Stack:
`   at System.Windows.Forms.Control.SetParentHandle(IntPtr value)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at DevExpress.XtraEditors.DForm.WndProc(Message& m)
   at DevExpress.XtraEditors.XtraForm.WndProc(Message& msg)
   at Gebit.Common.Views.UoWViewBase.WndProc(Message& m) in D:\Bamboo\local-working-dir\DDEV-RB36-BUILD\Gebit.Common.Views\BaseUoWViews\UoWViewBase.cs:line 330
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)`

### Steps to reproduce

We cannot reproduce this issue on our side. The customer is using VMWare with VMWare Horizon 8.1.0 clients. Unsure if that will be related

**Comment by JeremyKuhne** [comment]
In .NET Framework it didn't check whether setting the parent was successful.  The behavior was changed to address #2163.

@dreddy-work this was originally done to deal with DPI issues, perhaps you can help @GebitMattias narrow down what might be going on here?

**Comment by dreddy-work** [comment]
@GebitMattias, is it possible to run the same application by targeting .NET 8.0 on those environments to see if it reproduces with latest? Also, is it possible to share the application or simple repro on that environment?

**Comment by GebitMattias** [comment]
We are still trying to find a way to reproduce the issue, but are having no success. The project itself is too big to share.
Not sure if net8 will work for the project, we just upgraded to net6 and unsure how many things will need changing. For a short test, it might be doable. 
We also disable DPI scaling (it is old WinForms app not yet ready for it). Could this cause issues?

**Comment by dreddy-work** [comment]
> We also disable DPI scaling (it is old WinForms app not yet ready for it). Could this cause issues?

How do you disable DPI scaling? One of the reasons why the mention API fails is, if you created two windows in different DPI scaling modes and trying to add the one to the others control collection or explicitly setting as a parent of the other.

**Comment by GebitMattias** [comment]
> How do you disable DPI scaling? One of the reasons why the mention API fails is, if you created two windows in different DPI scaling modes and trying to add the one to the others control collection or explicitly setting as a parent of the other.

By setting `<ApplicationHighDpiMode>DpiUnaware</ApplicationHighDpiMode>` in the entrypoint csproj and calling the `ApplicationConfiguration.Initialize();` in the Main method.
I sent test versions to the client with normal DPI scaling, as well as one version using .NET 7.0. We cannot upgrade to .NET 8.0 easily, as too many libraries are not ready for it. I will report whether this helped.

**Comment by GebitMattias** [comment]
The customer reported that the activating the DPI scaling fixes the issue. We will use this fix for now and the customer will have to live with some Controls potentially scaling wrong.
Thanks for your help!

**Comment by dreddy-work** [comment]
Glad you have a temporary solution for now. In case if you face it again or get a simple repro for us, please reactivate the issue.
