### ISSUE TITLE
RichTextBox Find method throws exception when searching at end of RTF containing a table.

### ISSUE THREAD

**Issue by Rsge** [dotnet/winforms#10322]
### .NET version

.NET 8

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Not in .NET 6 nor 7. Others not tested.

### Issue description

When trying to use the `Find` method with just a `String` argument to find a string near the end of the document of a `RichtTextBox` which's RTF contains a table, an `ArgumentOutOfRangeException` is thrown: `Index and length must refer to a location within the string. (Parameter 'length')`.

If the RTF is only normal text the method works as expected.
If it contains a table, even if it's not the last thing in the RTF, it throws the exception.
If the text doesn't occur in the document at all, nothing happens, as expected.

The last fact leads me to believe the problem lies in the selection of a found string, not in finding its starting index itself

The stack trace:
```
System.Private.CoreLib
   at System.String.ThrowSubstringArgumentOutOfRange(Int32 startIndex, Int32 length)
   at System.String.Substring(Int32 startIndex, Int32 length)
   at System.Windows.Forms.RichTextBox.Find(String str, Int32 start, Int32 end, RichTextBoxFinds options)
   at System.Windows.Forms.RichTextBox.Find(String str)
   at Test.Form1.Button4_Click(Object sender, EventArgs e) in C:\Test\Test\Form1.vb:line 39
```

### Steps to reproduce

* Create a WinForms application using .NET 8.
* Create a form `Form1` with at least a `RichTextBox` (RTB).
* Create a RTF string which contains a table and let the RTB display it.
* Use the `Find` method on the RTB to find a string which lies near the end of the document.
* An exception is thrown.

Example Class:
```vbnet
Public Class Form1
    Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        Dim rtf As String = "{\rtf1\ansi\deff0\trowd
\pard\intbl Test\cell Example\cell Meow\cell Woof\cell \row
}"
        RichTextBox1.Rtf = rtf
    End Sub

    Private Sub Button2_Click(sender As Object, e As EventArgs) Handles Button2.Click
        Dim rtf As String = "{\rtf1\ansi\deff0
\pard Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec maximus nibh est, ut rutrum magna facilisis eget. Sed eget risus a purus sagittis suscipit. Mauris ut risus et ligula mollis pretium. Donec volutpat finibus eleifend. Ut molestie sit amet felis eget sollicitudin. Nunc odio nisl, fermentum at orci eget, tempor gravida ligula. Duis porta faucibus fringilla. Nam ut semper nisl. Example.\par
}"
        RichTextBox1.Rtf = rtf
    End Sub

    Private Sub Button3_Click(sender As Object, e As EventArgs) Handles Button3.Click
        Dim rtf As String = "{\rtf1\ansi\deff0\trowd
\pard\intbl X\cell X\cell X\cell X\cell\row 
\pard\intbl Test\cell Example\cell Meow\cell Woof\cell\row 
\pard Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec maximus nibh est, ut rutrum magna facilisis eget. Sed eget risus a purus sagittis suscipit. Mauris ut risus et ligula mollis pretium. Donec volutpat finibus eleifend. Ut molestie sit amet felis eget sollicitudin. Nunc odio nisl, fermentum at orci eget, tempor gravida ligula. Duis porta faucibus fringilla. Nam ut semper nisl. Test. Example.\par
}"
        RichTextBox1.Rtf = rtf
    End Sub

    Private Sub Button4_Click(sender As Object, e As EventArgs) Handles Button4.Click
        RichTextBox1.Rtf = RichTextBox1.Rtf
        Try
            RichTextBox1.Select()
            RichTextBox1.Find(InputBox(""))
        Catch ex As ArgumentOutOfRangeException
            MsgBox(ex.Message)
        End Try
    End Sub
End Class
```

* When using `Button1` to generate a table in the RTB and trying to find "Woof", the exception is thrown.
* When trying to find "Meow" there, it works as expected, "Meow" is selected.
* When using `Button2` to generate a normal text in the RTB and trying to find "Example.", it also works as expected.
* When using `Button3` to generate a table followed by "normal" text and trying to find "Example.", it throws the exception again.
* When trying to find "Test." there, it again works as expected.
* When using any of the buttons and trying to find something like "xxxxx", nothing happens, as expected, no exception.

**Comment by elachlan** [comment]
@Olina-Zhang can your team please test this?

**Comment by Amy-Li03** [comment]
This issue can repro from .NET 5.0 to 9.0, and it also reproes on .NET framework 4.7 ~ 4.8.1.
![Repro](https://github.com/dotnet/winforms/assets/62929087/c00f6638-3439-4bc2-a2ee-e3e3f7b73ace)

**Comment by elachlan** [comment]
This code is the culprit. The RichText control is returning a TextLength of `217` in my test example. But the string.length is `213`. It looks like the richedit when we call `Find` is returning a `position` with a different internal string length. This results in the substring `ArgumentOutOfRange`.
https://github.com/dotnet/winforms/blob/f6eee834ba66d1940262c1428772d937184c76e6/src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox/RichTextBox.cs#L1893-L1919

https://github.com/dotnet/winforms/blob/f6eee834ba66d1940262c1428772d937184c76e6/src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox/RichTextBox.cs#L1413-L1426

I imagine the fix will be around understanding the internals of the windows richedit control with regards to tables and text length.

**Comment by merriemcgaw** [comment]
Thanks for picking this up @elachlan

**Comment by Rsge** [comment]
If someone finds this via search:

### I've found a workaround until this gets fixed in the next release.

It works with the native `Find` method until it errors and then tries to estimate the error factor and use that to get a position via `IndexOf` and select via, well `Select`.\
It doesn't work perfectly, but pretty well in my testing.

#### VB.NET
```vb.net
Dim query As String = InputBox("")
Dim position As Integer
Dim previousPosition As Integer ' Just as an example, has to have been set beforehand.
RichTextBox1.Select()
Try
    position = RichTextBox1.Find(query, previousPosition, RichTextBoxFinds.None)
Catch ex As ArgumentOutOfRangeException
    Dim bugFactor As Double = RichTextBox1.TextLength / RichTextBox1.Text.Length
    position = CInt(RichTextBox1.Text.IndexOf(query, CInt(previousPosition / bugFactor) + 1) * bugFactor)
    RichTextBox1.Select(position, query.Length)
End Try
```

#### C#
```csharp
string query = Interaction.InputBox("");
int position;
int previousPosition; // Just as an example, has to have been set beforehand.
this.RichTextBox1.Select();
try
{
    position = this.RichTextBox1.Find(query, previousPosition, RichTextBoxFinds.None);
}
catch (ArgumentOutOfRangeException ex)
{
    double bugFactor = (double)this.RichTextBox1.TextLength / (double)this.RichTextBox1.Text.Length;
    position = (int)Math.Round((double)this.RichTextBox1.Text.IndexOf(query, (int)Math.Round(previousPosition / bugFactor) + 1) * bugFactor);
    this.RichTextBox1.Select(position, query.Length);
}
```

**Comment by Eudora-Li01** [comment]
Verified this on .NET 9.0.100-1.23606.3 + latest dll files. Find method can be find text correctly without expection thrown in RichTextBox.

https://github.com/dotnet/winforms/assets/130345015/8fd84096-15ae-4dbd-8fcf-027a5e5f5ea1
