### ISSUE TITLE
Images added as a resource inaccessible from controls

### ISSUE THREAD

**Issue by jwilo** [dotnet/winforms#10412]
### Environment

Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.8.0

### .NET version

8.0.0

### Did this work in a previous version of Visual Studio and/or previous .NET release?

Unknown

### Issue description

Attempting to add an image to a project from the Resources.resx designer, does not allow those images to be used by controls (such as a pictureBox), even though they are 'addable' from such controls, and even preview correctly.

Issue is seen with a .NET 8, WinForms C# project.

### Steps to reproduce

1. In solution explorer, right click on Properties > Resources.resx > Open
2. Change Icons dropdown to Images
3. Add Resource > Add Existing file
4. Navigate to where the image is and select the image
5. In the newly added images Properties, leave Persistence as 'Linked at compile time'
6. In the newly added resource Properties (Solution explorer > Project >Resources > new resource), leave these as default (build action: none)
7. Open the designer to a form with a pictureBox
8. In the properties of said pictureBox, go to Image to select a resource. The newly added resource should be visible inside 'Project resource file'
9. Select this resource
10. It should now appear in the designer successfully, great!
11. Build the solution - now it fails. 

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0117	'Resources' does not contain a definition for 'images'

You'll note that the newly added resource's build action has defaulted to 'Content' from 'None'. Try changing this to 'Embedded Resource' instead, the build still fails. Even if changing the Resources persistence to 'Embedded in .resx'.

Alternatively............. one can import the resource from the pictureBox directly, but the result is the same.

One thing, and perhaps the most important to note - is this is a project that was migrated from .NET framework, to .NET using the Visual Studio .NET Upgrade Assistant.

**Comment by jwilo** [comment]
I have also confirmed, if I create an entirely new solution and follow the reproduction steps, the issue is **not** present, leading me further to believe this is an issue with solution migration/upgrade.

**Comment by elachlan** [comment]
It would be good to diff compare the converted vs the new file (with all the resources added back). Also compare the converted vs new project file.

**Comment by merriemcgaw** [comment]
@jwilo which language are you using for this migration. If you can, please provide a sample that demonstrates the before/after of the upgrade.

**Comment by merriemcgaw** [comment]
@jwilo - if you find a repro, please use VS Feedback to send us the feedback and the logs. That's the easiest way to get that kind of information to the team. I'm glad everything is working for you now.

**Comment by jwilo** [comment]
Thanks both, to answer previous question this is a C# app.

I'm swamped at the moment, but as soon as I can I'll run a diff and see if I can reproduce.

**Comment by paul1956** [comment]
@merriemcgaw I just ran into this today on a very old project that was upgraded to latest Preview, everything worked as expected until I added 2 new PNG files as resources. The new resources Me.Resource.Copy and Me.Resource.ExportData could not be found in the code trying to reference them. When I compared the working project and upgraded project, I noticed the Resources.Designer file had not been modified but the files were added to project. When I manually added the lines below (copied from another project) to Resources.Designer file everything worked.
```
        '''<summary>
        ''' Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Copy", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ExportData() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ExportData", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property
```

**Comment by merriemcgaw** [comment]
@KlausLoeffelmann can you take a look?

**Comment by Tanya-Solyanik** [comment]
@Olina-Zhang  - could you please try to reproduce this issue and share the repro project?

**Comment by John-Qiao** [comment]
@Tanya-Solyanik please check my below steps and result:

1. Create a C# or VB .NET WinForms project
2. Add existing image files in **Resources.resx** file
3. Open form designer and add a **PictureBox** control
4. In **Properties** window, select the **Image** property and click **...** to open the **Select Resource** dialog.
5. Observe the items under **Project resource files:** option

https://github.com/dotnet/winforms/assets/45864985/07abebf2-c125-48ac-8f88-25141c07c4d7

**Current Behavior**
There's no images display under **Project resource files:** option.
![Current2](https://github.com/dotnet/winforms/assets/45864985/172974da-6342-4660-986b-71c6c5c59187)

**Expected Behavior**
The images should be displayed under **Project resource files:** option.
![Expected](https://github.com/dotnet/winforms/assets/45864985/8a9a08f0-bdee-46d3-acf0-fb13381ad072)

**More Info**
After step 5, if we build the project, then reopen the **Select Resource** dialog again, the images will display under **Project resource files:** option correctly, but the below error message shows in **Output** window. If we select the image file for **PictureBox** control, it works well, and we can build & run project successfully.

```
[22:59:13.258381] fail: System.InvalidOperationException: Can't resolve types until ITypeIdentityResolutionService has started processing enqueued assemblies.
                           at Microsoft.DotNet.DesignTools.Protocol.Types.AssemblySearchingTypeIdentityResolutionService.TryGetType(TypeIdentity typeIdentity, Boolean ignoreCase, Type& type)
                           at Microsoft.DotNet.DesignTools.Protocol.Types.AssemblySearchingTypeIdentityResolutionService.ResolveNamedType(TypeIdentity typeIdentity, TypeIdentityResolutionOptions options)
                           at Microsoft.DotNet.DesignTools.Protocol.Types.TypeIdentityResolutionService.ResolveType(TypeIdentity typeIdentity, TypeIdentityResolutionOptions options)
                           at Microsoft.DotNet.DesignTools.Client.Types.BaseTypeResolutionService.GetType(String name, Boolean throwOnError, Boolean ignoreCase)

                        For information on how to troubleshoot the designer refer to the guide at https://aka.ms/winforms/designer/troubleshooting.
[22:59:13.267901] fail: System.InvalidOperationException: Can't resolve types until ITypeIdentityResolutionService has started processing enqueued assemblies.
                           at Microsoft.DotNet.DesignTools.Protocol.Types.AssemblySearchingTypeIdentityResolutionService.TryGetType(TypeIdentity typeIdentity, Boolean ignoreCase, Type& type)
                           at Microsoft.DotNet.DesignTools.Protocol.Types.AssemblySearchingTypeIdentityResolutionService.ResolveNamedType(TypeIdentity typeIdentity, TypeIdentityResolutionOptions options)
                           at Microsoft.DotNet.DesignTools.Protocol.Types.TypeIdentityResolutionService.ResolveType(TypeIdentity typeIdentity, TypeIdentityResolutionOptions options)
                           at Microsoft.DotNet.DesignTools.Client.Types.BaseTypeResolutionService.GetType(String name, Boolean throwOnError, Boolean ignoreCase)

                        For information on how to troubleshoot the designer refer to the guide at https://aka.ms/winforms/designer/troubleshooting.
[22:59:13.271895] fail: System.InvalidOperationException: Can't resolve types until ITypeIdentityResolutionService has started processing enqueued assemblies.
                           at Microsoft.DotNet.DesignTools.Protocol.Types.AssemblySearchingTypeIdentityResolutionService.TryGetType(TypeIdentity typeIdentity, Boolean ignoreCase, Type& type)
                           at Microsoft.DotNet.DesignTools.Protocol.Types.AssemblySearchingTypeIdentityResolutionService.ResolveNamedType(TypeIdentity typeIdentity, TypeIdentityResolutionOptions options)
                           at Microsoft.DotNet.DesignTools.Protocol.Types.TypeIdentityResolutionService.ResolveType(TypeIdentity typeIdentity, TypeIdentityResolutionOptions options)
                           at Microsoft.DotNet.DesignTools.Client.Types.BaseTypeResolutionService.GetType(String name, Boolean throwOnError, Boolean ignoreCase)

                        For information on how to troubleshoot the designer refer to the guide at https://aka.ms/winforms/designer/troubleshooting.
```

![OutPut2](https://github.com/dotnet/winforms/assets/45864985/e8123780-90fa-4cec-a6a9-747ff89a8c75)

This issue repros in .NET 6.0/7.0/8.0/9.0 projects, and it still repros in VS 2019 and 2022 products.

**Comment by leivvv** [comment]
You can set the acces to public here:
![devenv_N35sgzXYgh](https://github.com/dotnet/winforms/assets/141370355/6a452ab1-0e11-42b3-857b-234b52d93c0f)

**Comment by merriemcgaw** [comment]
This looks like it's behaving by design as long as you build your project after adding resources and before expecting them to show up in the select resource dialog. Feel free to reopen if I've missed something here.

**Comment by paul1956** [comment]
Why would anyone expect to have to rebuild, this just started happening in recent version of VS. I think it has more to do with the modifier of the image resource not being set correctly, I reported this via feedback with details to repo but unfortunately due to my current location I can’t access the site or GitHub. Sent from my iPhoneI apologize for any typos Siri might have made.(503) 803-6077On Mar 1, 2024, at 1:51 PM, Merrie McGaw ***@***.***> wrote:﻿
This looks like it's behaving by design as long as you build your project after adding resources and before expecting them to show up in the select resource dialog. Feel free to reopen if I've missed something here.
