### ISSUE TITLE
Issue when using Dpi Aware with PermonitorV2.

### ISSUE THREAD

**Issue by Gokul-Subramani** [dotnet/winforms#10711]
### .NET version

.Net Framework 4.7

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

No 

## Issue Scenario ##

We are using DPI Awareness with PerMonitorV2 in the App.config and have added the App.manifest, enabling dpiAware as true. Then, we also added the supportedOS as Windows 10, with the supportedOS Id being 8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a.

I have created a UserControl and added a Panel to it. After setting the panel Location to (x=0, y=0) and the panel Size to (this.width, 0), the panel Location changed to a negative value (x= -536, y=0).

https://github.com/dotnet/winforms/assets/124788061/dab75853-01e3-4563-a0b8-727c2cb4b4da

## Working Scenario ##

However, without DPI Awareness, when I set the panel Location to (x=0, y=0) and the panel Size to (this.width, 0), the panel Location did not change to a negative value and it shows what I have set before (x=0, y=0).

## Sample ##

[WinformsSample.zip](https://github.com/dotnet/winforms/files/14005979/WinformsSample.zip)

### Steps to reproduce

1. Run the sample.
2. Click on the PopUp button.
3. A MessageBox will appear, showing the panel location.
4. Click on the Ok button.
5. The second time, the MessageBox will show that the panel location has been changed to negative (x = -184, y = 0).

**Comment by merriemcgaw** [comment]
@Olina-Zhang can your team validate this and offer any suggestions?

**Comment by Olina-Zhang** [comment]
Hi @Gokul-Subramani I tested your provided sample, and added extra supporting HDPI content with an improvement, it seems your issue resolved. Please add following content in app.config file:
```
<System.Windows.Forms.ApplicationConfigurationSection>
<add key="DpiAwareness" value="PerMonitorV2"/>
<add key="AnchorLayout.EnableHighDpiImprovementsV2" value="true"/>
</System.Windows.Forms.ApplicationConfigurationSection>
```
Testing result with this added content:

https://github.com/dotnet/winforms/assets/26474449/44020af9-91d0-4f92-93c2-3b4a6a9971c9

**Comment by paul1956** [comment]
> Hi @Gokul-Subramani I tested your provided sample, and added extra supporting HDPI content with an improvement in app.config file, it seems your issue resolved. Please add following content in app.config file:
> 
> ```
> <System.Windows.Forms.ApplicationConfigurationSection>
> <add key="DpiAwareness" value="PerMonitorV2"/>
> <add key="AnchorLayout.EnableHighDpiImprovementsV2" value="true"/>
> </System.Windows.Forms.ApplicationConfigurationSection>
> ```
> 
> Testing result with this added content:
> 
>  GHIssue10711_Testing.mp4
@Olina-Zhang 
I tried this on a VB program, there is an app.config under my project. Adding these lines to that file does not work, it faults while trying to parse the file.

Should I add a second app.config file under root or is this solution not compatible with VB?

```
System.Configuration.ConfigurationErrorsException
  HResult=0x80131902
  Message=Configuration system failed to initialize
  Source=System.Configuration.ConfigurationManager
  StackTrace:
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   at System.Configuration.ClientConfigurationSystem.PrepareClientConfigSystem(String sectionName)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.RefreshConfig(String sectionName)
   at System.Configuration.ClientSettingsStore.ReadSettings(String sectionName, Boolean isUserScoped)
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   at System.Configuration.SettingsBase.get_Item(String propertyName)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   at System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   at CareLink.My.MySettings.get_UpgradeRequired() in C:\Users\PaulM\Source\Repos\CareLink\src\CareLink\My Project\Settings.Designer.vb:line 98
   at CareLink.Form1.Form1_Load(Object sender, EventArgs e) in C:\Users\PaulM\Source\Repos\CareLink\src\CareLink\Forms\Form1.vb:line 1019
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean ignoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at CareLink.Form1.WndProc(Message& m) in C:\Users\PaulM\Source\Repos\CareLink\src\CareLink\Forms\Form1.vb:line 114
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)

  This exception was originally thrown at this call stack:
    System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(bool)
    System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(System.Configuration.ConfigurationSchemaErrors)
    System.Configuration.ClientConfigurationSystem.EnsureInit(string)

Inner Exception 1:
ConfigurationErrorsException: Unrecognized configuration section System.Windows.Forms.ApplicationConfigurationSection. (C:\Users\PaulM\Source\Repos\CareLink\src\CareLink\bin\Debug\net8.0-windows10.0.17763.0\CareLink.dll.config line 48)
```

**Comment by Olina-Zhang** [comment]
> Should I add a second app.config file under root or is this solution not compatible with VB?

That HDPI content is for .Net framework, not .Net.

**Comment by Olina-Zhang** [comment]
> Thanks for the work around, but facing another issue the size changes are not reflected properly in panel,

Hi @sethuramkumar That's what Merrie was talking about: Winforms doesn't fully support PerMonitorV2 in the .NET Framework (in fact, we're still working on implementing PerMonitorV2 in .Net). If you can, please use .Net.
