### ISSUE TITLE
VisualStyle unit tests failing locally, passing in CI builds

### ISSUE THREAD

**Issue by AdamYoblick** [dotnet/winforms#1093]
Tried looking into the issue, but it's failing in interop code and I'm not familiar enough with this to debug. Tagging @hughbe since he worked on this last. Hughbe did these work for you when you ran .\build -test locally? (note that these only fail in debug mode, not when specifying -configuration Release)

I'm going to comment out these tests since they are blocking local development and we can revisit later.

Errors are below:
```
System.Windows.Forms.VisualStyles.Tests.VisualStyleInformationTests.VisualStyleInformation_Author_Get_ReturnsExpected
System.InvalidProgramException : Common Language Runtime detected an invalid program.
   at System.Windows.Forms.VisualStyles.VisualStyleInformation.get_ThemeFilename()
   at System.Windows.Forms.VisualStyles.VisualStyleInformation.get_Author() in E:\src\repos\github\winforms\src\System.Windows.Forms\src\System\Windows\Forms\VisualStyles\VisualStyleInformation.cs:line 152
   at System.Windows.Forms.VisualStyles.Tests.VisualStyleInformationTests.VisualStyleInformation_Author_Get_ReturnsExpected() in E:\src\repos\github\winforms\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\VisualStyles\VisualStyleInformationTests.cs:line 15
0.0008417s ✘  System.Windows.Forms.VisualStyles.Tests.VisualStyleInformationTests.VisualStyleInformation_ColorScheme_Get_ReturnsDifferent
System.InvalidProgramException : Common Language Runtime detected an invalid program.
   at System.Windows.Forms.VisualStyles.VisualStyleInformation.get_ColorScheme()
   at System.Windows.Forms.VisualStyles.Tests.VisualStyleInformationTests.VisualStyleInformation_ColorScheme_Get_ReturnsDifferent() in E:\src\repos\github\winforms\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\VisualStyles\VisualStyleInformationTests.cs:line 31
0.000712s ✘  System.Windows.Forms.VisualStyles.Tests.VisualStyleInformationTests.VisualStyleInformation_ColorScheme_Get_ReturnsExpected
System.InvalidProgramException : Common Language Runtime detected an invalid program.
   at System.Windows.Forms.VisualStyles.VisualStyleInformation.get_ColorScheme()
   at System.Windows.Forms.VisualStyles.Tests.VisualStyleInformationTests.VisualStyleInformation_ColorScheme_Get_ReturnsExpected() in E:\src\repos\github\winforms\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\VisualStyles\VisualStyleInformationTests.cs:line 23
0.0008933s ✘  System.Windows.Forms.VisualStyles.Tests.VisualStyleInformationTests.VisualStyleInformation_Company_Get_ReturnsExpected
System.InvalidProgramException : Common Language Runtime detected an invalid program.
   at System.Windows.Forms.VisualStyles.VisualStyleInformation.get_ThemeFilename()
   at System.Windows.Forms.VisualStyles.VisualStyleInformation.get_Company() in E:\src\repos\github\winforms\src\System.Windows.Forms\src\System\Windows\Forms\VisualStyles\VisualStyleInformation.cs:line 136
   at System.Windows.Forms.VisualStyles.Tests.VisualStyleInformationTests.VisualStyleInformation_Company_Get_ReturnsExpected() in E:\src\repos\github\winforms\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\VisualStyles\VisualStyleInformationTests.cs:line 42
0.0023558s ✘  System.Windows.Forms.VisualStyles.Tests.VisualStyleInformationTests.VisualStyleInformation_Copyright_Get_ReturnsExpected
System.InvalidProgramException : Common Language Runtime detected an invalid program.
   at System.Windows.Forms.VisualStyles.VisualStyleInformation.get_ThemeFilename()
   at System.Windows.Forms.VisualStyles.VisualStyleInformation.get_Copyright() in E:\src\repos\github\winforms\src\System.Windows.Forms\src\System\Windows\Forms\VisualStyles\VisualStyleInformation.cs:line 168
   at System.Windows.Forms.VisualStyles.Tests.VisualStyleInformationTests.VisualStyleInformation_Copyright_Get_ReturnsExpected() in E:\src\repos\github\winforms\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\VisualStyles\VisualStyleInformationTests.cs:line 58
0.001642s ✘  System.Windows.Forms.VisualStyles.Tests.VisualStyleInformationTests.VisualStyleInformation_Description_Get_ReturnsExpected
System.InvalidProgramException : Common Language Runtime detected an invalid program.
   at System.Windows.Forms.VisualStyles.VisualStyleInformation.get_ThemeFilename()
   at System.Windows.Forms.VisualStyles.VisualStyleInformation.get_Description() in E:\src\repos\github\winforms\src\System.Windows.Forms\src\System\Windows\Forms\VisualStyles\VisualStyleInformation.cs:line 218
   at System.Windows.Forms.VisualStyles.Tests.VisualStyleInformationTests.VisualStyleInformation_Description_Get_ReturnsExpected() in E:\src\repos\github\winforms\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\VisualStyles\VisualStyleInformationTests.cs:line 66
0.0008617s ✘  System.Windows.Forms.VisualStyles.Tests.VisualStyleInformationTests.VisualStyleInformation_DisplayName_Get_ReturnsExpected
System.InvalidProgramException : Common Language Runtime detected an invalid program.
   at System.Windows.Forms.VisualStyles.VisualStyleInformation.get_ThemeFilename()
   at System.Windows.Forms.VisualStyles.VisualStyleInformation.get_DisplayName() in E:\src\repos\github\winforms\src\System.Windows.Forms\src\System\Windows\Forms\VisualStyles\VisualStyleInformation.cs:line 120
   at System.Windows.Forms.VisualStyles.Tests.VisualStyleInformationTests.VisualStyleInformation_DisplayName_Get_ReturnsExpected() in E:\src\repos\github\winforms\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\VisualStyles\VisualStyleInformationTests.cs:line 74
0.0008564s ✘  System.Windows.Forms.VisualStyles.Tests.VisualStyleInformationTests.VisualStyleInformation_Size_Get_ReturnsDifferent
System.InvalidProgramException : Common Language Runtime detected an invalid program.
   at System.Windows.Forms.VisualStyles.VisualStyleInformation.get_Size()
   at System.Windows.Forms.VisualStyles.Tests.VisualStyleInformationTests.VisualStyleInformation_Size_Get_ReturnsDifferent() in E:\src\repos\github\winforms\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\VisualStyles\VisualStyleInformationTests.cs:line 113
0.0007424s ✘  System.Windows.Forms.VisualStyles.Tests.VisualStyleInformationTests.VisualStyleInformation_Size_Get_ReturnsExpected
System.InvalidProgramException : Common Language Runtime detected an invalid program.
   at System.Windows.Forms.VisualStyles.VisualStyleInformation.get_Size()
   at System.Windows.Forms.VisualStyles.Tests.VisualStyleInformationTests.VisualStyleInformation_Size_Get_ReturnsExpected() in E:\src\repos\github\winforms\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\VisualStyles\VisualStyleInformationTests.cs:line 105
0.0008996s ✘  System.Windows.Forms.VisualStyles.Tests.VisualStyleInformationTests.VisualStyleInformation_Url_Get_ReturnsExpected
System.InvalidProgramException : Common Language Runtime detected an invalid program.
   at System.Windows.Forms.VisualStyles.VisualStyleInformation.get_ThemeFilename()
   at System.Windows.Forms.VisualStyles.VisualStyleInformation.get_Url() in E:\src\repos\github\winforms\src\System.Windows.Forms\src\System\Windows\Forms\VisualStyles\VisualStyleInformation.cs:line 186
   at System.Windows.Forms.VisualStyles.Tests.VisualStyleInformationTests.VisualStyleInformation_Url_Get_ReturnsExpected() in E:\src\repos\github\winforms\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\VisualStyles\VisualStyleInformationTests.cs:line 139
0.0008723s ✘  System.Windows.Forms.VisualStyles.Tests.VisualStyleInformationTests.VisualStyleInformation_Version_Get_ReturnsDifferent
System.InvalidProgramException : Common Language Runtime detected an invalid program.
   at System.Windows.Forms.VisualStyles.VisualStyleInformation.get_ThemeFilename()
   at System.Windows.Forms.VisualStyles.VisualStyleInformation.get_Version() in E:\src\repos\github\winforms\src\System.Windows.Forms\src\System\Windows\Forms\VisualStyles\VisualStyleInformation.cs:line 202
   at System.Windows.Forms.VisualStyles.Tests.VisualStyleInformationTests.VisualStyleInformation_Version_Get_ReturnsDifferent() in E:\src\repos\github\winforms\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\VisualStyles\VisualStyleInformationTests.cs:line 155
0.0009617s ✘  System.Windows.Forms.VisualStyles.Tests.VisualStyleInformationTests.VisualStyleInformation_Version_Get_ReturnsExpected
System.InvalidProgramException : Common Language Runtime detected an invalid program.
   at System.Windows.Forms.VisualStyles.VisualStyleInformation.get_ThemeFilename()
   at System.Windows.Forms.VisualStyles.VisualStyleInformation.get_Version() in E:\src\repos\github\winforms\src\System.Windows.Forms\src\System\Windows\Forms\VisualStyles\VisualStyleInformation.cs:line 202
   at System.Windows.Forms.VisualStyles.Tests.VisualStyleInformationTests.VisualStyleInformation_Version_Get_ReturnsExpected() in E:\src\repos\github\winforms\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\VisualStyles\VisualStyleInformationTests.cs:line 147

```

**Comment by AdamYoblick** [comment]
@hughbe here's some more info from @JeremyKuhne , our interop expert:

Yes, there is a pretty bad bug in the code. When passing a StringBuilder to a P/Invoke the length is set before the first null. Converting a span to a string converts the entire char array. So every string coming back in this change is 512 characters long.

https://github.com/dotnet/winforms/pull/1012/files#diff-1fabe581057676e6f7185f289cd1c751L54

The fix is relatively simple, find the index of the null and slice the span before converting it to a string (be careful of not finding the null, i.e. -1).

Another, more subtle, change is that StringBuilder.Capacity is actually one less than the backing buffer size. There is actually space for a trailing null. I seriously doubt the Windows API will try and put a null past the passed in length, but the docs aren’t very clear on the null terminating behavior. I can’t access the Windows sources at the moment to validate.

There is also a prior bug in this code that we’re not checking the return value for errors. The return value is an HRESULT- you can either compare it against S_OK and throw or let the interop layer do it for you by changing the return type to void and setting `PreserveSig` to false in the [DllImport]. When doing COM interop this is the default behavior, for P/Invokes it is obviously the reverse.

Lastly there is another prior issue in that we don’t handle if the strings are > 512 chars. Presumably the API will truncate, but it isn’t documented. We should at least test with a really small buffer to see what the behavior actually is and at least document what we know and that we’re ok with truncating (if that is in fact the case).

For future reference, all of these API calls that don’t return a length will need to be tweaked if you ever turn on ILLinkClearInitLocals in your repo. CoreFX and CoreCLR has this setting turned on for performance. WinForms uses a lot of APIs that don’t return the length. The usual fix for that is to explicitly set the first char to null.

**Comment by AdamYoblick** [comment]
Tagging @RussKie for visibility :)

**Comment by hughbe** [comment]
Why would this throw `InvalidProgramException`? I'd expect an AV or no crash!

**Comment by dreddy-work** [comment]
@AdamYoblick , can this issue be closed now?

**Comment by AdamYoblick** [comment]
I believe this was just an issue to track the failing unit test. If it’s passing locally now, feel free to close it out :)

________________________________

**Comment by dreddy-work** [comment]
Closing this issue as linked PR was merged and should take care of this. @RussKie , @hughbe as FYI.
