### ISSUE TITLE
Windows.Form on form.Show() with Run Test and Debug Test different behaviour

### ISSUE THREAD

**Issue by pashaalex** [dotnet/winforms#11123]
### .NET version

net8.0-windows

### Did it work in .NET Framework?

No

### Issue description

This test passed with RunTest but failed with DebugTest
```
    [TestClass]
    public class UnitTest1 {
        [TestMethod]
        public void TestMethod1() {
            using(var form = new System.Windows.Forms.Form()) {
                bool formWasPaint = false;
                form.Paint += (s, e) => {
                    formWasPaint = true;
                };
                form.Show();
                Application.DoEvents();
                Assert.IsTrue(formWasPaint);
            }
        }
    }
```
With MSTest 3.0.4

### Steps to reproduce

1. Create new MSTest project
2. Add Windows Forms support (TargetFramework and UseWindowsForms in  csproj file)
3. Add test with source code above
4. Try RunTest and try DebugTest ... you will see different result and you will not see the form DebugTest case

**Comment by merriemcgaw** [comment]
This is fascinating, thanks for bringing it up! If you have a debugger attached, the Windows message loop is different than when you run it without the debugger or it could be something related to the MS Test doing interesting things. Can you try to reproduce this outside of a test project? If you're still having problems, you should look at how we do our tests - that framework doesn't seem to produce this type of error.

**Comment by ricardobossan** [comment]
## To help with the triage:

- [mstest.zip](https://github.com/dotnet/winforms/files/15069314/mstest.zip)

## Call Stack with source paths:

Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.dll!Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestMethodInfo.ExecuteInternal(object[] arguments) Line 253
	at /_/src/Adapter/MSTest.TestAdapter/Execution/TestMethodInfo.cs(253)
Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.dll!Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestMethodInfo.Invoke(object[] arguments) Line 115
	at /_/src/Adapter/MSTest.TestAdapter/Execution/TestMethodInfo.cs(115)
Microsoft.VisualStudio.TestPlatform.TestFramework.dll!Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute.Execute(Microsoft.VisualStudio.TestTools.UnitTesting.ITestMethod testMethod) Line 44
	at /_/src/TestFramework/TestFramework/Attributes/TestMethod/TestMethodAttribute.cs(44)
Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.dll!Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestMethodRunner.ExecuteTest(Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestMethodInfo testMethodInfo) Line 388
	at /_/src/Adapter/MSTest.TestAdapter/Execution/TestMethodRunner.cs(388)
Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.dll!Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestMethodRunner.RunTestMethod() Line 170
	at /_/src/Adapter/MSTest.TestAdapter/Execution/TestMethodRunner.cs(170)
Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.dll!Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestMethodRunner.Execute() Line 106
	at /_/src/Adapter/MSTest.TestAdapter/Execution/TestMethodRunner.cs(106)
Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.dll!Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.UnitTestRunner.RunSingleTest(Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.ObjectModel.TestMethod testMethod, System.Collections.Generic.IDictionary<string, object> testContextProperties) Line 148
	at /_/src/Adapter/MSTest.TestAdapter/Execution/UnitTestRunner.cs(148)
Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.dll!Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestExecutionManager.ExecuteTestsWithTestRunner(System.Collections.Generic.IEnumerable<Microsoft.VisualStudio.TestPlatform.ObjectModel.TestCase> tests, Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.ITestExecutionRecorder testExecutionRecorder, string source, System.Collections.Generic.IDictionary<string, object> sourceLevelParameters, Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.UnitTestRunner testRunner) Line 401
	at /_/src/Adapter/MSTest.TestAdapter/Execution/TestExecutionManager.cs(401)
Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.dll!Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestExecutionManager.ExecuteTestsInSource(System.Collections.Generic.IEnumerable<Microsoft.VisualStudio.TestPlatform.ObjectModel.TestCase> tests, Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IRunContext runContext, Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IFrameworkHandle frameworkHandle, string source, bool isDeploymentDone) Line 353
	at /_/src/Adapter/MSTest.TestAdapter/Execution/TestExecutionManager.cs(353)
Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.dll!Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestExecutionManager.ExecuteTests(System.Collections.Generic.IEnumerable<Microsoft.VisualStudio.TestPlatform.ObjectModel.TestCase> tests, Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IRunContext runContext, Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IFrameworkHandle frameworkHandle, bool isDeploymentDone) Line 148
	at /_/src/Adapter/MSTest.TestAdapter/Execution/TestExecutionManager.cs(148)
Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.dll!Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestExecutionManager.RunTests(System.Collections.Generic.IEnumerable<Microsoft.VisualStudio.TestPlatform.ObjectModel.TestCase> tests, Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IRunContext runContext, Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IFrameworkHandle frameworkHandle, Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.TestRunCancellationToken runCancellationToken) Line 85
	at /_/src/Adapter/MSTest.TestAdapter/Execution/TestExecutionManager.cs(85)
Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.dll!Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.MSTestExecutor.RunTests(System.Collections.Generic.IEnumerable<Microsoft.VisualStudio.TestPlatform.ObjectModel.TestCase> tests, Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IRunContext runContext, Microsoft.VisualStudio.TestPlatform.ObjectModel.Adapter.IFrameworkHandle frameworkHandle) Line 46
	at /_/src/Adapter/MSTest.TestAdapter/VSTestAdapter/MSTestExecutor.cs(46)
JetBrains.ReSharper.TestRunner.Adapters.MsTest.dll!JetBrains.ReSharper.TestRunner.Adapters.MsTest.Executor.RunAllCore(JetBrains.ReSharper.TestRunner.Adapters.MsTest.AdapterRunContext adapterContext) Line 70
	at Z:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\Adapters\TestRunner.Adapters.MsTest\Executor.cs(70)
JetBrains.ReSharper.TestRunner.Adapters.MsTest.dll!JetBrains.ReSharper.TestRunner.Adapters.MsTest.Executor.RunAll.AnonymousMethod__0() Line 46
	at Z:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\Adapters\TestRunner.Adapters.MsTest\Executor.cs(46)
System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread threadPoolThread, System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state) Line 192
	at System.Threading\ExecutionContext.cs(192)
System.Private.CoreLib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot, System.Threading.Thread threadPoolThread) Line 2194
	at System.Threading.Tasks\Task.cs(2194)
System.Private.CoreLib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch() Line 690
	at System.Threading\ThreadPoolWorkQueue.cs(690)
System.Private.CoreLib.dll!System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() Line 1328
	at System.Threading\PortableThreadPool.cs(1328)

## Output/Tests from VS 

Building Test Projects
Executing test method: mstest2.UnitTest1.TestMethod1
========== Starting test run ==========
========== Test run finished: 1 Tests (1 Passed, 0 Failed, 0 Skipped) run in 3.7 sec ==========
System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: element
   at MS.Internal.Media.VisualTreeUtils.AsNonNullVisual(DependencyObject element, Visual& visual, Visual3D& visual3D)
   at System.Windows.Media.VisualTreeHelper.GetChildrenCount(DependencyObject reference)
   at Microsoft.VisualStudio.TestWindow.Copilot.Summary.SummaryExtender.FindDescendant[T](DependencyObject parent)
   at Microsoft.VisualStudio.TestWindow.Copilot.Summary.SummaryExtender.TryFindSummaryDockPanel(DockPanel& summaryPanel, TextBlock& titleBox)
   at Microsoft.VisualStudio.TestWindow.Copilot.Summary.SummaryExtender.<CreateAskCopilotButton>d__22.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.VisualStudio.TestWindow.Copilot.Summary.SummaryExtender.get_AskCopilotBtn()
   at Microsoft.VisualStudio.TestWindow.Copilot.Summary.SummaryExtender.<UpdateAskCopilotButtonVisibilityAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Copilot.Summary.SummaryExtender.<>c__DisplayClass18_0.<<AppendContent>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.TestWindow.Copilot.Summary.SummaryExtender.AppendContent(ISummaryGenerator summaryGenerator, String indent, CancellationToken cancellation)
   at Microsoft.VisualStudio.TestWindow.Logging.ILoggerExtensions.CallInternalWithLogging(IInternalLogger log, Action action, Boolean shouldThrow)
---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null.
Parameter name: element
   at MS.Internal.Media.VisualTreeUtils.AsNonNullVisual(DependencyObject element, Visual& visual, Visual3D& visual3D)
   at System.Windows.Media.VisualTreeHelper.GetChildrenCount(DependencyObject reference)
   at Microsoft.VisualStudio.TestWindow.Copilot.Summary.SummaryExtender.FindDescendant[T](DependencyObject parent)
   at Microsoft.VisualStudio.TestWindow.Copilot.Summary.SummaryExtender.TryFindSummaryDockPanel(DockPanel& summaryPanel, TextBlock& titleBox)
   at Microsoft.VisualStudio.TestWindow.Copilot.Summary.SummaryExtender.<CreateAskCopilotButton>d__22.MoveNext()<---

## Unit test Sessions (ReSharper) Exception Details:

System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in System.Reflection\MethodBaseInvoker.cs:line 91
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) in System.Reflection\MethodBase.cs:line 221
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Extensions.MethodInfoExtensions.InvokeAsSynchronousTask(MethodInfo methodInfo, Object classInstance, Object[] parameters) in /_/src/Adapter/MSTest.TestAdapter/Extensions/MethodInfoExtensions.cs:line 157
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestMethodInfo.ExecuteInternal(Object[] arguments) in /_/src/Adapter/MSTest.TestAdapter/Execution/TestMethodInfo.cs:line 248

  This exception was originally thrown at this call stack:
    Microsoft.VisualStudio.TestTools.UnitTesting.Assert.ThrowAssertFailed(string, string) in Assert.cs
    Microsoft.VisualStudio.TestTools.UnitTesting.Assert.IsTrue(bool, string, object[]) in Assert.IsTrue.cs
    Microsoft.VisualStudio.TestTools.UnitTesting.Assert.IsTrue(bool) in Assert.IsTrue.cs
    mstest2.UnitTest1.TestMethod1() in UnitTest1.cs
    System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(object, System.Reflection.BindingFlags) in MethodBaseInvoker.cs

Inner Exception 1:
AssertFailedException: Assert.IsTrue failed.
