### ISSUE TITLE
Unstable unit test: System.Windows.Forms.Tests.TextBoxBaseTests.TextBoxBase_Copy_PasteNotEmptyWithHandle_Success

### ISSUE THREAD

**Issue by LeafShi1** [dotnet/winforms#11498]
Related https://github.com/dotnet/winforms/issues/11227

### Test

Unstable unit test: System.Windows.Forms.Tests.TextBoxBaseTests.TextBoxBase_Copy_PasteNotEmptyWithHandle_Success

### Issue description

The case failed in [PR build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=697188&view=ms.vss-test-web.build-test-results-tab&runId=17337604&resultId=111580&paneView=debug), the failed scenario:

- System.Windows.Forms.Tests.TextBoxBaseTests.TextBoxBase_Copy_PasteNotEmptyWithHandle_Success

**Error Message:**

- **In X86 unit:**

     - Assert.Equal() Failure: Strings differ
       ↓ (pos 0)
       Expected: "bcxt"
       Actual:   "xt"
       ↑ (pos 0)

**Stack trace:**

```
   at System.Windows.Forms.Tests.TextBoxBaseTests.TextBoxBase_Copy_PasteNotEmptyWithHandle_Success() in /_/src/System.Windows.Forms/tests/UnitTests/TextBoxBaseTests.cs:line 4246
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by LeafShi1** [comment]
Add the test case to Collection("Sequential") and enable it
