### ISSUE TITLE
Unstable unit test: System.Windows.Forms.Tests.TextBoxBaseTests.TextBoxBase_ClearUndo_CanUndo_Success

### ISSUE THREAD

**Issue by LeafShi1** [dotnet/winforms#11497]
Related #11227

### Test

System.Windows.Forms.Tests.TextBoxBaseTests.TextBoxBase_ClearUndo_CanUndo_Success

### Issue description

The case failed in [PR build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=697728&view=ms.vss-test-web.build-test-results-tab&runId=17356006&resultId=116280&paneView=debug), the pipeline link:

- https://dev.azure.com/dnceng-public/public/_build?definitionId=76&_a=summary

**Error Message:**

- **In X86 unit:**

     - Assert.Equal() Failure: Strings differ
      ↓ (pos 0)
      Expected: "bcxt"
      Actual:   "xt"
      ↑ (pos 0)

**Stack trace:**

```
   at System.Windows.Forms.Tests.TextBoxBaseTests.TextBoxBase_ClearUndo_CanUndo_Success() in /_/src/System.Windows.Forms/tests/UnitTests/TextBoxBaseTests.cs:line 4148
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by LeafShi1** [comment]
Add the test case to Collection("Sequential") and enable it
