### ISSUE TITLE
PropertyGrid.OnPropertyValueSet: NullReferenceException

### ISSUE THREAD

**Issue by ulfemsoy** [dotnet/winforms#11495]
### .NET version

.NET 6

OS: WINDOWS 10.0.22631
64 bit OS and process.
Language: English
Country: Philippines

### Did it work in .NET Framework?

Not tested/verified

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Not sure

### Issue description

I found the following exception in the log:

System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.PropertyGrid.OnPropertyValueSet(GridItem changedItem, Object oldValue)
   at System.Windows.Forms.PropertyGridInternal.PropertyGridView.CommitValue(GridEntry entry, Object value, Boolean closeDropDown)
   at System.Windows.Forms.PropertyGridInternal.PropertyGridView.CommitValue(Object value)
   at System.Windows.Forms.PropertyGridInternal.PropertyGridView.CommitText(String text)
   at System.Windows.Forms.PropertyGridInternal.PropertyGridView.Commit()
   at System.Windows.Forms.PropertyGridInternal.PropertyGridView.UnfocusSelection()
   at System.Windows.Forms.PropertyGridInternal.PropertyGridView.GridViewEdit.ProcessDialogKey(Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)

### Steps to reproduce

Issue found in log. Not sure how to reproduce.

**Comment by merriemcgaw** [comment]
@ulfemsoy there is not enough information for us to diagnose this issue. When you have more information on how you encountered this issue, please reopen this bug or create a new one with the details then we'd be happy to help!
