### ISSUE TITLE
Failing unit test: SiteNestedContainer_Add_Unloading_Nop

### ISSUE THREAD

**Issue by AdamYoblick** [dotnet/winforms#1151]
https://dev.azure.com/dnceng/internal/_build/results?buildId=229007&view=ms.vss-test-web.build-test-results-tab&runId=5675834&resultId=101249&paneView=debug

System.Exception : There is no designer for the class System.ComponentModel.Design.Tests.SiteNestedContainerTests+DisposingDesignerComponent.

Stack trace
at System.ComponentModel.Design.DesignerHost.AddToContainerPostProcess(IComponent component, String name, IContainer containerToAddTo) in F:\workspace\_work\1\s\src\System.Windows.Forms.Design\src\System\ComponentModel\Design\DesignerHost.cs:line 246
at System.ComponentModel.Design.SiteNestedContainer.Add(IComponent component, String name) in F:\workspace\_work\1\s\src\System.Windows.Forms.Design\src\System\ComponentModel\Design\SiteNestedContainer.cs:line 59
at System.ComponentModel.Container.Add(IComponent component)
at System.ComponentModel.Design.Tests.SiteNestedContainerTests.SiteNestedContainer_Add_Unloading_Nop() in F:\workspace\_work\1\s\src\System.Windows.Forms.Design\tests\UnitTests\System\ComponentModel\Design\SiteNestedContainerTests.cs:line 611

**Comment by hughbe** [comment]
Hmm this doesn't make much sense:

Maybe `BeginLoad` does some async stuff?
```cs
[Fact]
public void SiteNestedContainer_Add_Unloading_Nop()
{
    var surface = new SubDesignSurface();
    IDesignerLoaderHost2 host = surface.Host;
    surface.BeginLoad(typeof(RootDesignerComponent));
    INestedContainer container = surface.CreateNestedContainer(new Component(), "containerName");

    var component = new DisposingDesignerComponent();
    container.Add(component);
    int callCount = 0;
    DisposingDesigner.Disposed += (sender, e) =>
    {
        callCount++;
    };
    surface.Dispose();
    Assert.Equal(0, callCount);
}
```

**Comment by AdamYoblick** [comment]
Yeah I’m not sure, and it passed in release. So it’s most likely a race condition like you suggested. Either way it failed the build so I commented it out for now until we can fix it :)

________________________________

**Comment by weltkante** [comment]
Its not called `BeginLoad` because it does async stuff, but to mark the begin of an ongoing operation which takes more than one call to complete. Just like `BeginUpdate`/`EndUpdate` pairs mark an update operation on some controls. While technically it could kick off some background operation I don't think the default implementation does that, at least I never came across it.

So dismissing this as a race condition is likely to be wrong.

**Comment by AdamYoblick** [comment]
Well it failed in debug but passed in release, so it’s either some sort of race condition or something specific to the debug config. :)

Not meaning to dismiss it, just taking a guess. We’ll need to dig in to be sure. Commented it out in the meantime to get some build stability back.

________________________________

**Comment by JeremyKuhne** [comment]
DesignerHost_Add_ComponentDisposeThrowsDuringUnloadingDispose_ThrowsInvalidOperationException has been failing regularly with the same error.

https://dev.azure.com/dnceng/public/_build/results?buildId=266084&view=ms.vss-test-web.build-test-results-tab&runId=7239310&resultId=100000&paneView=history

**Comment by RussKie** [comment]
Related #1460
