### ISSUE TITLE
Assembly.GetType Throws Exception When Using ControlDesigner in Netcore using Microsoft SDK

### ISSUE THREAD

**Issue by ChidanandMurugaiah** [dotnet/winforms#11566]
### Environment

Visual Studio - Version 17.10.1
Edition - Windows 11 Enterprise
Version - 23H2
OS build - 22631.3737

### .NET version

Net8.0, Net7.0, Net6.0

### Did this work in a previous version of Visual Studio and/or previous .NET release?

It works without the [Microsoft.Winforms.Designer.SDK](https://www.nuget.org/packages/Microsoft.WinForms.Designer.SDK). It works properly in netframework.

### Issue description

We are implementing smart tags for .NET Core controls and have installed the [Microsoft.WinForms.Designer.SDK](https://www.nuget.org/packages/Microsoft.WinForms.Designer.SDK). However, when attempting to call the Assembly.GetCallingAssembly() method and subsequently the Assembly.GetType() method, a **System.Reflection.ReflectionTypeLoadException** is thrown. 

**Below code causes the exception**
`Assembly callingAsm = Assembly.GetCallingAssembly();`
`Type[] asmTypes = callingAsm.GetTypes();`

**Sample** - [ControlDesigner_Exception.zip](https://github.com/user-attachments/files/15911992/ControlDesigner_Exception.zip)

**Exception Image**
![image](https://github.com/dotnet/winforms/assets/124787498/3320f448-2285-4834-951c-f4fda19e5fd4)

### Steps to reproduce

1.Drag and drop the control CustomButton control from the Toolbox.
2.Run the sample.

Expected behavior: - Need to run without exception.

**Comment by elachlan** [comment]
@Olina-Zhang can your team please test when you can?

**Comment by Zheng-Li01** [comment]
Running the application failed with below exception on the latest 9.0.0-preview.6.24319.11.
![image](https://github.com/dotnet/winforms/assets/38325459/d2bb3c5b-3e28-4b22-9dcb-35940e902dc8)

```
Application: CustomControl.exe
CoreCLR Version: 9.0.24.31911
.NET Version: 9.0.0-preview.6.24319.11
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'Microsoft.DotNet.DesignTools.Server, Version=1.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
Could not load file or assembly 'Microsoft.DotNet.DesignTools.Server, Version=1.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
   at System.Reflection.RuntimeModule.GetDefinedTypes()
   at System.Reflection.RuntimeModule.GetTypes()
   at CustomControl.Form1..ctor() in C:\Users\v-zhgl\Downloads\ControlDesigner_Exception\Form1.cs:line 11
   at CustomControl.Program.Main() in C:\Users\v-zhgl\Downloads\ControlDesigner_Exception\Program.cs:line 14
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DotNet.DesignTools.Server, Version=1.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
File name: 'Microsoft.DotNet.DesignTools.Server, Version=1.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DotNet.DesignTools.Server, Version=1.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
File name: 'Microsoft.DotNet.DesignTools.Server, Version=1.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
```

**Comment by John-Qiao** [comment]
@elachlan we can repro this issue from .NET 6.0 to the latest .NET 9.0 P7, the exception result and repro steps all are same as the provided in initial issue.

**Comment by KlausLoeffelmann** [comment]
Couple of questions:

* Is this a runtime or a design-time issue? So, does this exception happen when you start the up or when you are trying to add the new control to the Form?
* Just to make sure, I understand the scenario: Why do you need to call those methods in constructor?

Can you

**Comment by John-Qiao** [comment]
@KlausLoeffelmann 

- It's a runtime issue, so this exception occurs when start the project.
- This exception does not occur when call those methods in Form load event or other control events.

**Comment by lonitra** [comment]
@ChidanandMurugaiah could you respond to the following questions:

> Couple of questions:
> 
> * Is this a runtime or a design-time issue? So, does this exception happen when you start the up or when you are trying to add the new control to the Form?
> * Just to make sure, I understand the scenario: Why do you need to call those methods in constructor?
> 
> Thanks!

**Comment by ChidanandMurugaiah** [comment]
@lonitra Sorry for the delay.

* I encountered a runtime issue when trying to start up the application. 
* We are using these methods to retrieve assembly types and then create a custom XML serializer based on these types within our application.

**Comment by nithisam22** [comment]
@lonitra, Is there any update regarding the System.Reflection.ReflectionTypeLoadException issue when using Microsoft.WinForms.Designer.SDK, as previously reported?
