### ISSUE TITLE
Unstable unit test: System.Windows.Forms.Tests.ListViewItem_IKeyboardToolTipTests.ListViewItemKeyboardToolTip_InvokeIsHoveredWithMouse_ReturnsExpected

### ISSUE THREAD

**Issue by LeafShi1** [dotnet/winforms#12319]
### Test

System.Windows.Forms.Tests.ListViewItem_IKeyboardToolTipTests.ListViewItemKeyboardToolTip_InvokeIsHoveredWithMouse_ReturnsExpected(insideListView: True, virtualMode: True, isHovered: True, expected: True)

### Issue description

The case failed in PR build, the failure scenario: 

ListViewItemKeyboardToolTip_InvokeIsHoveredWithMouse_ReturnsExpected(insideListView: True, virtualMode: True, isHovered: True, expected: True)

**Error Message:**

- **In X86 and X64 unit:**
     - Assert.Equal() Failure: Values differ
       Expected: True
       Actual:   False

**Stack trace:**

```
   at System.Windows.Forms.Tests.ListViewItem_IKeyboardToolTipTests.ListViewItemKeyboardToolTip_InvokeIsHoveredWithMouse_ReturnsExpected(Boolean insideListView, Boolean virtualMode, Boolean isHovered, Boolean expected) in /_/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.IKeyboardToolTipTests.cs:line 716
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
```

**Comment by Eales** [comment]
I am preparing a small, test-only fix for this: supply controlled accessibility bounds instead of moving the physical cursor, and restore the disabled virtual-mode case. I checked the open PR file lists and did not find overlapping work. I will keep unrelated ListView layout tests out of the PR.
