### ISSUE TITLE
The specified structure must be blittable or have layout information.

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#1558]
* .NET Core Version: 
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview6-012264
 Commit:    be3f0c1a03

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\

Host (useful for support):
  Version: 3.0.0-preview8-28380-08
  Commit:  c855ac7187

.NET Core SDKs installed:
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009677 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009696 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009711 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  3.0.100-preview5-011568 [C:\Program Files\dotnet\sdk]
  3.0.100-preview6-012264 [C:\Program Files\dotnet\sdk]
  3.0.100-preview8-013437 [C:\Program Files\dotnet\sdk]
  3.0.100-preview8-013640 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19374.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19381.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27823-05 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27824-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-27916-10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-27917-07 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28373-17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28376-02 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28379-05 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28380-08 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview8-28373-17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview8-28380-08 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
* Have you experienced this same bug with .NET Framework?: No

**Problem description:**

Incorrect p/invoke definitions?

**Actual behavior:** 

![image](https://user-images.githubusercontent.com/4403806/62374120-e622fe00-b543-11e9-8e03-0d59dbdf6e2f.png)

```
System.ArgumentException
  HResult=0x80070057
  Message=The specified structure must be blittable or have layout information. 
  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.InteropServices.Marshal.PtrToStructureHelper(IntPtr ptr, Object structure, Boolean allowValueClasses)
   at System.Runtime.InteropServices.Marshal.PtrToStructureHelper(IntPtr ptr, Type structureType)
```

**Expected behavior:**

No exceptions

**Minimal repro:**

1. Checkout 8437748b9bad0f8311218afb0f040dfaf8fdd737
2. (optional) Run `.\build-local.ps1` to have the latest sdk/app and necessary bindgings
3. Build and run `WinformsControlsTest` project
4. Update "Exception Settings" to break on `System.ArgumentException`
4. Click [Collection Editors] button
5. Edit "StringArray" property via the UI editor (ignore AEs in `AccessibilityObject`, if any - #1556)
6. Modify the selected value but do NOT commit it (i.e. don't hit <kbd>ENTER</kbd>)
7. Move mouse
6. Observe VS to break on the exception

**Comment by weltkante** [comment]
PR #1246 removed `[StructLayout(LayoutKind.Sequential)]` from `MOUSEHOOKSTRUCT`. However `MOUSEHOOKSTRUCT` is a class and not a struct, so the attribute is not optional. (According to [this](https://github.com/dotnet/winforms/pull/1247#discussion_r299184957) discussion StructLayout(Sequential) on struct is optional).

**Comment by JeremyKuhne** [comment]
Yes, I crossed streams with this one. I'll put up the fix shortly.

**Comment by RussKie** [comment]
Thank you @weltkante, it is great you're keeping track of discussions and changes 👍 Thank you.
