### ISSUE TITLE
Flaky test: `AxHost_GetIPictureDispFromPicture_InvokeEnhancedMetafile_Roundtrips`

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#2005]
* .NET Core Version: master @ 3750c43d5d9b5161be967e39fd848c89d6479ff5

**Problem description:**

`AxHost_GetIPictureDispFromPicture_InvokeEnhancedMetafile_Roundtrips` test fails on CI but is passing locally.
E.g.
- https://dev.azure.com/dnceng/public/_build/results?buildId=371654&view=ms.vss-test-web.build-test-results-tab&runId=11320176&resultId=113727&paneView=debug
- https://dev.azure.com/dnceng/public/_build/results?buildId=371508&view=ms.vss-test-web.build-test-results-tab&runId=11308766&resultId=113727&paneView=debug

```

Error message
System.Runtime.InteropServices.ExternalException : A generic error occurred in GDI+.

Stack trace
   at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
   at System.Drawing.Imaging.Metafile..ctor(IntPtr henhmetafile, Boolean deleteEmf)
   at System.Windows.Forms.AxHost.GetPictureFromParams(UInt32 handle, PICTYPE type, UInt32 paletteHandle, Int32 width, Int32 height) in D:\a\1\s\src\System.Windows.Forms\src\System\Windows\Forms\AxHost.cs:line 5085
   at System.Windows.Forms.AxHost.GetPictureFromIPicture(Object picture) in D:\a\1\s\src\System.Windows.Forms\src\System\Windows\Forms\AxHost.cs:line 5029
   at System.Windows.Forms.Tests.AxHostTests.SubAxHost.GetPictureFromIPicture(Object picture) in D:\a\1\s\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\AxHostTests.cs:line 1370
   at System.Windows.Forms.Tests.AxHostTests.AxHost_GetIPictureDispFromPicture_InvokeEnhancedMetafile_Roundtrips() in D:\a\1\s\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\AxHostTests.cs:line 1210
```

**Expected behavior:**

The test pass

/cc: @hughbe

**Comment by weltkante** [comment]
As noted on the other similar issues this test also seems to be not running on STA, being only annotated with a `[Fact]` attribute. Considering that `OleInitialize` native API initializes the thread to STA I'd expect all OLE functions to require STA ...

**Comment by weltkante** [comment]
Test failure is independent from OleInitialize.

**Comment by weltkante** [comment]
This is an interop mistake, see #2004 for more details
