### ISSUE TITLE
Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies

### ISSUE THREAD

**Issue by cleitonfelipe** [dotnet/winforms#2142]
* .NET Core Version: 3.0.1
OS version: win10 64-bit

* Have you experienced this same bug with .NET Framework?: Yes

**Problem description:**
I'm creating an app WinForms and when I double-click in Forms.cs after load extension winformsdesigner.setup.vsix, I get this error Could not load file or assembly 'System.Runtime, Version=4.2.2.0,  Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. 

**Actual behavior:** 

```cs
at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String  codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint,  StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean  throwOnFileNotFound, Boolean forIntrospection, Boolean  suppressSecurityChecks)
at  System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase,  Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&  stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean  forIntrospection, Boolean suppressSecurityChecks)
at  System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName  assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly,  StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean  throwOnFileNotFound, Boolean forIntrospection, Boolean  suppressSecurityChecks)at System.Reflection.Assembly.Load(AssemblyName  assemblyRef)
at  Microsoft.VisualStudio.Design.VSTypeResolutionService.System.ComponentModel.Design.IDesignTimeAssemblyLoader.LoadRuntimeAssembly(AssemblyName  targetAssemblyName)
at  Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUniverse.LoadRuntimeAssembly(AssemblyName  assemblyName)
at  Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUtil.GetRuntimeType(Type  type)
at  Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkType.TryGetRuntimeType()
at  Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUtil.EnsureRuntimeType(Type  type)
at  Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUtil.GetCustomAttributes(ICustomAttributesDataProvider  member, Type filter, CustomAttributesCache cache)
at  Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUtil.GetCustomAttributes(Type  type, Type filter, Boolean inherit, CustomAttributesCache cache)
at  Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkType.GetCustomAttributes(Type  filter, Boolean inherit)
at  Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkAttributeCollection.GetAttributes(Type  type, Type filter)
at  Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkAttributeCollection.GetAttributes(MemberInfo  member, Type filter)
at  Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkAttributeCollection.get_Attributes()
at  Microsoft.VisualStudio.Design.VSDesignSurface.EnsureExtensions(IComponent  component)
at  Microsoft.VisualStudio.Design.VSDesignSurface.CreateInstance(Type type)
at  System.ComponentModel.Design.DesignerHost.System.ComponentModel.Design.IDesignerHost.CreateComponent(Type  componentType, String name)
at  System.ComponentModel.Design.Serialization.DesignerSerializationManager.CreateInstance(Type  type, ICollection arguments, String name, Boolean addToContainer)
at  System.ComponentModel.Design.Serialization.DesignerSerializationManager.System.ComponentModel.Design.Serialization.IDesignerSerializationManager.CreateInstance(Type  type, ICollection arguments, String name, Boolean addToContainer)
at  System.ComponentModel.Design.Serialization.TypeCodeDomSerializer.Deserialize(IDesignerSerializationManager  manager, CodeTypeDeclaration declaration)
at  System.ComponentModel.Design.Serialization.CodeDomDesignerLoader.PerformLoad(IDesignerSerializationManager  manager)
at  Microsoft.VisualStudio.Design.Serialization.CodeDom.VSCodeDomDesignerLoader.PerformLoad(IDesignerSerializationManager  serializationManager)
--- End of stack trace from previous location where  exception was thrown ---
at  Microsoft.VisualStudio.Design.Serialization.CodeDom.VSCodeDomDesignerLoader.PerformLoad(IDesignerSerializationManager  serializationManager)
at  System.ComponentModel.Design.Serialization.BasicDesignerLoader.BeginLoad(IDesignerLoaderHost  host) | at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String  codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint,  StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean  throwOnFileNotFound, Boolean forIntrospection, Boolean  suppressSecurityChecks)
at  System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase,  Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&  stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean  forIntrospection, Boolean suppressSecurityChecks)
at  System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName  assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly,  StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean  throwOnFileNotFound, Boolean forIntrospection, Boolean  suppressSecurityChecks)at System.Reflection.Assembly.Load(AssemblyName  assemblyRef)
at  Microsoft.VisualStudio.Design.VSTypeResolutionService.System.ComponentModel.Design.IDesignTimeAssemblyLoader.LoadRuntimeAssembly(AssemblyName  targetAssemblyName)
at  Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUniverse.LoadRuntimeAssembly(AssemblyName  assemblyName)
at  Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUtil.GetRuntimeType(Type  type)
at  Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkType.TryGetRuntimeType()
at  Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUtil.EnsureRuntimeType(Type  type)
at  Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUtil.GetCustomAttributes(ICustomAttributesDataProvider  member, Type filter, CustomAttributesCache cache)
at  Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUtil.GetCustomAttributes(Type  type, Type filter, Boolean inherit, CustomAttributesCache cache)
at  Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkType.GetCustomAttributes(Type  filter, Boolean inherit)
at  Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkAttributeCollection.GetAttributes(Type  type, Type filter)
at  Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkAttributeCollection.GetAttributes(MemberInfo  member, Type filter)
at  Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkAttributeCollection.get_Attributes()
at  Microsoft.VisualStudio.Design.VSDesignSurface.EnsureExtensions(IComponent  component)
at  Microsoft.VisualStudio.Design.VSDesignSurface.CreateInstance(Type type)
at  System.ComponentModel.Design.DesignerHost.System.ComponentModel.Design.IDesignerHost.CreateComponent(Type  componentType, String name)
at  System.ComponentModel.Design.Serialization.DesignerSerializationManager.CreateInstance(Type  type, ICollection arguments, String name, Boolean addToContainer)
at  System.ComponentModel.Design.Serialization.DesignerSerializationManager.System.ComponentModel.Design.Serialization.IDesignerSerializationManager.CreateInstance(Type  type, ICollection arguments, String name, Boolean addToContainer)
at  System.ComponentModel.Design.Serialization.TypeCodeDomSerializer.Deserialize(IDesignerSerializationManager  manager, CodeTypeDeclaration declaration)
at  System.ComponentModel.Design.Serialization.CodeDomDesignerLoader.PerformLoad(IDesignerSerializationManager  manager)
at  Microsoft.VisualStudio.Design.Serialization.CodeDom.VSCodeDomDesignerLoader.PerformLoad(IDesignerSerializationManager  serializationManager)
--- End of stack trace from previous location where  exception was thrown ---
at  Microsoft.VisualStudio.Design.Serialization.CodeDom.VSCodeDomDesignerLoader.PerformLoad(IDesignerSerializationManager  serializationManager)
at  System.ComponentModel.Design.Serialization.BasicDesignerLoader.BeginLoad(IDesignerLoaderHost  host) | at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String  codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint,  StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean  throwOnFileNotFound, Boolean forIntrospection, Boolean  suppressSecurityChecks)
at  System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase,  Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&  stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean  forIntrospection, Boolean suppressSecurityChecks)
at  System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName  assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly,  StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean  throwOnFileNotFound, Boolean forIntrospection, Boolean  suppressSecurityChecks)at System.Reflection.Assembly.Load(AssemblyName  assemblyRef)
at  Microsoft.VisualStudio.Design.VSTypeResolutionService.System.ComponentModel.Design.IDesignTimeAssemblyLoader.LoadRuntimeAssembly(AssemblyName  targetAssemblyName)
at  Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUniverse.LoadRuntimeAssembly(AssemblyName  assemblyName)
at  Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUtil.GetRuntimeType(Type  type)
at  Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkType.TryGetRuntimeType()
at  Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUtil.EnsureRuntimeType(Type  type)
at  Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUtil.GetCustomAttributes(ICustomAttributesDataProvider  member, Type filter, CustomAttributesCache cache)
at  Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkUtil.GetCustomAttributes(Type  type, Type filter, Boolean inherit, CustomAttributesCache cache)
at  Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkType.GetCustomAttributes(Type  filter, Boolean inherit)
at  Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkAttributeCollection.GetAttributes(Type  type, Type filter)
at  Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkAttributeCollection.GetAttributes(MemberInfo  member, Type filter)
at  Microsoft.VisualStudio.Shell.Design.VsTargetFrameworkAttributeCollection.get_Attributes()
at  Microsoft.VisualStudio.Design.VSDesignSurface.EnsureExtensions(IComponent  component)
at  Microsoft.VisualStudio.Design.VSDesignSurface.CreateInstance(Type type)
at  System.ComponentModel.Design.DesignerHost.System.ComponentModel.Design.IDesignerHost.CreateComponent(Type  componentType, String name)
at  System.ComponentModel.Design.Serialization.DesignerSerializationManager.CreateInstance(Type  type, ICollection arguments, String name, Boolean addToContainer)
at  System.ComponentModel.Design.Serialization.DesignerSerializationManager.System.ComponentModel.Design.Serialization.IDesignerSerializationManager.CreateInstance(Type  type, ICollection arguments, String name, Boolean addToContainer)
at  System.ComponentModel.Design.Serialization.TypeCodeDomSerializer.Deserialize(IDesignerSerializationManager  manager, CodeTypeDeclaration declaration)
at  System.ComponentModel.Design.Serialization.CodeDomDesignerLoader.PerformLoad(IDesignerSerializationManager  manager)
at  Microsoft.VisualStudio.Design.Serialization.CodeDom.VSCodeDomDesignerLoader.PerformLoad(IDesignerSerializationManager  serializationManager)
--- End of stack trace from previous location where  exception was thrown ---
at  Microsoft.VisualStudio.Design.Serialization.CodeDom.VSCodeDomDesignerLoader.PerformLoad(IDesignerSerializationManager  serializationManager)
at  System.ComponentModel.Design.Serialization.BasicDesignerLoader.BeginLoad(IDesignerLoaderHost  host)
```

**Expected behavior:**
Show Design Window from WinForms

**Minimal repro:**
Create a new WinForms App (.Net Core) with extension winformsdesigner.setup.vsix installled.

![erro_WinForms](https://user-images.githubusercontent.com/4966736/67249899-b814d200-f43f-11e9-84d5-ba1bada62823.jpg)

**Comment by cleitonfelipe** [comment]
This issue I close because this error is not happening more, but I get another error I´ll create a new topic in here.

**Comment by merriemcgaw** [comment]
@cleitonfelipe is this happening again for you? It looks like you closed it and reopened it on the same day.

**Comment by merriemcgaw** [comment]
@DustinCampbell any thoughts?

**Comment by cleitonfelipe** [comment]
> @cleitonfelipe is this happening again for you? It looks like you closed it and reopened it on the same day.

Hi @merriemcgaw this error happing sometimes, I closed but I open again because I think this can happing in another person.

**Comment by merriemcgaw** [comment]
This does not appear to be happening any more now that we've moved the designer directly into VS. You can get the latest updates by installing the preview version of VS and enabling the WinForms Core Designer in Tools->Options ->Preview Features.
In the future, probably the best way to interact when it comes to the designer is to use Developer Community or the VS Feedback Tool. That will help us with gathering some diagnostic information (if you approve it that is) that is hard to gather via GitHub.
