### ISSUE TITLE
ImageCollection_IListItem_SetWithHandle_GetReturnsExpected appears to be flakey

### ISSUE THREAD

**Issue by hughbe** [dotnet/winforms#2686]
https://dev.azure.com/dnceng/public/_test/analytics?definitionId=267&contextType=build

https://dev.azure.com/dnceng/public/_build/results?buildId=479537&view=ms.vss-test-web.build-test-results-tab

> System.InvalidOperationException : Image cannot be added to the ImageList.
   at System.Windows.Forms.ImageList.AddToHandle(Bitmap bitmap) in /_/src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs:line 548
   at System.Windows.Forms.ImageList.CreateHandle() in /_/src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs:line 617
   at System.Windows.Forms.ImageList.get_Handle() in /_/src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs:line 218
   at System.Windows.Forms.Tests.ImageCollectionTests.ImageCollection_IListItem_SetWithHandle_GetReturnsExpected(Color transparentColor, Image value) in /_/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ImageList.ImageCollectionTests.cs:line 1645

**Comment by weltkante** [comment]
First link says `Control_OnPaintBackground_InvokeWithParent_CallsPaint` failed
Second link says `ImageCollection_IListItem_SetWithHandle_GetReturnsExpected` failed
Line 1645 in ImageCollectionTests.cs is the latter, so stack trace probably belongs to that
None say something about `ImageCollection_Add_InvokeIconWithHandle_Success` so if you did some investigation you may want to add some more details how these 3 failures are connected?

**Comment by hughbe** [comment]
Sorry, updated the title: this issue relates to `ImageCollection_IListItem_SetWithHandle_GetReturnsExpected`

`Control_OnPaintBackground_InvokeWithParent_CallsPaint` and associated failures have been fixed because we had timing bug in `Application.EnableVisualStyles` calls in the tests

**Comment by RussKie** [comment]
All tests appear green now... ¯\_(ツ)_/¯

**Comment by hughbe** [comment]
Can’t repro
