### ISSUE TITLE
WindowsFormsSynchronizationContext fails to construct

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/winforms#2728]
It appears that there is a thread safety issue with `ThreadContext`. This came up in #2603.

Here is the debug runtime stack:

```
The active test run was aborted. Reason: Test host process crashed : Process terminated. Assertion failed.
hash table insert failed!  Load factor too high, or our double hashing function is incorrect.
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   at System.Collections.Hashtable.set_Item(Object key, Object value)
   at System.Windows.Forms.Application.ThreadContext..ctor()
   at System.Windows.Forms.Application.ThreadContext.FromCurrent()
   at System.Windows.Forms.WindowsFormsSynchronizationContext..ctor()
   at Xunit.Sdk.WinFormsSynchronizationContextAdapter.Create()
   at Xunit.Sdk.UITestInvoker.<RunAsync>b__2_0()
   at Xunit.Sdk.UITestInvoker.<>c__DisplayClass3_0.<RunOnSTA>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

In release you get:

```
System.InvalidOperationException : Hashtable insert failed. Load factor too high. The most common cause is multiple threads writing to the Hashtable simultaneously.
```

**Comment by RussKie** [comment]
This is a duplicate of https://github.com/dotnet/winforms/issues/2706, and is fixed in https://github.com/dotnet/winforms/pull/2713
Are you running the latest master?

**Comment by JeremyKuhne** [comment]
Thanks @RussKie, missed that. Yes, that is the fix for it. :)

Duplicate of #2706
