### ISSUE TITLE
WebBrowser.Dispose can throw Win32Exception randomly

### ISSUE THREAD

**Issue by hughbe** [dotnet/winforms#2961]
This occasionally fails with the following stack trace

```cs
[WinFormsTheory]
[CommonMemberData(nameof(CommonTestHelper.GetBoolTheoryData))]
public void WebBrowser_ScriptErrorsSuppressed_SetWithInstance_GetReturnsExpected(bool value)
{
    using var parent = new Control();
    using var control = new WebBrowser
    {
        Parent = parent
    };

    control.ScriptErrorsSuppressed = value;
    Assert.Equal(value, control.ScriptErrorsSuppressed);
    Assert.NotNull(control.ActiveXInstance);
    Assert.Equal(value, ((IWebBrowser2)control.ActiveXInstance).Silent);
    Assert.True(control.IsHandleCreated);

    // Set same.
    control.ScriptErrorsSuppressed = value;
    Assert.Equal(value, control.ScriptErrorsSuppressed);
    Assert.NotNull(control.ActiveXInstance);
    Assert.Equal(value, ((IWebBrowser2)control.ActiveXInstance).Silent);
    Assert.True(control.IsHandleCreated);

    // Set different.
    control.ScriptErrorsSuppressed = !value;
    Assert.Equal(!value, control.ScriptErrorsSuppressed);
    Assert.NotNull(control.ActiveXInstance);
    Assert.True(control.IsHandleCreated);
}
```

```
System.Windows.Forms.Tests.WebBrowserTests.WebBrowser_ScriptErrorsSuppressed_SetWithInstance_GetReturnsExpected(value: False) [10ms]
  Error Message:
   System.ComponentModel.Win32Exception : Error creating window handle.
  Stack Trace:
     at System.Windows.Forms.NativeWindow.CreateHandle(CreateParams cp)
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Application.ParkHandle(CreateParams cp, DpiAwarenessContext dpiAwarenessContext)
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.WebBrowserBase.FindContainerControlInternal()
   at System.Windows.Forms.WebBrowserBase.get_ContainingControl()
   at System.Windows.Forms.WebBrowserContainer.FindContainerForControl(WebBrowserBase ctl)
   at System.Windows.Forms.WebBrowserBase.GetParentContainer()
   at System.Windows.Forms.WebBrowserBase.TransitionFromRunningToLoaded()
   at System.Windows.Forms.WebBrowserBase.TransitionDownTo(AXState state)
   at System.Windows.Forms.WebBrowser.Dispose(Boolean disposing)
```

We certainly shouldn't be calling `CreateHandle` in `Control.Dispose`!

I think the problem is that we're calling `WebBrowserBase.FindContainerControlInternal`
```cs
internal ContainerControl FindContainerControlInternal()
{
    // ...

    if (cc == null)
    {
        cc = Control.FromHandle(User32.GetParent(this)) as ContainerControl;
    }

    ...
    return cc;
}
```

We should guard the call to `User32.GetParent` with `!IsDisposed` or `IsHandleCreated`

**Comment by weltkante** [comment]
Might be fallout of previous refactoring of `HandleRef(this, HandleInternal) ` to using the `IHandle` interface, see #2947

**Comment by hughbe** [comment]
Can repro in .Net Framework too
