### ISSUE TITLE
Adding a ToolStripDropDown child to ToolStripPanel throws NRE

### ISSUE THREAD

**Issue by hughbe** [dotnet/winforms#2973]
```cs
[WinFormsFact]
public void Test()
{
    using var control = new ToolStripDropDown
    {
        TopLevel = false
    };
    using var parent = new ToolStripPanel();
    parent.Controls.Add(control);
}
```

```
  Error Message:
   System.NullReferenceException : Object reference not set to an instance of an object.
  Stack Trace:
     at System.Windows.Forms.Layout.FlowLayout.xLayoutRow(ContainerProxy containerProxy, ElementProxy elementProxy, Int32 startIndex, Int32 endIndex, Rectangle rowBounds, Int32& breakIndex, Boolean measureOnly)
   at System.Windows.Forms.Layout.FlowLayout.xLayout(IArrangedElement container, Rectangle displayRect, Boolean measureOnly)
   at System.Windows.Forms.Layout.FlowLayout.GetPreferredSize(IArrangedElement container, Size proposedConstraints)
   at System.Windows.Forms.ToolStripPanelRow.System.Windows.Forms.Layout.IArrangedElement.GetPreferredSize(Size constrainingSize)
   at System.Windows.Forms.Layout.FlowLayout.VerticalElementProxy.GetPreferredSize(Size proposedSize)
   at System.Windows.Forms.Layout.FlowLayout.xLayoutRow(ContainerProxy containerProxy, ElementProxy elementProxy, Int32 startIndex, Int32 endIndex, Rectangle rowBounds, Int32& breakIndex, Boolean measureOnly)
   at System.Windows.Forms.Layout.FlowLayout.xLayout(IArrangedElement container, Rectangle displayRect, Boolean measureOnly)
   at System.Windows.Forms.Layout.FlowLayout.LayoutCore(IArrangedElement container, LayoutEventArgs args)
   at System.Windows.Forms.Layout.LayoutEngine.Layout(Object container, LayoutEventArgs layoutEventArgs)
   at System.Windows.Forms.Control.OnLayout(LayoutEventArgs levent)
   at System.Windows.Forms.ToolStripPanel.OnLayout(LayoutEventArgs e)
   at System.Windows.Forms.Control.PerformLayout(LayoutEventArgs args)
   at System.Windows.Forms.Control.PerformLayout()
   at System.Windows.Forms.Control.ResumeLayout(Boolean performLayout)
   at System.Windows.Forms.Control.SetBoundsCore(Int32 x, Int32 y, Int32 width, Int32 height, BoundsSpecified specified)
   at System.Windows.Forms.ToolStrip.SetBoundsCore(Int32 x, Int32 y, Int32 width, Int32 height, BoundsSpecified specified)
   at System.Windows.Forms.ToolStripDropDown.SetBoundsCore(Int32 x, Int32 y, Int32 width, Int32 height, BoundsSpecified specified)
   at System.Windows.Forms.Control.SetBounds(Int32 x, Int32 y, Int32 width, Int32 height, BoundsSpecified specified)
   at System.Windows.Forms.Control.set_Size(Size value)
   at System.Windows.Forms.ToolStripDropDown.AdjustSize()
   at System.Windows.Forms.ToolStripDropDown.OnLayout(LayoutEventArgs e)
   at System.Windows.Forms.Control.PerformLayout(LayoutEventArgs args)
   at System.Windows.Forms.Control.PerformLayout()
   at System.Windows.Forms.Control.ResumeLayout(Boolean performLayout)
   at System.Windows.Forms.Layout.LayoutTransaction.Dispose()
   at System.Windows.Forms.ToolStripPanel.ToolStripPanelControlCollection.AddInternal(Control value)
   at System.Windows.Forms.Tests.ControlTests.T() in C:\Users\hughbe\source\repos\ConsoleApp\ControlTests.cs:line 42
```

**Comment by elachlan** [comment]
The `ElementProxy` has its `Element` property set prior to `ParticipatesInLayout` being called. 
https://github.com/dotnet/winforms/blob/0dca79af5c537127e0fbfcfd857baa4bb8233174/src/System.Windows.Forms/src/System/Windows/Forms/Layout/FlowLayout.cs#L191-L197

So I guess there is a null value in the `ArrangedElementCollection`?

```
Message: 
  System.NullReferenceException : Object reference not set to an instance of an object.

Stack Trace: 
  ElementProxy.get_ParticipatesInLayout() line 75
  FlowLayout.TryCalculatePreferredSizeRow(ContainerProxy containerProxy, ElementProxy elementProxy, Int32 startIndex, Int32 endIndex, Rectangle rowBounds, Int32& breakIndex, Boolean measureOnly) line 195
  FlowLayout.MeasureRow(ContainerProxy containerProxy, ElementProxy elementProxy, Int32 startIndex, Rectangle displayRectangle, Int32& breakIndex) line 173
  FlowLayout.TryCalculatePreferredSize(IArrangedElement container, Rectangle displayRect, Boolean measureOnly) line 124
  FlowLayout.GetPreferredSize(IArrangedElement container, Size proposedConstraints) line 57
  IArrangedElement.GetPreferredSize(Size constrainingSize) line 694
  ElementProxy.GetPreferredSize(Size proposedSize) line 90
  VerticalElementProxy.GetPreferredSize(Size proposedSize) line 58
  FlowLayout.TryCalculatePreferredSizeRow(ContainerProxy containerProxy, ElementProxy elementProxy, Int32 startIndex, Int32 endIndex, Rectangle rowBounds, Int32& breakIndex, Boolean measureOnly) line 215
  FlowLayout.MeasureRow(ContainerProxy containerProxy, ElementProxy elementProxy, Int32 startIndex, Rectangle displayRectangle, Int32& breakIndex) line 173
  FlowLayout.TryCalculatePreferredSize(IArrangedElement container, Rectangle displayRect, Boolean measureOnly) line 124
  FlowLayout.LayoutCore(IArrangedElement container, LayoutEventArgs args) line 38
  LayoutEngine.Layout(Object container, LayoutEventArgs layoutEventArgs) line 44
  Control.OnLayout(LayoutEventArgs levent) line 8232
  ScrollableControl.OnLayout(LayoutEventArgs levent) line 630
  ContainerControl.OnLayout(LayoutEventArgs e) line 934
  ToolStripPanel.OnLayout(LayoutEventArgs e) line 512
  Control.PerformLayout(LayoutEventArgs args) line 8947
  Control.PerformLayout() line 8893
  Control.ResumeLayout(Boolean performLayout) line 10069
  Control.SetBoundsCore(Int32 x, Int32 y, Int32 width, Int32 height, BoundsSpecified specified) line 10849
  ToolStrip.SetBoundsCore(Int32 x, Int32 y, Int32 width, Int32 height, BoundsSpecified specified) line 2815
  ToolStripDropDown.SetBoundsCore(Int32 x, Int32 y, Int32 width, Int32 height, BoundsSpecified specified) line 1717
  Control.SetBounds(Int32 x, Int32 y, Int32 width, Int32 height, BoundsSpecified specified) line 10741
  Control.set_Size(Size value) line 3385
  ToolStripDropDown.AdjustSize() line 999
  ToolStripDropDown.OnLayout(LayoutEventArgs e) line 1310
  Control.PerformLayout(LayoutEventArgs args) line 8947
  Control.PerformLayout() line 8893
  Control.ResumeLayout(Boolean performLayout) line 10069
  LayoutTransaction.Dispose() line 68
  ToolStripPanelControlCollection.AddInternal(Control value) line 28
  ReadOnlyControlCollection.Add(Control value) line 30
  TypedControlCollection.Add(Control value) line 49
  ToolStripPanelTests.Test() line 22
```

**Comment by rickbrew** [comment]
I think this is the same bug that I have a hacky (reflection) workaround in Paint.NET for.

```cs
private sealed class ShapeTypeDropDown
    : ToolStripDropDown
{
    public ShapeTypeDropDown(ToolStripItem owner)
    {
        // HACK: Seems to be a bug in WinForms! (null-ref)
        // TODO: File issue in dotnet/winforms and fix this
        //       It might be this: https://github.com/dotnet/winforms/issues/2973
        FieldInfo isAutoGeneratedFieldInfo = typeof(ToolStripDropDown).GetField("isAutoGenerated", BindingFlags.Instance | BindingFlags.NonPublic);
        Debug.Assert(isAutoGeneratedFieldInfo != null);
        if (isAutoGeneratedFieldInfo != null)
        {
            isAutoGeneratedFieldInfo.SetValue(this, BooleanUtil.GetBoxed(true));
        }

        FieldInfo ownerItemFieldInfo = typeof(ToolStripDropDown).GetField("ownerItem", BindingFlags.Instance | BindingFlags.NonPublic);
        Debug.Assert(ownerItemFieldInfo != null);
        if (ownerItemFieldInfo != null)
        {
            ownerItemFieldInfo.SetValue(this, owner);
        }
    }

    protected override LayoutSettings CreateLayoutSettings(ToolStripLayoutStyle style)
    {
        LayoutSettings layoutSettings = base.CreateLayoutSettings(style);

        if (style == ToolStripLayoutStyle.Flow)
        {
            FlowLayoutSettings flowLayoutSettings = layoutSettings as FlowLayoutSettings;
            flowLayoutSettings.FlowDirection = System.Windows.Forms.FlowDirection.LeftToRight;
            flowLayoutSettings.WrapContents = true;
            return flowLayoutSettings;
        }

        return layoutSettings;
    }

    protected override Padding DefaultPadding
    {
        get => new Padding(2, 0, 2, 3);
    }
}
```

**Comment by merriemcgaw** [comment]
@Olina-Zhang when your team has a chance can we confirm this is still a problem? I'll add it to .NET 9 backlog.

**Comment by Olina-Zhang** [comment]
@merriemcgaw Yes, can repro it in the latest .Net 8.0 SDK build.

**Comment by JeremyKuhne** [comment]
At the very least here we should be throwing an argument exception. I wouldn't worry much beyond that without a user report.
