### ISSUE TITLE
NullReferenceException when removing items from a CheckedListBox in the ItemCheck handler

### ISSUE THREAD

**Issue by AustinWise** [dotnet/winforms#3084]
* .NET Core Version: 3.1.3

* Have you experienced this same bug with .NET Framework?: On 3.5, no. On 4.8 (Windows 10 178363.778), yes. I suspected this exception did not happen on some earlier versions of .NET Framework 4.x.

**Problem description:**

NullReferenceException from WinForms code after removing items from a CheckedListBox in the ItemCheck handler:

```
   at System.Windows.Forms.CheckedListBox.CheckedItemCollection.SetCheckedState(Int32 index, CheckState value)
   at System.Windows.Forms.CheckedListBox.LbnSelChange()
   at System.Windows.Forms.CheckedListBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ListBox.WndProc(Message& m)
   at System.Windows.Forms.CheckedListBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Expected behavior:**
I'm not sure how legitimate this bug is, as it does seem a bit questionable to clear the list of Items in an ItemChecked handler. However the the documentation makes no mention of this not being supported and it used to work (though perhaps by chance).

**Minimal repro:**

```csharp
using System;
using System.Windows.Forms;

namespace ConsoleApp4
{
    class Program : Form
    {
        [STAThread]
        static void Main(string[] args)
        {
            Application.EnableVisualStyles();
            Application.Run(new Program());
        }

        readonly CheckedListBox mLb;

        Program()
        {
            mLb = new CheckedListBox();
            mLb.Dock = DockStyle.Fill;
            mLb.Items.Add("A");
            mLb.Items.Add("B");
            mLb.Items.Add("C");
            mLb.ItemCheck += MLb_ItemCheck;
            this.Controls.Add(mLb);
        }

        private void MLb_ItemCheck(object sender, ItemCheckEventArgs e)
        {
            mLb.Items.Clear();
            //program crashes after this callback returns
        }
    }
}
```

**Comment by RussKie** [comment]
I tried your sample, and the issue repro'd all the way back to net45.

It fails here, which kind of makes sense:
![image](https://user-images.githubusercontent.com/4403806/79724315-a8ad0d80-832a-11ea-88a0-08033c1549b1.png)

I agree with your assessment that it is an edge case, and should be marked with "don't do it at home" kind of label.
