### ISSUE TITLE
`Clipboard` API must check for invalid `format`

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#3163]
* .NET Core Version: current master

* Have you experienced this same bug with .NET Framework?: Yes

**Problem description:**

Observed in https://dev.azure.com/dnceng/public/_build/results?buildId=622784&view=results

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.DataObject.OleConverter.GetDataFromOleOther(String format) in F:\workspace\_work\1\s\src\System.Windows.Forms\src\System\Windows\Forms\DataObject.cs:line 1435
   at System.Windows.Forms.DataObject.OleConverter.GetDataFromBoundOleDataObject(String format, Boolean& done) in F:\workspace\_work\1\s\src\System.Windows.Forms\src\System\Windows\Forms\DataObject.cs:line 1502
   at System.Windows.Forms.DataObject.OleConverter.GetDataFromBoundOleDataObject(String format, Boolean& done) in F:\workspace\_work\1\s\src\System.Windows.Forms\src\System\Windows\Forms\DataObject.cs:line 1502
   at System.Windows.Forms.DataObject.OleConverter.GetData(String format, Boolean autoConvert) in F:\workspace\_work\1\s\src\System.Windows.Forms\src\System\Windows\Forms\DataObject.cs:line 1677
   at System.Windows.Forms.DataObject.GetData(String format, Boolean autoConvert) in F:\workspace\_work\1\s\src\System.Windows.Forms\src\System\Windows\Forms\DataObject.cs:line 174
   at System.Windows.Forms.DataObject.GetData(String format) in F:\workspace\_work\1\s\src\System.Windows.Forms\src\System\Windows\Forms\DataObject.cs:line 184
   at System.Windows.Forms.Clipboard.GetData(String format) in F:\workspace\_work\1\s\src\System.Windows.Forms\src\System\Windows\Forms\Clipboard.cs:line 322
   at System.Windows.Forms.Tests.ClipboardTests.Clipboard_GetData_InvokeMultipleTimes_Success(String format) in F:\workspace\_work\1\s\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\ClipboardTests.cs:line 108
```

Related to #3115.

The following API allow to pass `null`, `string.Empty` or whitespace that all are invalid data formats:
https://github.com/dotnet/winforms/blob/8aeaa419c478dad316edc7ba4103c8abc2bba40f/src/System.Windows.Forms/src/System/Windows/Forms/Clipboard.cs#L317-L326
https://github.com/dotnet/winforms/blob/8aeaa419c478dad316edc7ba4103c8abc2bba40f/src/System.Windows.Forms/src/System/Windows/Forms/Clipboard.cs#L317-L326

**Expected behavior:**

These API must not result in NRE and gracefully handle invalid input. We could throw but this will be breaking.
Instead we should `return null`/`return` respectively.

**Comment by weltkante** [comment]
If you're going this way `GetDataPresent` should also make sure it doesn't throw and return false instead.

**Comment by RussKie** [comment]
We're already doing this:
https://github.com/dotnet/winforms/blob/83bf61abd4fb55e5ed50d726148397df102f9b86/src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs#L2032-L2038

Unless, of course, there is some other path I'm overlooking

**Comment by weltkante** [comment]
Sorry, all good, didn't check the source, just saw that you only mentioned `GetData` :-)
