### ISSUE TITLE
AppActivate_ProcessId fails locally

### ISSUE THREAD

**Issue by hughbe** [dotnet/winforms#3252]
```
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:02.87]     Microsoft.VisualBasic.IntegrationTests.InteractionTests.AppActivate_ProcessId [FAIL]
  X Microsoft.VisualBasic.IntegrationTests.InteractionTests.AppActivate_ProcessId [584ms]
  Error Message:
   System.FormatException : Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
  Stack Trace:
     at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at Microsoft.VisualBasic._Interaction.AppActivateHelper(IntPtr hwndApp) in C:\Users\hughbe\Documents\GitHub\winforms\src\Microsoft.VisualBasic.Forms\src\Microsoft\VisualBasic\Interaction.vb:line 204
   at Microsoft.VisualBasic._Interaction.AppActivateByProcessId(Int32 ProcessId) in C:\Users\hughbe\Documents\GitHub\winforms\src\Microsoft.VisualBasic.Forms\src\Microsoft\VisualBasic\Interaction.vb:line 137
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.VisualBasic.Interaction.InvokeMethod(String methodName, Object[] args)
   at Microsoft.VisualBasic.Interaction.AppActivate(Int32 ProcessId)
   at Microsoft.VisualBasic.IntegrationTests.InteractionTests.AppActivate_ProcessId() in C:\Users\hughbe\Documents\GitHub\winforms\src\Microsoft.VisualBasic\tests\IntegrationTests\Microsoft.VisualBasic.IntegrationTests\InteractionTests.cs:line 21
```

I suspect this might be causing tests to hang, because I ran some tests locally and I got a visual basic popup saying "Message" that didn't go away once the tests finished

**Comment by RussKie** [comment]
It is plausible that while the tests were run some other app (or you, if you used the PC) stole the focus while tests were run, and that precluded the message box from being dismissed.
But it is not improbable that something else is broken too.

**Comment by weltkante** [comment]
Actually this also found a bug which isn't a test bug 😉 

> System.FormatException : Index (zero based) must be greater than or equal to zero and less than the size of the argument list.

Code is [here](https://github.com/dotnet/winforms/blob/a69ded30f06eff90ecbde7e2ec722b5d1b1f695c/src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Interaction.vb#L221):
```vb
Throw New ArgumentException(GetResourceString(SR.ProcessNotFound))
```

And localization is [here](https://github.com/dotnet/winforms/blob/706f8b978281baca67f0d685d4677ee8838b1ba3/src/Microsoft.VisualBasic.Forms/src/Resources/SR.resx#L134), expects an argument.

Thats of course not the cause of the test failure, but still worth noting.

**Comment by RussKie** [comment]
@weltkante thank you!

@cston looks like something got missing during the port. 

I can think of a fix like this:
```vb
diff --git a/src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Interaction.vb b/src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Interaction.vb
index 8c876dc4d..f9e970e7a 100644
--- a/src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Interaction.vb
+++ b/src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Interaction.vb
@@ -193,11 +193,11 @@ Namespace Microsoft.VisualBasic
             If IntPtr.op_Equality(WindowHandle, IntPtr.Zero) Then 'no match
                 Throw New ArgumentException(GetResourceString(SR.ProcessNotFound, Title))
             Else
-                AppActivateHelper(WindowHandle)
+                AppActivateHelper(WindowHandle, Title)
             End If
         End Sub
 
-        Private Sub AppActivateHelper(hwndApp As IntPtr)
+        Private Sub AppActivateHelper(hwndApp As IntPtr, Title As String)
             '  if no window with name (full or truncated) or task id, return an error
             '  if the window is not enabled or not visible, get the first window owned by it that is not enabled or not visible
             Dim hwndOwned As IntPtr
@@ -218,7 +218,7 @@ Namespace Microsoft.VisualBasic
 
                 '  if scan failed, return an error
                 If IntPtr.op_Equality(hwndOwned, IntPtr.Zero) Then
-                    Throw New ArgumentException(GetResourceString(SR.ProcessNotFound))
+                    Throw New ArgumentException(GetResourceString(SR.ProcessNotFound, Title))
                 End If
 
                 '  set active window to the owned one
```

What do you think?
