### ISSUE TITLE
Broken IDispatch.GetTypeInfo interop tests

### ISSUE THREAD

**Issue by weltkante** [dotnet/winforms#3305]
**.NET Core Version:**
Master with PR #3276 applied

**Have you experienced this same bug with .NET Framework?:**
unknown

**Problem description:**
The [tests](https://github.com/dotnet/winforms/blob/e32620ed185e3c15fa67bdb7fe93757a735d6edb/src/System.Windows.Forms.Primitives/tests/Interop/Oleaut32/ITypeInfoTests.cs) were flaky before, sometimes throwing `ComException(E_FAIL)`. The update of xunit.stafact now is properly hosting everything in an WinForms STA thread and they suddenly seem to fail "reliably" with this error here.
```
System.Windows.Forms.Primitives.Tests.Interop.Oleaut32.ITypeInfoTests.ITypeInfo_AddressOfMember_Invoke_Success
System.Runtime.InteropServices.InvalidComObjectException : COM object that has been separated from its underlying RCW cannot be used. The COM object was released while it was still in use on another thread.
   at System.StubHelpers.InterfaceMarshaler.ConvertToManaged(IntPtr ppUnk, IntPtr itfMT, IntPtr classMT, Int32 flags)
   at Interop.Oleaut32.IDispatch.GetTypeInfo(UInt32 iTInfo, UInt32 lcid, ITypeInfo& ppTInfo)
   at System.Windows.Forms.Primitives.Tests.Interop.Oleaut32.ITypeInfoTests.ITypeInfo_AddressOfMember_Invoke_Success() in D:\projects\winforms\src\System.Windows.Forms.Primitives\tests\Interop\Oleaut32\ITypeInfoTests.cs:line 23

System.Windows.Forms.Primitives.Tests.Interop.Oleaut32.ITypeInfoTests.ITypeInfo_CreateInstance_Invoke_Success
System.Runtime.InteropServices.InvalidComObjectException : COM object that has been separated from its underlying RCW cannot be used. The COM object was released while it was still in use on another thread.
   at System.StubHelpers.InterfaceMarshaler.ConvertToManaged(IntPtr ppUnk, IntPtr itfMT, IntPtr classMT, Int32 flags)
   at Interop.Oleaut32.IDispatch.GetTypeInfo(UInt32 iTInfo, UInt32 lcid, ITypeInfo& ppTInfo)
   at System.Windows.Forms.Primitives.Tests.Interop.Oleaut32.ITypeInfoTests.ITypeInfo_CreateInstance_Invoke_Success() in D:\projects\winforms\src\System.Windows.Forms.Primitives\tests\Interop\Oleaut32\ITypeInfoTests.cs:line 39

System.Windows.Forms.Primitives.Tests.Interop.Oleaut32.ITypeInfoTests.ITypeInfo_GetDllEntry_Invoke_Success
System.Runtime.InteropServices.InvalidComObjectException : COM object that has been separated from its underlying RCW cannot be used. The COM object was released while it was still in use on another thread.
   at System.StubHelpers.InterfaceMarshaler.ConvertToManaged(IntPtr ppUnk, IntPtr itfMT, IntPtr classMT, Int32 flags)
   at Interop.Oleaut32.IDispatch.GetTypeInfo(UInt32 iTInfo, UInt32 lcid, ITypeInfo& ppTInfo)
   at System.Windows.Forms.Primitives.Tests.Interop.Oleaut32.ITypeInfoTests.ITypeInfo_GetDllEntry_Invoke_Success() in D:\projects\winforms\src\System.Windows.Forms.Primitives\tests\Interop\Oleaut32\ITypeInfoTests.cs:line 81

System.Windows.Forms.Primitives.Tests.Interop.Oleaut32.ITypeInfoTests.ITypeInfo_GetFuncDesc_Invoke_Success
System.Runtime.InteropServices.InvalidComObjectException : COM object that has been separated from its underlying RCW cannot be used. The COM object was released while it was still in use on another thread.
   at System.StubHelpers.InterfaceMarshaler.ConvertToManaged(IntPtr ppUnk, IntPtr itfMT, IntPtr classMT, Int32 flags)
   at Interop.Oleaut32.IDispatch.GetTypeInfo(UInt32 iTInfo, UInt32 lcid, ITypeInfo& ppTInfo)
   at System.Windows.Forms.Primitives.Tests.Interop.Oleaut32.ITypeInfoTests.ITypeInfo_GetFuncDesc_Invoke_Success() in D:\projects\winforms\src\System.Windows.Forms.Primitives\tests\Interop\Oleaut32\ITypeInfoTests.cs:line 123

System.Windows.Forms.Primitives.Tests.Interop.Oleaut32.ITypeInfoTests.ITypeInfo_GetIDsOfNames_Invoke_Success
System.Runtime.InteropServices.InvalidComObjectException : COM object that has been separated from its underlying RCW cannot be used. The COM object was released while it was still in use on another thread.
   at System.StubHelpers.InterfaceMarshaler.ConvertToManaged(IntPtr ppUnk, IntPtr itfMT, IntPtr classMT, Int32 flags)
   at Interop.Oleaut32.IDispatch.GetTypeInfo(UInt32 iTInfo, UInt32 lcid, ITypeInfo& ppTInfo)
   at System.Windows.Forms.Primitives.Tests.Interop.Oleaut32.ITypeInfoTests.ITypeInfo_GetIDsOfNames_Invoke_Success() in D:\projects\winforms\src\System.Windows.Forms.Primitives\tests\Interop\Oleaut32\ITypeInfoTests.cs:line 159

System.Windows.Forms.Primitives.Tests.Interop.Oleaut32.ITypeInfoTests.ITypeInfo_GetMops_Invoke_Success
System.Runtime.InteropServices.InvalidComObjectException : COM object that has been separated from its underlying RCW cannot be used. The COM object was released while it was still in use on another thread.
   at System.StubHelpers.InterfaceMarshaler.ConvertToManaged(IntPtr ppUnk, IntPtr itfMT, IntPtr classMT, Int32 flags)
   at Interop.Oleaut32.IDispatch.GetTypeInfo(UInt32 iTInfo, UInt32 lcid, ITypeInfo& ppTInfo)
   at System.Windows.Forms.Primitives.Tests.Interop.Oleaut32.ITypeInfoTests.ITypeInfo_GetMops_Invoke_Success() in D:\projects\winforms\src\System.Windows.Forms.Primitives\tests\Interop\Oleaut32\ITypeInfoTests.cs:line 196

System.Windows.Forms.Primitives.Tests.Interop.Oleaut32.ITypeInfoTests.ITypeInfo_GetRefTypeInfo_Invoke_Success
System.Runtime.InteropServices.InvalidComObjectException : COM object that has been separated from its underlying RCW cannot be used. The COM object was released while it was still in use on another thread.
   at System.StubHelpers.InterfaceMarshaler.ConvertToManaged(IntPtr ppUnk, IntPtr itfMT, IntPtr classMT, Int32 flags)
   at Interop.Oleaut32.IDispatch.GetTypeInfo(UInt32 iTInfo, UInt32 lcid, ITypeInfo& ppTInfo)
   at System.Windows.Forms.Primitives.Tests.Interop.Oleaut32.ITypeInfoTests.ITypeInfo_GetRefTypeInfo_Invoke_Success() in D:\projects\winforms\src\System.Windows.Forms.Primitives\tests\Interop\Oleaut32\ITypeInfoTests.cs:line 236

System.Windows.Forms.Primitives.Tests.Interop.Oleaut32.ITypeInfoTests.ITypeInfo_Invoke_Invoke_Success
System.Runtime.InteropServices.InvalidComObjectException : COM object that has been separated from its underlying RCW cannot be used. The COM object was released while it was still in use on another thread.
   at System.StubHelpers.InterfaceMarshaler.ConvertToManaged(IntPtr ppUnk, IntPtr itfMT, IntPtr classMT, Int32 flags)
   at Interop.Oleaut32.IDispatch.GetTypeInfo(UInt32 iTInfo, UInt32 lcid, ITypeInfo& ppTInfo)
   at System.Windows.Forms.Primitives.Tests.Interop.Oleaut32.ITypeInfoTests.ITypeInfo_Invoke_Invoke_Success() in D:\projects\winforms\src\System.Windows.Forms.Primitives\tests\Interop\Oleaut32\ITypeInfoTests.cs:line 368

```

**Expected behavior:**
Tests pass or there is a reasonable explanation for the error

**Minimal repro:**
Run tests with PR #3276 applied

**Comment by weltkante** [comment]
I can reproduce these inside the VS debugger, but I don't know how to diagnose this without further assistance.

Things I checked:
* updated above tests to WinFormsFact and made sure they execute in STA
* made sure WinForms was not calling any `Marshal.ReleaseComObject` or `Marshal.FinalReleaseComObject` APIs which in my experience can be common sources of this exception if the RCW is used after being released

What else can cause this exception? I have a dump taken from debugger [here](https://1drv.ms/u/s!AuW3VU_s-jxTgeZYHkWgExacPMzNfw?e=RPMiv2). If I can assist diagnosis in other ways feel free to make suggestions.

**Comment by weltkante** [comment]
I remembered that `ITypeInfo` can be finnicky and added `Marshal.ReleaseComObject(typeInfo);` to the end of each test, that _seems_ to work around the problem.

I still don't see how this can cause the exception though, is this something that could be a bug in coreclr and needs further investigation, or should we be working around by manually managing `ITypeInfo` RCW refcounts?

**Comment by hughbe** [comment]
I remember in https://github.com/dotnet/winforms/pull/2603 (https://github.com/dotnet/winforms/pull/2603#discussion_r368761076) we had some problems. Maybe they are realted?

**Comment by weltkante** [comment]
Right, this is probably related to the linked comment. It'll probably mean we have to do manual RCW reference management to avoid the problem of automatic release, I'll do the corresponding PR.

I still want the opinion of @AaronRobinsonMSFT on whether this may be a race condition/bug in the runtime that needs further inspection, or if we should ignore it and work around it.

**Comment by hughbe** [comment]
I also made this a while ago: https://github.com/hughbe/Interop-Repro

Run StressTest.ps1 from the root of the repo

**Comment by weltkante** [comment]
Having read through the whole linked thread it looks like this issue was exactly what happened before. The previous workaround was probably relying on xunit.stafact behavior, now that its updated the old workaround might no longer work. The correct workaround is to never cause the problematic situation, if you don't want to wind up individual processes for tests the easiest solution is manual RCW reference management.

Considering that this scenario already has been examined there's probably no desire to fix anything in classic COM interop. I'll be preparing the PR to do manual RCW reference management then, that should fix the issue reliably for the future.

**Comment by AaronRobinsonMSFT** [comment]
Sorry about missing this. @hughbe Yes, this issue is the same as https://github.com/dotnet/winforms/pull/2603#discussion_r368761076. This is a general problem with the XUnit framework and the STA for concurrent tests. @weltkante Your suggestion about manual `Release` seems reasonable to me.

**Comment by RussKie** [comment]
Thank you all 🚀

**Comment by weltkante** [comment]
Sorry, [missed one ITypeInfo](https://github.com/dotnet/winforms/pull/3276/commits/1235d10eca868cfad148cfeeb2625b735b9b6470) 😞  Want me to make another PR for that line or leave that for the nuget package update? Around 1 out of 10 runs pass locally so I missed it. Its definitely better than all tests failing constantly.

**Comment by RussKie** [comment]
Let's fix it :)
