### ISSUE TITLE
DataGridView.TopLeftHeaderCell throws ArgumentOutOfRangeException on Handle creation

### ISSUE THREAD

**Issue by hughbe** [dotnet/winforms#3378]
* .NET Core Version: 
Master

* Have you experienced this same bug with .NET Framework?: 
Yes

**Problem description:**
Consider the following code:
```


public static IEnumerable<object[]> MouseLeaveUnsharesRow_WithDataGridViewMouseDown_TestData()
{
    ButtonState expected = VisualStyleRenderer.IsSupported ? ButtonState.Pushed : ButtonState.Normal;
    yield return new object[] { true, -2, expected };
    yield return new object[] { true, -1, expected };
    yield return new object[] { true, 0, expected };
    yield return new object[] { true, 1, expected };
    yield return new object[] { false, -2, ButtonState.Normal };
    yield return new object[] { false, -1, ButtonState.Normal };
    yield return new object[] { false, 0, ButtonState.Normal };
    yield return new object[] { false, 1, ButtonState.Normal };
}

[WinFormsTheory]
[MemberData(nameof(MouseLeaveUnsharesRow_WithDataGridViewMouseDown_TestData))]
public void DataGridViewHeaderCell_MouseLeaveUnsharesRow_InvokeWithDataGridViewMouseDown_ReturnsExpected(bool enableHeadersVisualStyles, int rowIndex, ButtonState expectedButtonState)
{
    Application.EnableVisualStyles();

    using var cellTemplate = new SubDataGridViewHeaderCell();
    using var column = new DataGridViewColumn
    {
        CellTemplate = cellTemplate
    };
    using var control = new DataGridView
    {
        EnableHeadersVisualStyles = enableHeadersVisualStyles
    };
    control.Columns.Add(column);
    SubDataGridViewHeaderCell cell = (SubDataGridViewHeaderCell)control.Rows[0].Cells[0];
    cell.OnMouseDown(new DataGridViewCellMouseEventArgs(-1, -1, 0, 0, new MouseEventArgs(MouseButtons.Left, 0, 0, 0, 0)));
    Assert.Equal(enableHeadersVisualStyles && VisualStyleRenderer.IsSupported, cell.MouseLeaveUnsharesRow(rowIndex));
    Assert.Equal(expectedButtonState, cell.ButtonState);
    Assert.False(control.IsHandleCreated);
}
```
Get the error
```
A total of 1 test files matched the specified pattern.
The active test run was aborted. Reason: Test host process crashed : Unhandled Exception: System.Exception: Specified argument was out of the range of valid values.
Parameter name: rowIndex
   at System.Windows.Forms.DataGridViewCell.GetInheritedStyle(DataGridViewCellStyle inheritedCellStyle, Int32 rowIndex, Boolean includeColors)
   at System.Windows.Forms.DataGridViewCell.GetPreferredHeight(Int32 rowIndex, Int32 width)
   at System.Windows.Forms.DataGridView.AutoResizeColumnHeadersHeight(Boolean fixedRowHeadersWidth, Boolean fixedColumnsWidth)
   at System.Windows.Forms.DataGridView.OnGlobalAutoSize()
   at System.Windows.Forms.DataGridView.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.Tests.ControlTests.<>c.<.ctor>b__3_0(Object sender, ThreadExceptionEventArgs e) in C:\Users\hughbe\source\repos\ConsoleApp\Support\ControlTests.Data.cs:line 19
   at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t)
   at System.Windows.Forms.Control.WndProcException(Exception e)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Expected behavior:**
Shouldn't throw

**Minimal repro:**
See above

**Comment by kirsan31** [comment]
Is it related with https://github.com/dotnet/winforms/issues/1830?

**Comment by hughbe** [comment]
I don’t think it’s the same cause but I agree TopLeftHeaderCell is rather buggy

**Comment by RussKie** [comment]
Which test case is causing the crash? Is this a test bug or an implementation bug?

**Comment by hughbe** [comment]
The test is `DataGridViewHeaderCell_GetInheritedState_InvokeTopLeftHeaderCellWithHandle_ReturnsExpected`.
https://github.com/dotnet/winforms/blob/7eff6d2f762a5f47b6bd6f3432a5225753f055de/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewHeaderCellTests.cs#L2945-L2988

I think this is an implementation bug. The reason I consider this is because the `RowIndex` and `ColumnIndex` of `TopLeftHeaderCell` are both `-1`.
`DataGridViewCell.GetInheritedStyle` is not overriden in `DataGridViewHeaderCell`, which means that it will always throw
```cs
public virtual DataGridViewCellStyle GetInheritedStyle(DataGridViewCellStyle inheritedCellStyle, int rowIndex, bool includeColors)
{
    if (DataGridView == null)
    {
        throw new InvalidOperationException(SR.DataGridView_CellNeedsDataGridViewForInheritedStyle);
    }
    if (rowIndex < 0 || rowIndex >= DataGridView.Rows.Count)
    {
        throw new ArgumentOutOfRangeException(nameof(rowIndex));
    }
    if (ColumnIndex < 0)
    {
        throw new InvalidOperationException();
    }

....
}
```

The fix would be for `DataGridViewHeaderCell` to provide a default implementation of `GetInheritedStyle` that provides the `DataGridView` default cell style

I think the reasons why we haven't seen this problem before is because I don't think the problem occurs if you set the header cell *after* the handle is created, and also the exception may be silently caught (though I'd expect a popup)
