### ISSUE TITLE
Expected a proxy type, Microsoft.VisualStudio.WinForms.RemoteClient.Proxies.ComponentProxy

### ISSUE THREAD

**Issue by qwertybba** [dotnet/winforms#3523]
* .NET Core Version: 
3.1,5.0
* Have you experienced this same bug with .NET Framework?: 
No 

**Problem description:**

I recently port my application from net472 to core3.1(5.0) after get every thing done ,so I build the application and test it everything's works well.
but when I try to open DevExpress XtraReport in designer I get the error:
```
Expected a proxy type, Microsoft.VisualStudio.WinForms.RemoteClient.Proxies.ComponentProxy
at Microsoft.VisualStudio.WinForms.RemoteClient.Proxies.Extensions.ToComponentProxy(Object obj)
at Microsoft.VisualStudio.WinForms.RemoteClient.DesignerSession.InitializeRootComponent(CodeTypeDeclaration typeDeclaration, ResourceContentData[] resourceDocDataContent)
at Microsoft.VisualStudio.WinForms.RemoteClient.Loader.RemoteCodeDomDesignerLoader.PerformLoad(IDesignerSerializationManager manager)
at Microsoft.VisualStudio.Design.Serialization.CodeDom.VSCodeDomDesignerLoader.PerformLoad(IDesignerSerializationManager serializationManager)
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.VisualStudio.Design.Serialization.CodeDom.VSCodeDomDesignerLoader.PerformLoad(IDesignerSerializationManager serializationManager)
at System.ComponentModel.Design.Serialization.BasicDesignerLoader.BeginLoad(IDesignerLoaderHost host) 
```

**Expected behavior:**
open the report in designer 

**Minimal repro:**
I use Windows 10 x64 version 2004
VS 2019 Version 16.7.0 Preview 3.1
DevExpres 20.1.4
[Sdk style project  Core3.1,5.0.txt](https://github.com/dotnet/winforms/files/4847371/Sdk.style.project.Core3.1.5.0.txt)

**Comment by RussKie** [comment]
I appreciate you have spent the time to raise the issue, but issues with VS and VS Designer should be sent via VS Feedback channel (the icon in the top right hand side corner). The reason for this - the VS Feedback tool captures a lot of additional information (such as screenshots, memory dumps, stack traces, assembly versions, etc.) that can help us to investigate your issue and identify the cause.
