### ISSUE TITLE
`DeviceContextExtensions.CreateGraphics` results in `System.OutOfMemoryException`

### ISSUE THREAD

**Issue by RussKie** [dotnet/winforms#3630]
Observed in https://dev.azure.com/dnceng/public/_build/results?buildId=741547&view=results

**Problem description:**

```
    System.Windows.Forms.Tests.RadioButtonTests.RadioButton_OnMouseUp_InvokeMouseDown_CallsMouseUp(flatStyle: Flat, eventArgs: HandledMouseEventArgs { Button = Left, Clicks = 1, Delta = 4, Handled = False, Location = {X=2,Y=3}, ... }, expectedIsHandleCreated: True) [FAIL]
      System.OutOfMemoryException : Out of memory.
      Stack Trace:
           at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
           at System.Drawing.Graphics.FromHdcInternal(IntPtr hdc)
        /_/src/System.Windows.Forms.Primitives/src/System/Windows/Forms/DeviceContextExtensions.cs(110,0): at System.Windows.Forms.DeviceContextExtensions.CreateGraphics(HDC hdc)
        /_/src/System.Windows.Forms/src/System/Windows/Forms/Internal/GdiCache.ScreenGraphicsScope.cs(23,0): at System.Windows.Forms.GdiCache.ScreenGraphicsScope..ctor(ScreenDcScope& scope)
        /_/src/System.Windows.Forms/src/System/Windows/Forms/Internal/GdiCache.cs(45,0): at System.Windows.Forms.GdiCache.GetScreenDCGraphics()
        /_/src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/ButtonBaseAdapter.cs(1364,0): at System.Windows.Forms.ButtonInternal.ButtonBaseAdapter.LayoutOptions.GetTextSize(Size proposedSize)
        /_/src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/ButtonBaseAdapter.cs(1217,0): at System.Windows.Forms.ButtonInternal.ButtonBaseAdapter.LayoutOptions.LayoutTextAndImage(LayoutData layout)
        /_/src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/ButtonBaseAdapter.cs(990,0): at System.Windows.Forms.ButtonInternal.ButtonBaseAdapter.LayoutOptions.Layout()
        /_/src/System.Windows.Forms/src/System/Windows/Forms/RadioButton.cs(342,0): at System.Windows.Forms.RadioButton.get_DownChangeRectangle()
        /_/src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs(913,0): at System.Windows.Forms.ButtonBase.OnMouseDown(MouseEventArgs mevent)
        /_/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RadioButtonTests.cs(1474,0): at System.Windows.Forms.Tests.RadioButtonTests.SubRadioButton.OnMouseDown(MouseEventArgs eventargs)
        /_/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RadioButtonTests.cs(984,0): at System.Windows.Forms.Tests.RadioButtonTests.RadioButton_OnMouseUp_InvokeMouseDown_CallsMouseUp(FlatStyle flatStyle, MouseEventArgs eventArgs, Boolean expectedIsHandleCreated)
```

**Comment by RussKie** [comment]
Also observed in https://dev.azure.com/dnceng/public/_build/results?buildId=740879&view=results

```
    System.Windows.Forms.Tests.ProfessionalColorTableTests.ProfessionalColorTable_Properties_Get_ReturnsExpected(factory: Func`2 { Method = System.Drawing.Color <Properties_TestData>b__1_9(System.Windows.Forms.ProfessionalColorTable), Target = <>c { } }) [FAIL]
      System.OutOfMemoryException : Out of memory.
      Stack Trace:
           at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
           at System.Drawing.Graphics.FromHdcInternal(IntPtr hdc)
        /_/src/System.Windows.Forms.Primitives/src/System/Windows/Forms/DeviceContextExtensions.cs(110,0): at System.Windows.Forms.DeviceContextExtensions.CreateGraphics(HDC hdc)
        /_/src/System.Windows.Forms/src/System/Windows/Forms/Internal/GdiCache.ScreenGraphicsScope.cs(23,0): at System.Windows.Forms.GdiCache.ScreenGraphicsScope..ctor(ScreenDcScope& scope)
        /_/src/System.Windows.Forms/src/System/Windows/Forms/Internal/GdiCache.cs(45,0): at System.Windows.Forms.GdiCache.GetScreenDCGraphics()
        /_/src/System.Windows.Forms/src/System/Windows/Forms/ProfessionalColorTable.cs(341,0): at System.Windows.Forms.ProfessionalColorTable.InitCommonColors(Dictionary`2& rgbTable)
        /_/src/System.Windows.Forms/src/System/Windows/Forms/ProfessionalColorTable.cs(368,0): at System.Windows.Forms.ProfessionalColorTable.InitSystemColors(Dictionary`2& rgbTable)
        /_/src/System.Windows.Forms/src/System/Windows/Forms/ProfessionalColorTable.cs(61,0): at System.Windows.Forms.ProfessionalColorTable.get_ColorTable()
        /_/src/System.Windows.Forms/src/System/Windows/Forms/ProfessionalColorTable.cs(99,0): at System.Windows.Forms.ProfessionalColorTable.FromKnownColor(KnownColors color)
        /_/src/System.Windows.Forms/src/System/Windows/Forms/ProfessionalColorTable.cs(154,0): at System.Windows.Forms.ProfessionalColorTable.get_ButtonPressedGradientMiddle()
        /_/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ProfessionalColorTableTests.cs(36,0): at System.Windows.Forms.Tests.ProfessionalColorTableTests.<>c.<Properties_TestData>b__1_9(ProfessionalColorTable t)
        /_/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ProfessionalColorTableTests.cs(90,0): at System.Windows.Forms.Tests.ProfessionalColorTableTests.ProfessionalColorTable_Properties_Get_ReturnsExpected(Func`2 factory)
```

**Comment by JeremyKuhne** [comment]
I'll look into it

**Comment by RussKie** [comment]
Another occurrence in https://dev.azure.com/dnceng/internal/_build/results?buildId=759127&view=artifacts&type=publishedArtifacts

**Comment by RussKie** [comment]
...and another https://dev.azure.com/dnceng/public/_build/results?buildId=759324&view=artifacts&type=publishedArtifacts

**Comment by JeremyKuhne** [comment]
Please copy in call stacks when this happens- the HDC isn't correct.

**Comment by merriemcgaw** [comment]
This hasn't come up in a while. Closing and we can reopen if it repros later.
