### ISSUE TITLE
TextBox.BackColor = Color.Transpartent

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/winforms#3834]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/482296/textboxbackcolor-colortranspartent.html)._

---
<p>It would even be possible if in the future a text field in VB.WinForm can be assigned a transparent value (Back Color). In contrast, the whole thing would be solved with the variant TextBox.BackColor = Color.FromArgb (0,0,0,0). Unfortunately I can only use fixed colors for my projects &#128549;.</p>

---
#### Jane Wu [MSFT] on 3/8/2019, 00:24 PM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.&nbsp;We'll provide an update once the issue has been triaged by the product team.</p>
#### Dean Goddard on 8/29/2019, 09:19 AM: 

WinForms apps continue to get slammed by the current business community as being old and tied.  I agree that any visual or structural improvement to WinForm controls to behave or act like Web controls is a good thing.
#### Feedback Bot on 9/4/2020, 06:19 AM: 

<p>Your suggestion has been queued up for prioritization. Feature suggestions are prioritized based on the value to our broader developer community and the product roadmap. We may not be able to pursue this one immediately, but we will continue to monitor it for community input</p>

**Comment by Olina-Zhang** [comment]
This issue is from SuggestionTicket, and Merrie suggests file an issue in here, will prioritize it.

Now, the framework and core have the same result when setting TextBox BackColor as Transparent, running app gets an exception:
System.ArgumentException
  HResult=0x80070057
  Message=Control does not support transparent background colors.
  Source=System.Windows.Forms
  StackTrace:
   at System.Windows.Forms.Control.set_BackColor(Color value)
   at System.Windows.Forms.TextBoxBase.set_BackColor(Color value)
   at WindowsFormsApp1.Form1.Form1_Load(Object sender, EventArgs e) in C:\Users\v-olzhan\source\repos\WindowsFormsApp1\WindowsFormsApp1\Form1.cs:line 23
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by merriemcgaw** [comment]
Closing for lack of activity since creation.
