### ISSUE TITLE
Flaky test: `ImageCollection_Item_Get32bppColorDepth_Success`

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/winforms#3898]
System.Windows.Forms.Tests.ImageCollectionTests.ImageCollection_Item_Get32bppColorDepth_Success is failing intermittently in the CI. It has failed several times over the last month with the exact same error:

```
Error message
Assert.Equal() Failure\r\nExpected: Color [A=255, R=255, G=0, B=0]\r\nActual:   Color [A=255, R=0, G=0, B=0]

Stack trace
   at System.Windows.Forms.Tests.ImageCollectionTests.ImageCollection_Item_Get32bppColorDepth_Success() in F:\workspace\_work\1\s\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\ImageList.ImageCollectionTests.cs:line 215
```

``` C#
            using Bitmap resultImage24bppRgbCustom = Assert.IsType<Bitmap>(collection[5]);
            Assert.NotSame(image24bppRgbCustom, resultImage24bppRgbCustom);
            Assert.Equal(new Size(16, 16), resultImage24bppRgbCustom.Size);
            Assert.Equal(PixelFormat.Format32bppArgb, resultImage24bppRgbCustom.PixelFormat);
            Assert.Equal(Color.FromArgb(0xFF, 0xFF, 0x00, 0x00), resultImage24bppRgbCustom.GetPixel(0, 0));   // <-- Failing line
            Assert.Equal(Color.FromArgb(0xFF, 50, 75, 100), resultImage24bppRgbCustom.GetPixel(1, 0));
```

**Comment by RussKie** [comment]
https://dev.azure.com/dnceng/internal/_build/results?buildId=816990&view=results Release/x86

**Comment by RussKie** [comment]
Reopening since the instability hasn't been resolved.

[Another build](https://dev.azure.com/dnceng/public/_build/results?buildId=852489&view=results) failed in Debug/x64 with:
```
    System.Windows.Forms.Tests.ImageCollectionTests.ImageCollection_Item_Get32bppColorDepth_Success(pixelFormat: Format24bppRgb, pixel00Color: Color [Red], pixel10Color: Color [A=200, R=50, G=75, B=100]) [FAIL]
      Assert.Equal() Failure
      Expected: Color [A=255, R=255, G=0, B=0]
      Actual:   Color [A=255, R=0, G=0, B=0]
      Stack Trace:
        F:\workspace\_work\1\s\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\ImageList.ImageCollectionTests.cs(192,0): at System.Windows.Forms.Tests.ImageCollectionTests.ImageCollection_Item_Get32bppColorDepth_Success(PixelFormat pixelFormat, Color pixel00Color, Color pixel10Color)
    System.Windows.Forms.Tests.ImageCollectionTests.ImageCollection_Item_Get32bppColorDepth_Success(pixelFormat: Format24bppRgb, pixel00Color: Color [Red], pixel10Color: Color [A=200, R=50, G=75, B=100]) [FAIL]
      Assert.Equal() Failure
      Expected: Color [A=255, R=255, G=0, B=0]
      Actual:   Color [A=255, R=0, G=0, B=0]
      Stack Trace:
        F:\workspace\_work\1\s\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\ImageList.ImageCollectionTests.cs(192,0): at System.Windows.Forms.Tests.ImageCollectionTests.ImageCollection_Item_Get32bppColorDepth_Success(PixelFormat pixelFormat, Color pixel00Color, Color pixel10Color)
    System.Windows.Forms.Tests.ImageCollectionTests.ImageCollection_Item_Get32bppColorDepth_Success(pixelFormat: Format24bppRgb, pixel00Color: Color [Red], pixel10Color: Color [A=200, R=50, G=75, B=100]) [FAIL]
      Assert.Equal() Failure
      Expected: Color [A=255, R=255, G=0, B=0]
      Actual:   Color [A=255, R=0, G=0, B=0]
      Stack Trace:
        F:\workspace\_work\1\s\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\ImageList.ImageCollectionTests.cs(192,0): at System.Windows.Forms.Tests.ImageCollectionTests.ImageCollection_Item_Get32bppColorDepth_Success(PixelFormat pixelFormat, Color pixel00Color, Color pixel10Color)
    System.Windows.Forms.Tests.ImageCollectionTests.ImageCollection_Item_Get32bppColorDepth_Success(pixelFormat: Format32bppArgb, pixel00Color: Color [Empty], pixel10Color: Color [Empty]) [FAIL]
      Assert.Equal() Failure
      Expected: Color [A=0, R=0, G=0, B=0]
      Actual:   Color [A=255, R=0, G=0, B=0]
      Stack Trace:
        F:\workspace\_work\1\s\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\ImageList.ImageCollectionTests.cs(192,0): at System.Windows.Forms.Tests.ImageCollectionTests.ImageCollection_Item_Get32bppColorDepth_Success(PixelFormat pixelFormat, Color pixel00Color, Color pixel10Color)
    System.Windows.Forms.Tests.ImageCollectionTests.ImageCollection_Item_Get32bppColorDepth_Success(pixelFormat: Format24bppRgb, pixel00Color: Color [Red], pixel10Color: Color [A=200, R=50, G=75, B=100]) [FAIL]
      Assert.Equal() Failure
      Expected: Color [A=255, R=255, G=0, B=0]
      Actual:   Color [A=255, R=0, G=0, B=0]
      Stack Trace:
        F:\workspace\_work\1\s\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\ImageList.ImageCollectionTests.cs(192,0): at System.Windows.Forms.Tests.ImageCollectionTests.ImageCollection_Item_Get32bppColorDepth_Success(PixelFormat pixelFormat, Color pixel00Color, Color pixel10Color)
    System.Windows.Forms.Tests.ImageCollectionTests.ImageCollection_Item_Get32bppColorDepth_Success(pixelFormat: Format32bppPArgb, pixel00Color: Color [Empty], pixel10Color: Color [Empty]) [FAIL]
      Assert.Equal() Failure
      Expected: Color [A=0, R=0, G=0, B=0]
      Actual:   Color [A=255, R=0, G=0, B=0]
      Stack Trace:
        F:\workspace\_work\1\s\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\ImageList.ImageCollectionTests.cs(192,0): at System.Windows.Forms.Tests.ImageCollectionTests.ImageCollection_Item_Get32bppColorDepth_Success(PixelFormat pixelFormat, Color pixel00Color, Color pixel10Color)
    System.Windows.Forms.Tests.ImageCollectionTests.ImageCollection_Item_Get32bppColorDepth_Success(pixelFormat: Format24bppRgb, pixel00Color: Color [Red], pixel10Color: Color [A=200, R=50, G=75, B=100]) [FAIL]
      Assert.Equal() Failure
      Expected: Color [A=255, R=255, G=0, B=0]
      Actual:   Color [A=255, R=0, G=0, B=0]
      Stack Trace:
        F:\workspace\_work\1\s\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\ImageList.ImageCollectionTests.cs(192,0): at System.Windows.Forms.Tests.ImageCollectionTests.ImageCollection_Item_Get32bppColorDepth_Success(PixelFormat pixelFormat, Color pixel00Color, Color pixel10Color)
```

**Comment by weltkante** [comment]
See [note](https://github.com/dotnet/winforms/pull/4092#discussion_r504457630) in one of the PRs, this test is not testing v6 common controls, so its value is questionable. Don't know why it is flaky though, couldn't reproduce the failures yet.

**Comment by RussKie** [comment]
Seems to have resurfaced again in Release/x86
* https://dev.azure.com/dnceng/public/_build/results?buildId=876543&view=results
* https://dev.azure.com/dnceng/public/_build/results?buildId=875377&view=results

**Comment by RussKie** [comment]
In x86 the tests are failing with visual styles enabled:
https://dev.azure.com/dnceng/public/_build/results?buildId=882474&view=artifacts&type=publishedArtifacts

```
    System.Windows.Forms.Tests.ImageCollectionTests.ImageCollection_Item_Get32bppColorDepth_Success(pixelFormat: Format24bppRgb, pixel00Color: Color [Red], pixel10Color: Color [A=200, R=50, G=75, B=100]) [FAIL]
      Assert.Equal() Failure
      Expected: Color [A=255, R=50, G=75, B=100]
      Actual:   Color [A=255, R=49, G=74, B=99]
      Stack Trace:
        F:\workspace\_work\1\s\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\ImageList.ImageCollectionTests.cs(194,0): at System.Windows.Forms.Tests.ImageCollectionTests.ImageCollection_Item_Get32bppColorDepth_Success(PixelFormat pixelFormat, Color pixel00Color, Color pixel10Color)
    System.Windows.Forms.Tests.ImageCollectionTests.ImageCollection_Item_Get32bppColorDepth_Success(pixelFormat: Format24bppRgb, pixel00Color: Color [Red], pixel10Color: Color [A=200, R=50, G=75, B=100]) [FAIL]
      Assert.Equal() Failure
      Expected: Color [A=255, R=50, G=75, B=100]
      Actual:   Color [A=255, R=49, G=74, B=99]
      Stack Trace:
        F:\workspace\_work\1\s\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\ImageList.ImageCollectionTests.cs(194,0): at System.Windows.Forms.Tests.ImageCollectionTests.ImageCollection_Item_Get32bppColorDepth_Success(PixelFormat pixelFormat, Color pixel00Color, Color pixel10Color)
    System.Windows.Forms.Tests.ImageCollectionTests.ImageCollection_Item_Get32bppColorDepth_Success(pixelFormat: Format24bppRgb, pixel00Color: Color [Red], pixel10Color: Color [A=200, R=50, G=75, B=100]) [FAIL]
      Assert.Equal() Failure
      Expected: Color [A=255, R=50, G=75, B=100]
      Actual:   Color [A=255, R=49, G=74, B=99]
      Stack Trace:
        F:\workspace\_work\1\s\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\ImageList.ImageCollectionTests.cs(194,0): at System.Windows.Forms.Tests.ImageCollectionTests.ImageCollection_Item_Get32bppColorDepth_Success(PixelFormat pixelFormat, Color pixel00Color, Color pixel10Color)
    System.Windows.Forms.Tests.ImageCollectionTests.ImageCollection_Item_Get32bppColorDepth_Success(pixelFormat: Format24bppRgb, pixel00Color: Color [Red], pixel10Color: Color [A=200, R=50, G=75, B=100]) [FAIL]
      Assert.Equal() Failure
      Expected: Color [A=255, R=50, G=75, B=100]
      Actual:   Color [A=255, R=49, G=74, B=99]
      Stack Trace:
        F:\workspace\_work\1\s\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\ImageList.ImageCollectionTests.cs(194,0): at System.Windows.Forms.Tests.ImageCollectionTests.ImageCollection_Item_Get32bppColorDepth_Success(PixelFormat pixelFormat, Color pixel00Color, Color pixel10Color)
    System.Windows.Forms.Tests.ImageCollectionTests.ImageCollection_Item_Get32bppColorDepth_Success(pixelFormat: Format24bppRgb, pixel00Color: Color [Red], pixel10Color: Color [A=200, R=50, G=75, B=100]) [FAIL]
      Assert.Equal() Failure
      Expected: Color [A=255, R=50, G=75, B=100]
      Actual:   Color [A=255, R=49, G=74, B=99]
      Stack Trace:
        F:\workspace\_work\1\s\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\ImageList.ImageCollectionTests.cs(194,0): at System.Windows.Forms.Tests.ImageCollectionTests.ImageCollection_Item_Get32bppColorDepth_Success(PixelFormat pixelFormat, Color pixel00Color, Color pixel10Color)
```

**Comment by weltkante** [comment]
Yes, like I said before in the PR comment, there is more going on than just v5 vs. v6 common controls. I've been writing some tests against ImageList using GDI HBITMAP APIs and it seemed to roundtrip colors and transparency properly. Since WinForms puts the HBITMAP through GDI+ instead of accessing the image directly I can only guess something is going wrong in the GDI+ side. I didn't have the time yet to make more experiments to see where exactly things go wrong.

**Comment by RussKie** [comment]
Will re-open if the issue re-surfaces
