### ISSUE TITLE
ListView.Items.Add throws ExecutionEngineException with custom ListViewItemSorter

### ISSUE THREAD

**Issue by dhrdlicka** [dotnet/winforms#4264]
* .NET Core Version: 5.0.100

* Have you experienced this same bug with .NET Framework?: No

**Problem description:**

ListView.Items.Add throws ExecutionEngineException upon reaching a certain number of items in the ListView when ListView.ListViewItemSorter is used to sort the items.

The exact number might vary on the specific use case and machine setup. The repro linked below crashes on my machine after ~130 added items, although I have observed numbers as low as 16 in a project of mine.

This didn't happen in .NET Core 3.1.

Stack trace:
```
Process terminated. A callback was made on a garbage collected delegate of type 'System.Windows.Forms.Primitives!System.Windows.Forms.NativeMethods+ListViewCompareCallback::Invoke'.
Repeat 2 times:
--------------------------------
   at Interop+User32.CallWindowProcW(IntPtr, IntPtr, WM, IntPtr, IntPtr)
--------------------------------
   at System.Windows.Forms.NativeWindow.DefWndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.ListView.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control+ControlNativeWindow.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr, WM, IntPtr, IntPtr)
   at Interop+User32.SendMessageW(IntPtr, WM, IntPtr, IntPtr)
   at Interop+User32.SendMessageW(IntPtr, WM, IntPtr, IntPtr)
   at System.Windows.Forms.ListView.Sort()
   at System.Windows.Forms.ListView.InsertItems(Int32, System.Windows.Forms.ListViewItem[], Boolean)
   at System.Windows.Forms.ListView+ListViewNativeItemCollection.Add(System.Windows.Forms.ListViewItem)
   at System.Windows.Forms.ListView+ListViewItemCollection.Add(System.Windows.Forms.ListViewItem)
   at ListViewRepro.MainForm.AddFruit()
   at ListViewRepro.MainForm.MainForm_Shown(System.Object, System.EventArgs)
   at System.Windows.Forms.Form.OnShown(System.EventArgs)
   at System.Windows.Forms.Form.CallShownEvent()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.ScrollableControl.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Form.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control+ControlNativeWindow.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr, WM, IntPtr, IntPtr)
   at Interop+User32.DispatchMessageW(MSG ByRef)
   at Interop+User32.DispatchMessageW(MSG ByRef)
   at System.Windows.Forms.Application+ComponentManager.Interop.Mso.IMsoComponentManager.FPushMessageLoop(UIntPtr, msoloop, Void*)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(msoloop, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(msoloop, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application.Run(System.Windows.Forms.Form)
   at ListViewRepro.Program.Main()
```

**Expected behavior:**
ListView.Add does not throw ExecutionEngineException.

**Minimal repro:**
https://github.com/dhrdlicka/ListViewRepro (The LVIS assignment is commented out in the MainForm constructor as the same project serves as repro on another issue as well)

**Comment by RussKie** [comment]
Thank you for the repro project, but I can't seem to repro the issue having a clean install of .NET 5.0 (i.e. deleted C:\Program Files\dotnet folder and installed [.NET 5.0 afresh](https://dotnet.microsoft.com/download/dotnet/5.0)). I have also increased all `for` loops to 500 iterations.

Can you please tell more about your setup and hardware you're observing the issue on?

**Comment by RussKie** [comment]
@JeremyKuhne @weltkante do you think we're failing to keep the `callback` alive, i.e. `GC.KeepAlive(callback)` on line:5532?
https://github.com/dotnet/winforms/blob/00b77530a64b0e0e1bfcc57e523f46c58e7c6843/src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs#L5527-L5532

**Comment by RussKie** [comment]
@Olina-Zhang can you see if you can repro this on .NET 5.0 RTM and the latest 6.0?

**Comment by kpreisser** [comment]
I think failing to keep the delegate instance alive until after the `SendMessageW` call is probably the issue. You should be able to reproduce it more easily by setting `ListView.ListViewItemSorter`to a comparer that contains e.g.  `GC.Collect()` and `Thread.Sleep(10)`, in order to induce garbage collection and delay execution a bit, for example:
```cs
    class ListViewItemComparer : Comparer<ListViewItem>
    {
        public override int Compare(ListViewItem x, ListViewItem y)
        {
            // Induce a GC and wait a bit so that unreachable objects should be collected before we return.
            GC.Collect();
            Thread.Sleep(10);
            return 0;
        }
    }
```

**Comment by weltkante** [comment]
Yes in the snippet you show, the `callback` managed delegate looks eligible for garbage collection, so if the comparer does complex work this may cause it to be collected prematurely while native code still has access to the delegate pointer. You are responsible for keeping the managed delegate alive as long as the native pointer is in use.

**Comment by dhrdlicka** [comment]
> Can you please tell more about your setup and hardware you're observing the issue on?

Intel Core i3-4160 @ 3.60 GHz, 16 GB of RAM, Windows 10 x64 build 20262.

**Comment by Olina-Zhang** [comment]
@RussKie, I cannot repro this exception issue using that sample app in .Net 5.0 RTM and the latest 6.0 build: added listview items can be sorted. And the results for both have a little difference: In 5.0, repro the intermittent missing icons, and in the latest 6.0, cannot.

**Comment by RussKie** [comment]
Thank you @kpreisser, but even with your suggestion I'm unable to repro the crash on two different machines I have at my disposal (.NET 5.0 and 6.0, debug and release). It is a good way to lock a machine up for 5+ minutes though, haha.
Were you able to repro the crash yourself?


@dhrdlicka have you observed the issue on any other workstation other than yours?
Is there anything else happening on the workstation when the issue manifests itself? 

We can certainly add `GC.KeepAlive(callback)` to the master branch, but without a repro it may be hard to get it past the servicing committee.

**Comment by kpreisser** [comment]
Hi @RussKie,
yes, I'm able to reliably (100% of the time) reproduce the crash with the comparer code sample, running on .NET SDK 5.0.100 (x64) on Windows 10 Version 2004, when running the application compiled for Debug or Release in Visual Studio with and without a debugger. I haven't tried yet with a nightly build.

<details>
<summary><code>dotnet --info</code></summary>
<br>
.NET SDK (gemäß "global.json"):
 Version:   5.0.100
 Commit:    5044b93829

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  5.0.100-rc.2.20479.15 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>

Here's a comlpete code sample  with which I can reproduce the issue:
**`Program.cs`:**
```c#
using System;
using System.Collections.Generic;
using System.Threading;
using System.Windows.Forms;

namespace repro_listview
{
    static class Program
    {
        [STAThread]
        static void Main()
        {
            Application.SetHighDpiMode(HighDpiMode.SystemAware);
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);

            var f = new Form();
            var listView = new ListView();

            f.Controls.Add(listView);

            listView.Items.Add("A");
            listView.Items.Add("Z");
            listView.Items.Add("X");
            listView.ListViewItemSorter = new TestComparer();

            Application.Run(f);
        }

        class TestComparer : Comparer<ListViewItem>
        {
            public override int Compare(ListViewItem x, ListViewItem y)
            {
                GC.Collect();
                Thread.Sleep(10);
                return 0;
            }
        }
    }
}
```

**`App.csproj`**:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <RootNamespace>winf_listview</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

</Project>
```

![grafik](https://user-images.githubusercontent.com/13289184/100060833-6baf7900-2e2d-11eb-88dc-62a7fa455fb7.png)

The `ExecutionEngineException` above doesn't show any details in my case, but when I run the application without a debugger, an error is also logged to the EventLog (.NET Runtime):
```
Application: winf-listview.exe
CoreCLR Version: 5.0.20.51904
.NET Version: 5.0.0
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: A callback was made on a garbage collected delegate of type 'System.Windows.Forms.Primitives!System.Windows.Forms.NativeMethods+ListViewCompareCallback::Invoke'.
Stack:
   at Interop+User32.CallWindowProcW(IntPtr, IntPtr, WM, IntPtr, IntPtr)
   at Interop+User32.CallWindowProcW(IntPtr, IntPtr, WM, IntPtr, IntPtr)
   at System.Windows.Forms.NativeWindow.DefWndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control.DefWndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.ListView.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control+ControlNativeWindow.OnMessage(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control+ControlNativeWindow.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr, WM, IntPtr, IntPtr)
   at Interop+User32.SendMessageW(IHandle, WM, IntPtr, IntPtr)
   at System.Windows.Forms.ListView.Sort()
   at System.Windows.Forms.ListView.OnHandleCreated(System.EventArgs)
   at System.Windows.Forms.Control.WmCreate(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.ListView.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control+ControlNativeWindow.OnMessage(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control+ControlNativeWindow.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr, WM, IntPtr, IntPtr)
   at Interop+User32.CreateWindowExW(WS_EX, Char*, System.String, WS, Int32, Int32, Int32, Int32, IntPtr, IntPtr, IntPtr, System.Object)
   at Interop+User32.CreateWindowExW(WS_EX, Char*, System.String, WS, Int32, Int32, Int32, Int32, IntPtr, IntPtr, IntPtr, System.Object)
   at Interop+User32.CreateWindowExW(WS_EX, System.String, System.String, WS, Int32, Int32, Int32, Int32, IntPtr, IntPtr, IntPtr, System.Object)
   at System.Windows.Forms.NativeWindow.CreateHandle(System.Windows.Forms.CreateParams)
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.ListView.CreateHandle()
   at System.Windows.Forms.Control.CreateControl(Boolean)
   at System.Windows.Forms.Control.CreateControl(Boolean)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.ScrollableControl.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.ContainerControl.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Form.WmShowWindow(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Form.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control+ControlNativeWindow.OnMessage(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control+ControlNativeWindow.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr, WM, IntPtr, IntPtr)
   at Interop+User32.ShowWindow(IntPtr, SW)
   at Interop+User32.ShowWindow(IntPtr, SW)
   at System.Windows.Forms.Control.SetVisibleCore(Boolean)
   at System.Windows.Forms.Form.SetVisibleCore(Boolean)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(msoloop, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(msoloop, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application.Run(System.Windows.Forms.Form)
   at repro_listview.Program.Main()

```

**Comment by RussKie** [comment]
Thank you! I'll give it a go tomorrow, hopefully I'll get it to fail.

**Comment by Olina-Zhang** [comment]
Verified this issue in .Net SDK 5.0.101 build, this issue is fixed, app with listViewItemSorter can be ran successfully.
![image](https://user-images.githubusercontent.com/26474449/100834017-1961fe00-34a6-11eb-8bc9-498827075600.png)

**Comment by RussKie** [comment]
@Olina-Zhang can you please test https://github.com/dotnet/winforms/issues/4306 and https://github.com/dotnet/winforms/issues/4301 as well? They look related.
Thank you

**Comment by Olina-Zhang** [comment]
@RussKie  these related 2 issues: #4306, #4301 cannot repro in .Net SDK 5.0.101-servicing.20601.5 build. Have updated test results in those issues.
