### ISSUE TITLE
ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObject ctor ArgumentNullException

### ISSUE THREAD

**Issue by StevenBonePgh** [dotnet/winforms#4742]
* .NET Core Version: 
5.0.4

* Have you experienced this same bug with .NET Framework?: 
This does not happen with .NET Framework 4.8. This also does not happen with NetCoreApp3.1.

This appears to be a regression due to #3224, though I can't seem to reconcile the call stack with the code I see in this repository. This is exhibited in a library called `ObjectListView`. This control inherits from ListView, and overrides WndProc. After receiving a WM_LBUTTONDOWN, it calls to base.WndProc. In all cases, when clicking on the first item in Detail view, an ArgumentNullException for parameter 'owningItem' is raised with this stack trace:
```
   at System.Windows.Forms.ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObject..ctor(ListViewSubItem owningSubItem, ListViewItem owningItem)
   at System.Windows.Forms.ListView.ListViewAccessibleObject.HitTest(Int32 x, Int32 y)
   at System.Windows.Forms.ListView.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at MyType.WndProc(Message& m) in 
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```
This is raised when in Details view, only when clicking on a listviewitem in the first column, no matter if it is in Virtual Mode or not. This causes the application to crash.

**Expected behavior:**
Please do not throw unhandled exception during a hit test.

**Minimal repro:**
See https://github.com/StevenBonePgh/ListViewSubItemAccessibleObjectExceptionDemo

**Comment by Jenna-Zheng** [comment]
Verified this issue with .NET 5.0.6(SDK 5.0.203), it is fixed that do not throw unhandled exception during a hit test.
![Table](https://user-images.githubusercontent.com/64949616/115526938-218ad080-a2c3-11eb-94b8-e1bbabf9fa50.gif)

**Comment by Zheng-Li01** [comment]
Verified the issue ..NET 6.0.100-preview.4.21221.10-win-x64 that the issue has been fixed that the project can run successfully with no exception.
