### ISSUE TITLE
Setting do not work on NEW VB .Net 5 Winforms application

### ISSUE THREAD

**Issue by paul1956** [dotnet/winforms#4957]
* .NET Core Version:  What I have installed is below
```
Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.0-preview.2.21154.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**
Create a new VB WinForm App, that will read settings, add settings, run app and application will crash as below.

![image](https://user-images.githubusercontent.com/12789369/119243280-20470080-bb1a-11eb-9bcc-4c95a6dd18f3.png)
```
System.Configuration.ConfigurationErrorsException
  HResult=0x80131902
  Message=Configuration system failed to initialize
  Source=System.Configuration.ConfigurationManager
  StackTrace:
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   at System.Configuration.ClientConfigurationSystem.PrepareClientConfigSystem(String sectionName)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.RefreshConfig(String sectionName)
   at System.Configuration.ConfigurationManager.RefreshSection(String sectionName)
   at System.Configuration.ClientSettingsStore.ReadSettings(String sectionName, Boolean isUserScoped)
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   at System.Configuration.SettingsBase.get_Item(String propertyName)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   at System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   at CareLink.My.MySettings.get_username() in C:\Users\PaulM\Source\Repos\CareLink\CareLink\My Project\Settings.Designer.vb:line 62
   at CareLink.LoginForm1.LoginForm1_Load(Object sender, EventArgs e) in C:\Users\PaulM\Source\Repos\CareLink\CareLink\LoginForm1.vb:line 12
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
ConfigurationErrorsException: Unrecognized configuration section system.diagnostics. (C:\Users\PaulM\Source\Repos\CareLink\CareLink\bin\Debug\net5.0-windows\CareLink.dll.config line 8)
```

**Expected behavior:**
I can read settings

**Minimal repro:**
Contents of .config file
```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <configSections>
        <sectionGroup name="userSettings" type="System.Configuration.UserSettingsGroup, System.Configuration.ConfigurationManager, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" >
            <section name="CareLink.My.MySettings" type="System.Configuration.ClientSettingsSection, System.Configuration.ConfigurationManager, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" allowExeDefinition="MachineToLocalUser" requirePermission="false" />
        </sectionGroup>
    </configSections>
```
Manually deleting system.diagnostics section fixes the issue until a rebuild.
```
    <system.diagnostics>
        <sources>
            <!-- This section defines the logging configuration for My.Application.Log -->
            <source name="DefaultSource" switchName="DefaultSwitch">
                <listeners>
                    <add name="FileLog"/>
                    <!-- Uncomment the below section to write to the Application Event Log -->
                    <!--<add name="EventLog"/>-->
                </listeners>
            </source>
        </sources>
        <switches>
            <add name="DefaultSwitch" value="Information" />
        </switches>
        <sharedListeners>
            <add name="FileLog"
                 type="Microsoft.VisualBasic.Logging.FileLogTraceListener, Microsoft.VisualBasic, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL"
                 initializeData="FileLogWriter"/>
            <!-- Uncomment the below section and replace APPLICATION_NAME with the name of your application to write to the Application Event Log -->
            <!--<add name="EventLog" type="System.Diagnostics.EventLogTraceListener" initializeData="APPLICATION_NAME"/> -->
        </sharedListeners>
    </system.diagnostics>
```
From here down works
```
    <userSettings>
        <CareLink.My.MySettings>
            <setting name="username" serializeAs="String">
                <value />
            </setting>
            <setting name="password" serializeAs="String">
                <value />
            </setting>
        </CareLink.My.MySettings>
    </userSettings>
</configuration>
```

**Comment by KlausLoeffelmann** [comment]
Hey Paul, thanks for reporting this.
And also thank you for providing that workaround.

Project System knows about general issues with conflicting Framework/.NET Core/5 assembly versions, and we're working on a solution.

@KathleenDollard  for FYI!

**Comment by paul1956** [comment]
@KlausLoeffelmann, it seems if you delete the problem sections from App.Config manually. You can change setting and the changes work at runtime and the error doesn't happen of course you lose the features you comment out (Logging).

**Comment by RussKie** [comment]
> Project System knows about general issues with conflicting Framework/.NET Core/5 assembly versions, and we're working on a solution.

@KlausLoeffelmann is this tracked somewhere to which we can link?

**Comment by paul1956** [comment]
I just ported a 10 year old WinForm app to .Net Core 5 using TryConvert. It used SQL, Excel and Office Interop and it went flawlessly except for the issue with App.Config any update on when this might be fixed, what does **external issue** mean? Also found a subtle bug in the code flagged by newest ,Net analyzers.

**Comment by RussKie** [comment]
> what does **external issue** mean?

It means just that, the issue is external to our codebase.

@KlausLoeffelmann the stack trace in https://github.com/dotnet/winforms-designer/issues/3596 looks very similar.
