### ISSUE TITLE
[ 6.0.100-preview.6.21322.2] PropertyGrid doesn't work well at HeroesPowerPlant when Enabled property is set False and PropertySort set to PropertySort.NoSort

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/winforms#5143]
**Application**: HeroesPowerPlant
**OS**: Windows 10 RS5
**CPU**: X64
**.NET Build Number**: 6.0.100-preview.6.21322.2

**Source Code & App check at :** https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1346436

**Verify Scenarios:**
1) Windows 10 RS5 X64 + dotnet-sdk-3.1.406   PASS
2) Windows 10 RS5 X64 + dotnet-sdk-5.0.200   PASS
3) Windows 10 RS5 X64 + 6.0.100-preview.6.21315.23 PASS
4) Windows 10 RS5 X64 +6.0.100-preview.6.21322.2: Fail

**Repro steps:**

This is 3.0 app, but we are running it on 6.0, machine only have 6.0 installed, and DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX=2, so it runs on 6.0

1) Launch application from HeroesPowerPlant.exe.   
2) Press F5 to open Layout Editor.
3) Click Add button. 

**Expected Result:**
It should add 'Nothing' item

**Actual Result:**
Unhandled exception has occurred in the application.

detailed information:
```
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.PropertyGridInternal.PropertyGridView.CountPropsFromOutline(GridEntryCollection rgipes) in System.Windows.Forms.dll:token 0x6004d2d+0xc
   at System.Windows.Forms.PropertyGridInternal.PropertyGridView.RecalculateProps() in System.Windows.Forms.dll:token 0x6004da7+0x0
   at System.Windows.Forms.PropertyGridInternal.PropertyGridView.Refresh(Boolean fullRefresh, Int32 rowStart, Int32 rowEnd) in System.Windows.Forms.dll:token 0x6004dab+0xfa
   at System.Windows.Forms.PropertyGridInternal.PropertyGridView.Refresh() in System.Windows.Forms.dll:token 0x6004da9+0x0
   at System.Windows.Forms.PropertyGrid.Refresh(Boolean clearCached) in System.Windows.Forms.dll:token 0x60033c6+0x3b
   at System.Windows.Forms.PropertyGrid.Refresh() in System.Windows.Forms.dll:token 0x60033c5+0xe
   at System.Windows.Forms.PropertyGrid.OnEnabledChanged(EventArgs e) in System.Windows.Forms.dll:token 0x60033a4+0x7
   at System.Windows.Forms.Control.set_Enabled(Boolean value) in System.Windows.Forms.dll:token 0x6001196+0x1a
   at HeroesPowerPlant.LayoutEditor.LayoutEditor.DisableDisplayData() in HeroesPowerPlant.dll:token 0x6000b67+0x53
   at HeroesPowerPlant.LayoutEditor.LayoutEditor.listBoxObjects_SelectedIndexChanged(Object sender, EventArgs e) in HeroesPowerPlant.dll:token 0x6000b45+0x43
   at System.Windows.Forms.ListBox.OnSelectedIndexChanged(EventArgs e) in System.Windows.Forms.dll:token 0x6002b30+0xf1
   at System.Windows.Forms.ListBox.ClearSelected() in System.Windows.Forms.dll:token 0x6002b10+0x55
   at HeroesPowerPlant.LayoutEditor.LayoutEditor.ButtonAdd_Click(Object sender, EventArgs e) in HeroesPowerPlant.dll:token 0x6000b46+0xb
   at System.Windows.Forms.Control.OnClick(EventArgs e) in System.Windows.Forms.dll:token 0x6001316+0x21
   at System.Windows.Forms.Button.OnClick(EventArgs e) in System.Windows.Forms.dll:token 0x6000e3b+0x5c
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent) in System.Windows.Forms.dll:token 0x6000e3d+0x66
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks) in System.Windows.Forms.dll:token 0x60013ed+0x177
   at System.Windows.Forms.Control.WndProc(Message& m) in System.Windows.Forms.dll:token 0x60013fd+0x778
   at System.Windows.Forms.ButtonBase.WndProc(Message& m) in System.Windows.Forms.dll:token 0x6000ea0+0x11a
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m) in System.Windows.Forms.dll:token 0x6005425+0x85
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam) in System.Windows.Forms.dll:token 0x6002f2f+0x6a
```

**Minimal Repro steps:**

1) Create Windows Forms  App (.net6 or .net5, but we need to run on .net6)
2) Add PropertyGrid component, we can drag from Toolbox
3) Insert this code to Form1.cs :
```
public Form1()
{
InitializeComponent();
var dictionary = new Dictionary<string, string>();
dictionary.Add("cat", "blue");
dictionary.Add("dog", "green");
propertyGrid1.PropertySort = PropertySort.NoSort; // if we remove this line, app doesn't crash but                                                                                                     //PropertyGrid is not disabled, also it does                                                                                                           //not  show any data
propertyGrid1.SelectedObject = dictionary;
propertyGrid1.Enabled = false;
}
```
**Expected Result**:

PropertyGrid should be disabled

**Actual Result**:
```
Object reference not set to an instance of an object.
   at System.Windows.Forms.PropertyGridInternal.PropertyGridView.CountPropsFromOutline(GridEntryCollection rgipes)
   at System.Windows.Forms.PropertyGridInternal.PropertyGridView.RecalculateProps()
   at System.Windows.Forms.PropertyGridInternal.PropertyGridView.Refresh(Boolean fullRefresh, Int32 rowStart, Int32 rowEnd)
   at System.Windows.Forms.PropertyGridInternal.PropertyGridView.Refresh()
   at System.Windows.Forms.PropertyGrid.Refresh(Boolean clearCached)
   at System.Windows.Forms.PropertyGrid.Refresh()
   at System.Windows.Forms.PropertyGrid.OnEnabledChanged(EventArgs e)
   at System.Windows.Forms.Control.set_Enabled(Boolean value)
   at WinFormsApp4.Form1..ctor() in C:\Users\appcompat\source\repos\TestApp6\WinFormsApp4\Form1.cs:line 23

```
Note:  We think this issue is related to System.Windows.Forms.dll

@dotnet-actwx-bot @dotnet/compat

**Comment by dreddy-work** [comment]
@vladimir-krestov , is this related to the one you guys fixed recently? @Junjun-zhao , did you try with latest preview?

**Comment by RussKie** [comment]
This appears to be a regression in net6.0

![image](https://user-images.githubusercontent.com/4403806/123184285-b5049b80-d4d6-11eb-9ded-2db34ed02d15.png)

**Comment by Junjun-zhao** [comment]
@dreddy-work   Yes,  We tired. It repro on the latest preview build 6.0.100-preview.6.21322.2 .

**Comment by vladimir-krestov** [comment]
@dreddy-work, no, it's not related to the previous our work.

Yes, this is a regression, it apprears since c5e6890d27861fabd53da802c4da5c7da24ef883.
Loot at `GridEntry.cs` file, line 133:

![image](https://user-images.githubusercontent.com/49272759/123257600-0de62b00-d4fb-11eb-9ad4-3aef1c47a6c3.png)

Here `_flags` field should be used like in the rest places of this change (#5058).
The exception appears because we are triyng to get `_propertyInfo` field that is not inicialized yet in the base constructor (see `PropertyDescriptorGridEntry` constructor).
Actually, we can rework the line 133 to the following:
`Flags = Flags | FLAG_FORCE_READONLY;`
And you can see, that we call `Flags.get` firstly. In the getter we are trying to get `_propertyInfo` through `TypeConverter` (see the PropertyDescriptorGridEntry's overridden property).

I propose to change using `Flags` to `_flags` as it was before. @JeremyKuhne, could you please say, can we make this? And is there any reasons why we should use `Flags` instead of `_flags` that were used before (`flags`)?

**Comment by JeremyKuhne** [comment]
> I propose to change using Flags to _flags as it was before. @JeremyKuhne, could you please say, can we make this? And is there any reasons why we should use Flags instead of _flags that were used before (flags)?

@vladimir-krestov yes, please make the change. If you can write a regression test that would be fantastic.

**Comment by Philip-Wang01** [comment]
Verified the issue with latest .Net 6.0.100-rc.1.21368.3(x64) that this issue is fixed: PropertyGrid doesn't work well at HeroesPowerPlant when Enabled property is set False and PropertySort set to PropertySort.NoSort.
![deyege](https://user-images.githubusercontent.com/86937911/126126168-132b1a16-d542-468f-8ca7-79f1f22d9118.gif)

**Comment by Junjun-zhao** [comment]
Thanks.  Verified this with SDK dotnet-sdk-6.0.100-preview.7.21368.1, this issue also has been fixed.
