### ISSUE TITLE
Selection of dropdown throws exception in getting Accessible role

### ISSUE THREAD

**Issue by dreddy-work** [dotnet/winforms#5397]
* .NET Core Version: 
6.0

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**

A simple form with propertygrid that has label as selected object. At runtime,  clicking on dropdown items is causing exception while accessing Accessible role for ListboxItemAccessibleObject. FOllowing is stacktrace,

   at Accessibility.IAccessible.get_accRole(Object varChild)
   at System.Windows.Forms.ListBox.ListBoxItemAccessibleObject.get_Role() in C:\workspace\winforms\src\System.Windows.Forms\src\System\Windows\Forms\ListBox.ItemAccessibleObject.cs:line 135
   at System.Windows.Forms.AccessibleObject.Accessibility.IAccessible.get_accRole(Object childID) in C:\workspace\winforms\src\System.Windows.Forms\src\System\Windows\Forms\AccessibleObject.cs:line 1293
   at System.Windows.Forms.InternalAccessibleObject.Interop.UiaCore.IAccessibleInternal.get_accRole(Object childID) in C:\workspace\winforms\src\System.Windows.Forms\src\System\Windows\Forms\InternalAccessibleObject.cs:line 189

**Expected behavior:**
No exception.

**Minimal repro:**
sample app attached. Clicking on any dropdown in the property grid at runtime would throw exception.

[TestDpiChanging (2).zip](https://github.com/dotnet/winforms/files/6941598/TestDpiChanging.2.zip)

**Comment by Marie-Shi** [comment]
Verified this issue with .Net 6.0.100-rc.1.21417.19 from Release/6.0.1XX, it is fixed. No exception throwing when selecting dropdown list item.
![issue_update](https://user-images.githubusercontent.com/45864017/130035763-4b771fff-55e3-4f53-8402-6df19dbb4e82.png)

**Comment by Jenna-Zheng** [comment]
Verified the issue with .NET Core SDK 5.0.402, the issue has been fixed that have the same results as above.
