### ISSUE TITLE
Unhandled exception about "System.Drawing.Common is not supported on this platform" occurs when running winforms application

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#5476]
* .NET Core Version: 
.Net 6.0 RC1 build: 6.0.100-rc.1.21418.27 from release/6.0.1xx-rc1 branch in https://github.com/dotnet/installer
**This is a regression issue**, cannot repro previous .Net 6.0 build: 6.0.100-rc.1.21417.19

* Have you experienced this same bug with .NET Framework?: 
No

**Minimal repro:**
1. Create a Winforms .Net 6.0 application
2. Build and run app

**Expected behavior:**
Build and run successfully

**Actual behavior:**
Run app failed with an exception: "System.Drawing.Common is not supported on this platform" 
![image](https://user-images.githubusercontent.com/26474449/130025157-be38b9ab-1e8c-4bc2-a1d3-b4a120b1ec1d.png)

System.PlatformNotSupportedException
  HResult=0x80131539
  Message=System.Drawing.Common is not supported on this platform.
  Source=System.Drawing.Common
  StackTrace:
   at System.Drawing.SystemFonts.get_MessageBoxFont()
   at System.Windows.Forms.Control.get_DefaultFont()
   at System.Windows.Forms.Control.GetDefaultFontHandleWrapper()
   at System.Windows.Forms.Control.get_FontHandle()
   at System.Windows.Forms.ContainerControl.GetFontAutoScaleDimensions()
   at System.Windows.Forms.ContainerControl.get_CurrentAutoScaleDimensions()
   at System.Windows.Forms.ContainerControl.get_AutoScaleFactor()
   at System.Windows.Forms.ContainerControl.PerformAutoScale(Boolean includedBounds, Boolean excludedBounds, Boolean causedByFontChanged)
   at System.Windows.Forms.ContainerControl.PerformNeededAutoScaleOnLayout()
   at System.Windows.Forms.Form.OnLayout(LayoutEventArgs levent)
   at System.Windows.Forms.Control.PerformLayout(LayoutEventArgs args)
   at System.Windows.Forms.Control.System.Windows.Forms.Layout.IArrangedElement.PerformLayout(IArrangedElement affectedElement, String affectedProperty)
   at System.Windows.Forms.ContainerControl.LayoutScalingNeeded()
   at System.Windows.Forms.ContainerControl.set_AutoScaleMode(AutoScaleMode value)
   at WinFormsApp31.Form1.InitializeComponent() in C:\Users\v-olzhan\source\repos\WinFormsApp31\WinFormsApp31\Form1.Designer.cs:line 32
   at WinFormsApp31.Form1..ctor() in C:\Users\v-olzhan\source\repos\WinFormsApp31\WinFormsApp31\Form1.cs:line 17
   at WinFormsApp31.Program.Main() in C:\Users\v-olzhan\source\repos\WinFormsApp31\WinFormsApp31\Program.cs:line 20

**Comment by dreddy-work** [comment]
@Olina-Zhang , is this the case with `main` as well?

**Comment by dreddy-work** [comment]
@safern, do you know anything changed in RC for Drawing.Common?

**Comment by ericstj** [comment]
We did change https://github.com/dotnet/runtime/commit/2ccf787faaf5798253a66d81be716798c751175f however that should only apply on Unix.  @ViktorHofer perhaps something changed in how we share this binary with WinForms to give them the wrong implementation?

**Comment by ericstj** [comment]
I can confirm this.  Rather than picking up the Windows implementations WindowsDesktop is getting the RID-less implementations.  @ViktorHofer I think it's due to this: https://github.com/dotnet/runtime/blob/948770a23b1e1b5d128d7bbc06f172fbd01d4ba5/src/libraries/Microsoft.Internal.Runtime.WindowsDesktop.Transport/src/Microsoft.Internal.Runtime.WindowsDesktop.Transport.proj#L3
