### ISSUE TITLE
System.Runtime.InteropServices.ExternalException : A generic error occurred in GDI+

### ISSUE THREAD

**Issue by StefanKoell** [dotnet/winforms#5704]
* .NET Core Version: 
Microsoft.WindowsDesktop.App 5.0.9

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**
I switched my WinForms App from .NET 4.71 to .NET 5 and get the following crashes from my user's machine:
```
System.Runtime.InteropServices.ExternalException: A generic error occurred in GDI+.
Source: System.Drawing.Common
    -- get_ErrorCode = -2147467259 (0x80004005)   [int]
    -- get_HResult = -2147467259 (0x80004005)   [int]
 at [System.Drawing.Common] System.Drawing.Graphics void CheckErrorStatus(int )
 at [System.Drawing.Common] System.Drawing.Graphics void FillRectangle(System.Drawing.Brush ,System.Drawing.Rectangle )
```

From the stack trace, I can see that this crash almost always originates from showing a messagebox (drawing the background). Since I'm not able to reproduce the crash myself, I reached out to my users and I was at least able to find a common pattern:
- Many users told me that the crash happens when the machine has been in sleep mode and wakes up. My app would show a message box when a network connection is interrupted, so this makes sense.
- Some users reported that the crash happens when Windows tries to shutdown/reboot while my app is running.
- Some users reported that the crash happens when my app is set to auto-run and shows the first dialog (password prompt). In this case it seems that the app has been started while the login screen is still shown.

Judging from the user reports, I guess this crash mostly happens when the "desktop" is "hidden" or not shown (like lock screen when the machine enters sleep mode, login screen, the screen shown when you shutdown/reboot Windows).

I'm not sure how to further troubleshoot the issue or resolve the issue.

**Minimal repro:**
Unfortunately I'm not able to reliably reproduce the issue myself.

**Comment by kirsan31** [comment]
Interesting...
Can you post some more (and a beet deeper) stack traces?
We faced a similar problems.
Long story...
Such errors never happens on .Net472.
After we switched to .NetCore 3.1, we have several such errors (during a year) **only** on Windows7 machine:
```
UnhandledException details: System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.DrawLine(Pen pen, Int32 x1, Int32 y1, Int32 x2, Int32 y2)
   at ...FrmBase.WndProc(Message& m) in ...
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

`WndProc` (override in Form class) is something like this:
```cs
protected override void WndProc(ref System.Windows.Forms.Message m)
{
    base.WndProc(ref m);

    IntPtr hdc = WinApi.User32.GetWindowDC(m.HWnd);
    if (hdc == IntPtr.Zero)
        return;

    using (Graphics g = Graphics.FromHdc(hdc))
    {
        g.DrawLine(ErrorPen, 0, 0, this.Width, 0);
    }
    WinApi.User32.ReleaseDC(m.HWnd, hdc);
}
```
After we switched to .Net5, this error began to appear several times a day, but again **only on windows7** machine.
Since I was not able to provide a 100% reproduction method, I did not report it.  

Also on .Net5, several times (win 10) we got this:
```
UnhandledException details: System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.FillRectangle(Brush brush, Int32 x, Int32 y, Int32 width, Int32 height)
   at System.Windows.Forms.ToolStripTextBox.ToolStripTextBoxControl.WmNCPaint(Message& m)
   at System.Windows.Forms.ToolStripTextBox.ToolStripTextBoxControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
   at Interop.User32.CallWindowProcW(IntPtr wndProc, IntPtr hWnd, WM msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.NativeWindow.DefWndProc(Message& m)
   at System.Windows.Forms.Control.DefWndProc(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TextBoxBase.WndProc(Message& m)
   at System.Windows.Forms.TextBox.WndProc(Message& m)
   at System.Windows.Forms.ToolStripTextBox.ToolStripTextBoxControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
   at Interop.User32.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.Interop.Mso.IMsoComponentManager.FPushMessageLoop(UIntPtr dwComponentID, msoloop uReason, Void* pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
```
and this one looks more similar to your...

**Comment by StefanKoell** [comment]
Nice to see that I'm not alone!

I don't have any of these reports from Windows 7 machines. This could mean that it doesn't exist on Windows 7 or my user base doesn't use Windows 7 anymore.

As for deeper stack traces, here's one:
```
System.Runtime.InteropServices.ExternalException: A generic error occurred in GDI+.
Source: System.Drawing.Common
    -- get_ErrorCode = -2147467259 (0x80004005)   [int]
    -- get_HResult = -2147467259 (0x80004005)   [int]
 at [System.Drawing.Common] System.Drawing.Graphics void CheckErrorStatus(int )
 at [System.Drawing.Common] System.Drawing.Graphics void FillRectangle(System.Drawing.Brush ,System.Drawing.Rectangle )
 at [DevExpress.Utils.v21.1] DevExpress.Utils.Paint.XPaint void FillRectangle(System.Drawing.Graphics ,System.Drawing.Brush ,System.Drawing.Rectangle )
 at [DevExpress.Utils.v21.1] DevExpress.Skins.SkinElementPainter void FillSkinBackground(DevExpress.Utils.Drawing.ObjectInfoArgs ,DevExpress.Skins.SkinElement )
 at [DevExpress.Utils.v21.1] DevExpress.Skins.SkinElementPainter void DrawObject(DevExpress.Utils.Drawing.ObjectInfoArgs )
 at [DevExpress.Utils.v21.1] DevExpress.Utils.Drawing.ObjectPainter void DrawObject(DevExpress.Utils.Drawing.GraphicsCache ,DevExpress.Utils.Drawing.ObjectPainter ,DevExpress.Utils.Drawing.ObjectInfoArgs )
 at [DevExpress.Utils.v21.1] DevExpress.XtraEditors.FormShowHelperBase void ProcessPaintBackground(System.Windows.Forms.Message )
 at [DevExpress.Utils.v21.1] DevExpress.XtraEditors.FormShowHelperBase void WndProc(System.Windows.Forms.Message )
 at [DevExpress.Utils.v21.1] DevExpress.XtraEditors.XtraForm void WndProc(System.Windows.Forms.Message& )
 at [DevExpress.XtraEditors.v21.1] DevExpress.XtraEditors.XtraBaseForm void WndProc(System.Windows.Forms.Message& )
 at [System.Windows.Forms] System.Windows.Forms.Control/ControlNativeWindow void WndProc(System.Windows.Forms.Message& )
 at [System.Windows.Forms] System.Windows.Forms.NativeWindow System.IntPtr Callback(System.IntPtr ,Interop+User32/WM ,System.IntPtr ,System.IntPtr )
```
I'm also using the DevExpress UI libraries but I also have seen stacktraces like yours, pure WinForms. Since the FillRectangle method seems to be a common entry point for most stack traces I get, I guess it has something to do with the GDI graphics context when Windows shows a non interactive desktop, such as the lock, login or shutdown screen.

I hope someone can shed some light on the error and on how to further troubleshoot the issue. If I know which data I should collect, I could try to attach this to my crash reports for further investigation.

**Comment by StefanKoell** [comment]
Well, I just looked at the CheckErrorStatus method in the framework code and found this comment in Graphics.Windows.cs:

        /// <summary>
        /// GDI+ will return a 'generic error' with specific win32 last error codes when
        /// a terminal server session has been closed, minimized, etc... We don't want 
        /// to throw when this happens, so we'll guard against this by looking at the
        /// 'last win32 error code' and checking to see if it is either 1) access denied
        /// or 2) proc not found and then ignore it.
        /// 
        **/// The problem is that when you lock the machine, the secure desktop is enabled and 
        /// rendering fails which is expected (since the app doesn't have permission to draw 
        /// on the secure desktop). Not sure if there's anything you can do, short of catching 
        /// the desktop switch message and absorbing all the exceptions that get thrown while 
        /// it's the secure desktop.**
        /// </summary>

I couldn't find this file in the github repo but if you navigate to a FillRectangle call in your code using JetBrains Rider and navigate to the definition, you will get to that code (and comment).

Now I'm really confused how this could have worked in .NET Framework 4.71. I guess there has been code in place which took this scenario into account. I'm wondering why this hasn't been ported or handled properly. Anyone has some more information?

**Comment by kirsan31** [comment]
It seems that `CheckErrorStatus` is defiantly here to protect us from what happens in this topic :) But for some reason in core it's not always working...
The code of `CheckErrorStatus` doesn't changed:

[.Net](https://referencesource.microsoft.com/System.Drawing/R/5a91110038389dd5.html):
```cs
private void CheckErrorStatus(int status) {
    if (status != SafeNativeMethods.Gdip.Ok) {
        // Generic error from GDI+ can be GenericError or Win32Error.
        if (status == SafeNativeMethods.Gdip.GenericError || status == SafeNativeMethods.Gdip.Win32Error) {
            int error = Marshal.GetLastWin32Error();
            if (error == SafeNativeMethods.ERROR_ACCESS_DENIED || error == SafeNativeMethods.ERROR_PROC_NOT_FOUND || 
                    //here, we'll check to see if we are in a term. session...
                    (((UnsafeNativeMethods.GetSystemMetrics(NativeMethods.SM_REMOTESESSION) & 0x00000001) != 0) && (error == 0))) {
                    return;
                }
            }

        //legitimate error, throw our status exception
        throw SafeNativeMethods.Gdip.StatusException(status);
    }
}
```
.net5: 

https://github.com/dotnet/runtime/blob/208e377a5329ad6eb1db5e5fb9d4590fa50beadd/src/libraries/System.Drawing.Common/src/System/Drawing/Graphics.cs#L2421-L2440

**Comment by StefanKoell** [comment]
I see. I find it really strange how this can work in .NET 4.71 without a single crash and not always work in .NET 5 with so many crashes. The status, which is passed into the CheckErrorStatus method is the native GDI+ FillRectangle method which I assume is the same in both frameworks.

**Comment by kirsan31** [comment]
> I see. I find it really strange how this can work in .NET 4.71 without a single crash and not always work in .NET 5 with so many crashes. The status, which is passed into the CheckErrorStatus method is the result of the native GDI+ FillRectangle method which I assume is the same in both frameworks.

My guess is that in core `GetLastWin32Error` can return somthing different than in .Net Framework?

[.Net Framework](https://referencesource.microsoft.com/System.Drawing/R/72c3918085efa357.html):
```cs
[DllImport(ExternDll.Gdiplus, SetLastError=true, ExactSpelling=true, CharSet=System.Runtime.InteropServices.CharSet.Unicode)] // 3 = Unicode
            [ResourceExposure(ResourceScope.None)]
            internal static extern int GdipFillRectangleI(HandleRef graphics, HandleRef brush, int x, int y,
                                                          int width, int height);
```

[.net5](https://github.com/dotnet/runtime/blob/208e377a5329ad6eb1db5e5fb9d4590fa50beadd/src/libraries/System.Drawing.Common/src/System/Drawing/GdiplusNative.cs#L1222-L1223):
```cs
[DllImport(LibraryName, ExactSpelling = true)]
internal static extern int GdipFillRectangleI(HandleRef graphics, HandleRef brush, int x, int y, int width, int height);
```

In .net I see no `SetLastError=true`...

**Comment by StefanKoell** [comment]
Good catch! I hope that someone at MS (@OliaG) can take a look at it.

**Comment by RussKie** [comment]
It is plausible that the missing `SetLastError` attribute is the cause, but without a stand alone repro there would be a lot of speculations, and very difficult convince the ship room to allow servicing of .NET 6.0 (RC2 is almost complete) let alone 5.0...

System.Drawing.Common belong to dotnet/runtime, moving there.
