### ISSUE TITLE
ObjectDisposedException when closing a Form with TopMost=true inside its OnLoad event handler

### ISSUE THREAD

**Issue by andrekoehler** [dotnet/winforms#6071]
* .NET Core Version: 
5.0.11

* Have you experienced this same bug with .NET Framework?: 
Yes

**Problem description:**

```
System.ObjectDisposedException
  HResult=0x80131622
  Message=Cannot access a disposed object.
Object name: 'Form1'.
  Source=System.Windows.Forms
  StackTrace:
   at System.Windows.Forms.Control.CreateHandle() in /_/src/System.Windows.Forms/src/System/Windows/Forms/Control.cs:line 4883
   at System.Windows.Forms.Form.CreateHandle() in /_/src/System.Windows.Forms/src/System/Windows/Forms/Form.cs:line 3131
   at System.Windows.Forms.Control.get_Handle() in /_/src/System.Windows.Forms/src/System/Windows/Forms/Control.cs:line 2455
   at System.Windows.Forms.ContainerControl.FocusActiveControlInternal() in /_/src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs:line 669
   at System.Windows.Forms.Form.SetVisibleCore(Boolean value) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Form.cs:line 2322
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(msoloop reason, ApplicationContext context) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs:line 1028
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(msoloop reason, ApplicationContext context) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs:line 975
   at System.Windows.Forms.Application.Run(Form mainForm) in /_/src/System.Windows.Forms/src/System/Windows/Forms/Application.cs:line 1198
   at WinFormsApp2.Program.Main() in C:\dev\_tests\WinFormsApp2\Program.cs:line 21
```

**Expected behavior:**
No exception.

**Minimal repro:**
Create a new Windows Forms App and change the code in Form1.cs as follows:
```
public Form1()
{
    TopMost = true;
    InitializeComponent();
}

protected override void OnLoad(EventArgs e)
{
    base.OnLoad(e);
    Close();
}
```
Then compile & run the application. The exception will occur immediately.

**Comment by AraHaan** [comment]
This is because you call Close in OnLoad() almost immediately.

**Comment by andrekoehler** [comment]
@AraHaan Is there any documentation that states that this is a bad idea? In OnLoad we initialze a camera because it is a camera setup dialog and if anything goes wrong during that step we show an error MessageBox and then close the dialog.

**Comment by AraHaan** [comment]
> @AraHaan Is there any documentation that states that this is a bad idea? Our use case is that in OnLoad we initialze a camera because it is a camera setup dialog and if anything goes wrong during that step we show an error MessageBox and then close the dialog.

That is fine as long as something blocked the call before it tries to call Close() on the form.

**Comment by andrekoehler** [comment]
@AraHaan So how do I know from which time on am I allowed to Close() the form? Should in use `BeginInvoke(() => this.Close())` inside the OnLoad handler?

**Comment by kirsan31** [comment]
@andrekoehler it's hard to say something concrete without full picture of your code.
 I think that the problem is in `TopMost = true;`. Try to set `TopMost = false;` before calling `Close();`...
Or even better set `TopMost = true;` in `OnLoad` **only** if you will show the form.

**Comment by andrekoehler** [comment]
@kirsan31 You don't need any more code than I provided in order to reproduce what is in my opinion a bug. Setting TopMost = false; before calling Close(); is indeed the workaround I am using in our project right now but I wanted to report this so it can get fixed.

**Comment by kirsan31** [comment]
> @kirsan31 You don't need any more code than I provided in order to reproduce what is in my opinion a bug.

it's was about this your sentence:

> So how do I know from which time on am I allowed to Close() the form?

**Comment by RussKie** [comment]
Looks like you found a workaround. Since this is an existing behaviour (i.e., .NET Framework reproduces the same) we are not going to change it.
