### ISSUE TITLE
System.Runtime.Serialization.SerializationException occurs on deserialize Calendar

### ISSUE THREAD

**Issue by SlavaB** [dotnet/winforms#616]
* .NET Core 3.0 Preview 4
* Have you experienced this same bug with .NET Framework?: No

**Problem description:**

System.Runtime.Serialization.SerializationException with Message=Type 'System.Globalization.GregorianCalendar' in Assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' is not marked as serializable.
ocurrs. Please find the attached sample to reproduce.
[DotNetCore3Calendar.zip](https://github.com/dotnet/winforms/files/2986949/DotNetCore3Calendar.zip)

**Actual behavior:** 

System.Runtime.Serialization.SerializationException
  HResult=0x8013150C
  Message=Type 'System.Globalization.GregorianCalendar' in Assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' is not marked as serializable.
  Source=System.Runtime.Serialization.Formatters
  StackTrace:
   at System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers(Type type)
   at System.Runtime.Serialization.FormatterServices.<>c.<GetSerializableMembers>b__5_0(MemberHolder mh)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at System.Runtime.Serialization.FormatterServices.GetSerializableMembers(Type type, StreamingContext context)
   at System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.InitMemberInfo()
   at System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.InitReadConstructor(Type objectType, ISurrogateSelector surrogateSelector, StreamingContext context)
   at System.Runtime.Serialization.Formatters.Binary.ObjectMap..ctor(String objectName, String[] memberNames, BinaryTypeEnum[] binaryTypeEnumA, Object[] typeInformationA, Int32[] memberAssemIds, ObjectReader objectReader, Int32 objectId, BinaryAssemblyInfo assemblyInfo, SizedArray assemIdToAssemblyTable)
   at System.Runtime.Serialization.Formatters.Binary.ObjectMap.Create(String name, String[] memberNames, BinaryTypeEnum[] binaryTypeEnumA, Object[] typeInformationA, Int32[] memberAssemIds, ObjectReader objectReader, Int32 objectId, BinaryAssemblyInfo assemblyInfo, SizedArray assemIdToAssemblyTable)
   at System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectWithMapTyped(BinaryObjectWithMapTyped record)
   at System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectWithMapTyped(BinaryHeaderEnum binaryHeaderEnum)
   at System.Runtime.Serialization.Formatters.Binary.BinaryParser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(BinaryParser serParser, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, Boolean check)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)
   at System.Resources.ResourceReader.<>c__DisplayClass44_0`1.<CreateUntypedDelegate>b__0(Object obj, Stream stream)
   at System.Resources.ResourceReader.DeserializeObject(Int32 typeIndex)
   at System.Resources.ResourceReader._LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.ResourceReader.LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.ResourceReader.LoadObject(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.RuntimeResourceSet.GetObject(String key, Boolean ignoreCase, Boolean isString)
   at System.Resources.RuntimeResourceSet.GetObject(String key, Boolean ignoreCase)
   at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture, Boolean wrapUnmanagedMemStream)
   at System.Resources.ResourceManager.GetObject(String name)
   at WindowsFormsAppCalendar.Form1.InitializeComponent() in \.Net Core 3\Apps\DotNetCore3Calendar\WindowsFormsAppCalendar\Form1.Designer.cs:line 38
   at WindowsFormsAppCalendar.Form1..ctor() in \.Net Core 3\Apps\DotNetCore3Calendar\WindowsFormsAppCalendar\Form1.cs:line 16
   at DotNetCore3Calendar.Program.Main() in \.Net Core 3\Apps\DotNetCore3Calendar\DotNetCore3Calendar\Program.cs:line 19

**Expected behavior:**

Run sample without exception.

**Minimal repro:**

* Unpack the attached sample. 
* Open the DotNetCore3Cal.sln solution in Visual Studio 2019
* Build and run the DotNetCore3Calendar.csproj project - exception raised

Note the WindowsFormsAppCalendar.csproj (.NET Framework 4.0 WinForms project) runs without exception.

**Comment by merriemcgaw** [comment]
@dreddy-work can you take a look at this one? This relates to the resource serialization stuff you're working on. It may be that we need to consider WinForms controls like this one in our design.

**Comment by OliaG** [comment]
@dreddy-work , any updates on this one?

**Comment by dreddy-work** [comment]
We hae a known issue on some ofthese controls not supporting binary serialization. We are working on it. Will update the status as soon as we get to it.

**Comment by dreddy-work** [comment]
@OliaG Can you please help move this issue to coreclr repo?

**Comment by merriemcgaw** [comment]
Issue moved to [dotnet/coreclr #23567](https://github.com/dotnet/coreclr/issues/23567) via [**ZenHub**](https://www.zenhub.com/)
