### ISSUE TITLE
.NET 6 Cannot read resources that depend on serialization

### ISSUE THREAD

**Issue by qwertybba** [dotnet/winforms#6541]
* .NET Core Version:  6.0.101

* Have you experienced this same bug with .NET Framework?:  No 

**Problem description:**
When I run the WinForm application from VS2022 and try to open one of the forms I get this error:

> System.NotSupportedException
  HResult=0x80131515
  Message=Cannot read resources that depend on serialization.
  Source=System.Resources.Extensions
  StackTrace:
   at System.Resources.Extensions.DeserializingResourceReader.UseReflectionToGetType(Int32 typeIndex)
   at System.Resources.Extensions.DeserializingResourceReader.DeserializeObject(Int32 typeIndex)
   at System.Resources.Extensions.DeserializingResourceReader.LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.Extensions.DeserializingResourceReader.ResourceEnumerator.get_Entry()
   at System.Resources.Extensions.DeserializingResourceReader.ResourceEnumerator.get_Current()
   at System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   at System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   at System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   at System.ComponentModel.ComponentResourceManager.ApplyResources(Object value, String objectName, CultureInfo culture)
   at SmartWinForm.PL.FrmWeldingProduction.InitializeComponent() in C:\Users\MBoua\source\repos\SmartWinForm\SmartWinForm\PL\FrmWeldingProduction.Designer.cs:line 295
   at SmartWinForm.PL.FrmWeldingProduction..ctor() in C:\Users\MBoua\source\repos\SmartWinForm\SmartWinForm\PL\FrmWeldingProduction.cs:line 23
   at SmartWinForm.PL.XtraMain.bbtnWeldingProduction_ItemClick(Object sender, ItemClickEventArgs e) in C:\Users\MBoua\source\repos\SmartWinForm\SmartWinForm\PL\XtraMain.cs:line 973
   at DevExpress.XtraBars.BarItem.OnClick(BarItemLink link)
   at DevExpress.XtraBars.BarBaseButtonItem.OnClick(BarItemLink link)
   at DevExpress.XtraBars.BarButtonItem.OnClick(BarItemLink link)
   at DevExpress.XtraBars.BarItemLink.OnLinkClick()
   at DevExpress.XtraBars.BarButtonItemLink.OnLinkClick()
   at DevExpress.XtraBars.BarButtonItemLink.OnLinkAction(BarLinkAction action, Object actionArgs)
   at DevExpress.XtraBars.ViewInfo.BarSelectionInfo.ClickLink(BarItemLink link)
   at DevExpress.XtraBars.ViewInfo.BarSelectionInfo.UnPressLink(BarItemLink link)
   at DevExpress.XtraBars.Ribbon.Handler.BaseRibbonHandler.OnUnPressItem(DXMouseEventArgs e, RibbonHitInfo hitInfo)
   at DevExpress.XtraBars.Ribbon.Handler.BaseRibbonHandler.OnUnPress(DXMouseEventArgs e, RibbonHitInfo hitInfo)
   at DevExpress.XtraBars.Ribbon.Handler.RibbonHandler.OnUnPress(DXMouseEventArgs e, RibbonHitInfo hitInfo)
   at DevExpress.XtraBars.Ribbon.Handler.BaseRibbonHandler.OnMouseUp(DXMouseEventArgs e)
   at DevExpress.XtraBars.Ribbon.Handler.RibbonHandler.OnMouseUp(DXMouseEventArgs e)
   at DevExpress.XtraBars.Ribbon.RibbonControl.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at DevExpress.Utils.Controls.ControlBase.BaseWndProc(Message& m)
   at DevExpress.XtraBars.Ribbon.RibbonControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

I use:
Windows 11 Pro x64bit
VS2022 Version 17.0.5

**Comment by kirsan31** [comment]
May be https://github.com/dotnet/winforms/issues/2886 ?

**Comment by merriemcgaw** [comment]
@qwertybba have you been able to run this from earlier versions of VS? It would be great to have a targeted sample that demonstrates the issue so we can better troubleshoot it and rule out issues with 3rd party controls for example. 
@kirsan31 #2886 was the first think I thought of too.

**Comment by qwertybba** [comment]
Here's what I did:
01- I create a simple WINFORM project and run the project.
02- Set the **Localizable** property to True then the **Language** to French and run the project.
03- Add **DevExpress form ** then add some controls and run the project.
04- Set the **Localizable** property to True then the **Language** to French in DevExpress form and run the project.
05- Change Text property in **Localizable DevExpress form (fr)** and run the project **The problem occurs** 

WinFormsSerializationNet6 Project
[https://1drv.ms/u/s!Ak95wpRhTBw9gv4gDwg6gXgLGLQPkw](url)

**Comment by merriemcgaw** [comment]
@Olina-Zhang can you validate the scenario @qwertybba describes above without using DevExpress. This should be working and I'd like to confirm that nothing has broken recently.

**Comment by John-Qiao** [comment]
@merriemcgaw I have tested above scenario which @qwertybba describes without using DevExpress in these 3 projects: VS 17.0.5 WinForms project(targeting to .NET 6.0.1), VS 17.1.0 Preview 4.0 WinForms project(targeting to .NET 6.0.2) and latest VS 17.2.0 P1 WinForms project(targeting to latest .NET 7.0), the all work fine without error.

**Comment by qwertybba** [comment]
The same problem here
[https://developercommunity.visualstudio.com/t/Resx-files-of-multi-language-localizabl/1637863](url)

**Comment by kirsan31** [comment]
@qwertybba the link and text are not consistent.
text: `https://developercommunity.visualstudio.com/t/Resx-files-of-multi-language-localizabl/1637863` - correct
link: `https://github.com/dotnet/winforms/issues/url` - wrong

**Comment by qwertybba** [comment]
@kirsan31 I corrected it, thanks

**Comment by dreddy-work** [comment]
This seems an issue with DevExpress control libraries given that our stand-alone WinForms application is working as expected in similar scenario here. @qwertybba , did you reach out to DevExpress?

**Comment by RussKie** [comment]
@mikeroz FYI

**Comment by qwertybba** [comment]
> This seems an issue with DevExpress control libraries given that our stand-alone WinForms application is working as expected in similar scenario here. @qwertybba , did you reach out to DevExpress?

Yes, DevExpress engineers are aware of this problem.
The  [link](https://developercommunity.visualstudio.com/t/Resx-files-of-multi-language-localizabl/1637863) I mentioned above is created by one of the DevExpress engineers

**Comment by LexEPoX** [comment]
Hello,
I'm a DevExpress engineer who created the bug report mentioned by @qwertybba ([Resx files of multi-language (localizable) forms get corrupted if their child controls have properties without default values (.NET 6)](https://developercommunity.visualstudio.com/t/Resx-files-of-multi-language-localizabl/1637863)).

Although I shared a project that does not have DevExpress components and illustrates the issue, here is a copy of those files. Please let me know if you need additional information.

Steps to reproduce (can be also found in the [video](https://supportcenter.devexpress.com/internal/attachment/file/ec5cc1c6-3d90-4066-a664-2e7bad020b23)):

* Open the project from the [ResxSample_LocalizableUserControl_NETF452_converted_to_NET6_Initial.zip](https://github.com/dotnet/winforms/files/8001476/ResxSample_LocalizableUserControl_NETF452_converted_to_NET6_Initial.zip) archive.
* Check the `Form1.resx` file.
* Change any property of Form1 in the Visual Studio designer (v17.0.3-17.0.5), e.g., the form’s size.
* Check whether properties without default values are serialized incorrectly in `Form1.resx`.

[ResxSample_LocalizableUserControl_NETF452_converted_to_NET6_Initial.zip](https://github.com/dotnet/winforms/files/8001476/ResxSample_LocalizableUserControl_NETF452_converted_to_NET6_Initial.zip)
[ResxSample_LocalizableUserControl_NETF452_converted_to_NET6_Modified.zip](https://github.com/dotnet/winforms/files/8001475/ResxSample_LocalizableUserControl_NETF452_converted_to_NET6_Modified.zip)

![ResxNET6Issue-ExceptionDesigner](https://user-images.githubusercontent.com/13219327/152502465-b6f2d5b3-de67-4a38-b5ce-28e0ac2841b2.png)
![ResxNET6Issue-Exception](https://user-images.githubusercontent.com/13219327/152502469-ee52a936-89c5-4e01-b90e-1de77176a6a4.png)

**Comment by dreddy-work** [comment]
Reopening the issue for further investigation here.

**Comment by dreddy-work** [comment]
@Olina-Zhang , can you take look and try a repro with latest .NET 7.0 bits here?

**Comment by John-Qiao** [comment]
@dreddy-work I tested LexEPoX's scenario using his sample project with latest .NET 7.0 Preview2 SDK, it still repro, please check below gif result:
![TestResult](https://user-images.githubusercontent.com/45864985/153128372-024f309f-2ef6-4de8-a859-b8ebfef382b1.gif)

**Comment by merriemcgaw** [comment]
@KlausLoeffelmann was taking a look at this today. This is definitely a problem we need to root cause and address sooner rather than later.

**Comment by KlausLoeffelmann** [comment]
I have a fix in the Designer repo.
This is not a runtime issue.
