### ISSUE TITLE
Designer load encountered an error. Please ensure that the project can be built successfully.

### ISSUE THREAD

**Issue by nathan130200** [dotnet/winforms#6722]
Again another problem with designtoolsserver (from #6420)

Ok, so i got new error (updated to latest preview version from VS2022)

```cs
[16:25:46.8925168] Creating VSCodeDomDesignerLoader
[16:25:47.6300184] Processed 'System.Design' in 00:00:02.4840523
[16:25:47.6830170] Added 'System.Design'
[16:25:47.6840173] Loaded System.Drawing.Design in 00:00:00.0000227 [thread 56]
[16:25:47.6890185] Processed 'System.Drawing.Design' in 00:00:00.0055732
[16:25:47.6900189] Added 'System.Drawing.Design'
[16:25:48.8251525] [Thread 1] Creating design-time ITypeResolutionService.
[16:25:50.5392459] Start processing enqueued assemblies
[16:25:50.5392459] Loaded Microsoft.WinForms.DesignTools.Protocol in 00:00:00.0000178 [thread 79]
[16:25:50.7015014] Processed 'Microsoft.WinForms.DesignTools.Protocol' in 00:00:00.1625103
[16:25:50.7055005] Added 'Microsoft.WinForms.DesignTools.Protocol'
[16:25:50.7055005] Loaded Microsoft.WinForms.DesignTools.Client in 00:00:00.0000282 [thread 61]
[16:25:50.8610191] Processed 'Microsoft.WinForms.DesignTools.Client' in 00:00:00.1546868
[16:25:50.8630155] Added 'Microsoft.WinForms.DesignTools.Client'
[16:25:51.3873048] [Thread 68] Launching server...
[16:26:53.4778102] OutputGroupService didn't return output group DesignerRuntimeImplementationProjectOutputGroup.
[16:26:53.4778102] Could not retrieve DesignerRuntimeImplementationProjectOutputGroupPaths for current project.
[16:26:54.1809027] System.InvalidOperationException: Designer load encountered an error. Please ensure that the project can be built successfully.
                      at Microsoft.DotNet.DesignTools.Client.Host.ProjectInfoProvider.<GetProjectInfoAsync>d__4.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.DotNet.DesignTools.Client.Host.ServerHostFactory.<CreateHostAsync>d__7.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.DotNet.DesignTools.Client.DesignToolsClientLoader.<CreateClientAsync>d__28.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
[16:26:54.3889082] Cannot update selection in server process as Session is not connected.
```

Updated to latest visual studio 2022 preview. Using .net6.0

And in designer display this:

![image](https://user-images.githubusercontent.com/14365254/154816146-356d4f12-6653-47d1-a655-e97d2ca6de79.png)

And again i just created empty winforms project, and project can be built.

![image](https://user-images.githubusercontent.com/14365254/154816222-52f613ab-5f62-433c-bcb9-d20625c32c02.png)

### Same workaround from #6420 
I must close then reopen project to design tools server start

**Comment by RussKie** [comment]
I appreciate you have spent the time to raise the issue, but issues with VS and VS Designer should be sent via VS Feedback channel (the icon in the top right hand side corner). The reason for this - the VS Feedback tool captures a lot of additional information (such as screenshots, memory dumps, stack traces, assembly versions, etc.) that can help us to investigate your issue and identify the cause.

Please post the link to the VS Feedback issue here, so that our team can track it.

**Comment by nathan130200** [comment]
Oh thanks!
