### ISSUE TITLE
System.Windows.Forms.Timer got stuck after being disabled and enabled reentrantly

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/winforms#6779]
* .NET Core Version: 
Not yet reproduced on .NET Core, but the implementation is similar.

* Have you experienced this same bug with .NET Framework?: 
Yes, on .NET Framework 4.7.2.

**Problem description:**
System.Windows.Forms.Timer.TimerNativeWindow got into an invalid state in which NativeWindow.Handle == IntPtr.Zero but TimerNativeWindow._timerID != 0. After this, no more Timer.Tick events were raised, and assigning Timer.Enabled = false or Timer.Enabled = true had no effect.

Before the problem occurred, the application had enabled the timer. The application was then assigning Timer.Enabled = false. This caused TimerNativeWindow.StopTimer to call SafeNativeMethods.KillTimer and NativeWindow.DestroyHandle, which in turn called UnsafeNativeMethods.DestroyWindow. Normally, DestroyWindow would cause the window messages 0x90 (WM_UAHDESTROYWINDOW), 0x2 (WM_DESTROY), and 0x82 (WM_NCDESTROY) to be sent to the window. For unknown reasons in a RemoteApp environment, the 0x90 (WM_UAHDESTROYWINDOW) message was instead followed by WM_ACTIVATE to some other window. This indirectly caused Windows Forms to raise the Control.GotFocus event:

```
   at System.Windows.Forms.Control.OnGotFocus(EventArgs e)
   at System.Windows.Forms.TextBox.OnGotFocus(EventArgs e)
   at System.Windows.Forms.Control.WmSetFocus(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TextBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.SetFocus(HandleRef hWnd)
   at System.Windows.Forms.UnsafeNativeMethods.SetFocus(HandleRef hWnd)
   at System.Windows.Forms.ContainerControl.FocusActiveControlInternal()
   at System.Windows.Forms.Form.set_Active(Boolean value)
   at System.Windows.Forms.Form.WmActivate(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.IntDestroyWindow(HandleRef hWnd)
   at System.Windows.Forms.UnsafeNativeMethods.IntDestroyWindow(HandleRef hWnd)
   at System.Windows.Forms.UnsafeNativeMethods.DestroyWindow(HandleRef hWnd)
   at System.Windows.Forms.NativeWindow.DestroyHandle()
   at System.Windows.Forms.Timer.TimerNativeWindow.StopTimer(Boolean destroyHwnd, IntPtr hWnd)
   at System.Windows.Forms.Timer.set_Enabled(Boolean value)
   … redacted application-specific methods …
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   … redacted application-specific methods …
```

At this point, TimerNativeWindow._timerID was zero because KillTimer had finished, and NativeWindow.Handle was nonzero because DestroyWindow had not yet finished.

When the application handled the Control.GotFocus event, it wanted to restart the timer from the previously configured interval. It assigned Timer.Enabled = false and then Timer.Enabled = true. After these assignments, both TimerNativeWindow._timerID and NativeWindow.Handle were nonzero. The Control.GotFocus event handler then returned, and NativeWindow.Callback finished handling the WM_ACTIVATE message.

NativeWindow.Callback then received the 0x2 (WM_DESTROY) and 0x82 (WM_NCDESTROY) messages. WM_NCDESTROY caused it to call ReleaseHandle(false), which zeroed NativeWindow.Handle but did not change TimerNativeWindow._timerID. The TimerNativeWindow was now in an invalid state as NativeWindow.Handle was zero but TimerNativeWindow._timerID was nonzero. Finally, Timer.set_Enabled returned and the TimerNativeWindow was left in the invalid state.

Later, the application attempted to restart the timer again, by setting Timer.Enabled = false and then Timer.Enabled = true. This however had no effect:

- Assigning Timer.Enabled = false had no effect because TimerNativeWindow.StopTimer detected that Handle was zero.
- Assigning Timer.Enabled = true had no effect because TimerNativeWindow.StartTimer detected that _timerID was not zero.

The timer was thus irreversibly stuck.

**Expected behavior:**
Either prevent the timer from getting stuck if it is reentrantly disabled and enabled, or at least make the timer work again if the application assigns Timer.Enabled = true after the reentrancy has finished.

**Minimal repro:**
Currently no repro, because I don't know how to cause NativeWindow.Callback to receive a WM_ACTIVATE message while DestroyWindow is destroying the message-only window of the timer.

**Comment by dreddy-work** [comment]
@KalleOlaviNiemitalo , can you provide a sample app to debug this issue on our end?

**Comment by KalleOlaviNiemitalo** [comment]
I cannot provide a sample app. Although the issue repeatedly occurred for one user, I was never able to reproduce it when I used the app. We took a memory dump from the user's process after the timer had got stuck, and I found the invalid state in the dump. I then changed the app to hook the window messages of the TimerNativeWindow (by locating the window handle by reflection and creating another NativeWindow instance for it) and log the window handle, timer ID, and managed stack trace on each message. The log then revealed the reentrancy.

I understand it is difficult to fix the problem reliably if the fix cannot be tested. Perhaps this will have to wait until someone explains how it was possible for WM_ACTIVATE to be received during DestroyWindow.

**Comment by dreddy-work** [comment]
@KalleOlaviNiemitalo , thank you for adding details here. Next t time when this happen, would you mind sharing it via Visual Studio feedback portal so that we get the dumps and other info?

**Comment by KalleOlaviNiemitalo** [comment]
I already changed the app to detect if Timer.Enabled is about to be assigned reentrantly, and to postpone those assignments until the outer assignment finishes. This works around the problem. So I don't think there will be an opportunity for more memory dumps.

**Comment by dreddy-work** [comment]
@KalleOlaviNiemitalo thank you for updating us on the workaround. In this case, we will be closing this until we hear again and get some consistent repro steps.
