### ISSUE TITLE
Setting InvariantGlobalization to true causes exception

### ISSUE THREAD

**Issue by bodrick** [dotnet/winforms#6797]
* .NET Core Version: 
Host (useful for support):
  Version: 6.0.2
  Commit:  839cdfb0ec

**Problem description:**
Setting InvariantGlobalization to true causes exception.

[07:58:38.1898548] Processed 'System.Windows.Forms' in 00:00:00.0003725
[07:58:38.2018540] Added 'System.Windows.Forms'
[07:58:38.2028554] Loaded System in 00:00:00.0000114 [thread 53]
[07:58:38.2028554] Processed 'System' in 00:00:00.0004680
[07:58:38.2158547] Added 'System'
[07:58:38.2168556] Loaded System.Drawing in 00:00:00.0000145 [thread 13]
[07:58:38.2168556] Processed 'System.Drawing' in 00:00:00.0000513
[07:58:38.2178543] Added 'System.Drawing'
[07:58:38.2178543] Loaded System.Design in 00:00:00.0000086 [thread 13]
[07:58:38.2188550] Processed 'System.Design' in 00:00:00.0002857
[07:58:38.2248513] Creating VSCodeDomDesignerLoader
[07:58:38.2278490] Added 'System.Design'
[07:58:38.2278490] Loaded System.Drawing.Design in 00:00:00.0000144 [thread 51]
[07:58:38.2278490] Processed 'System.Drawing.Design' in 00:00:00.0000176
[07:58:38.2288517] Added 'System.Drawing.Design'
[07:58:38.5528534] [Thread 1] Creating design-time ITypeResolutionService.
[07:58:38.6098556] Start processing enqueued assemblies
[07:58:38.6098556] Loaded Microsoft.WinForms.DesignTools.Protocol in 00:00:00.0000129 [thread 49]
[07:58:38.6108563] Processed 'Microsoft.WinForms.DesignTools.Protocol' in 00:00:00.0015006
[07:58:38.6138555] Added 'Microsoft.WinForms.DesignTools.Protocol'
[07:58:38.6138555] Loaded Microsoft.WinForms.DesignTools.Client in 00:00:00.0000134 [thread 49]
[07:58:38.6388530] Processed 'Microsoft.WinForms.DesignTools.Client' in 00:00:00.0253481
[07:58:38.6398528] Added 'Microsoft.WinForms.DesignTools.Client'
[07:58:38.7588511] [Thread 55] Launching server...
[07:58:39.6368576] [WinFormsApp1]: Preparing shadow cache folder
[07:58:39.6398587] [WinFormsApp1]: Copying design tools server common files from: 'c:\program files\microsoft visual studio\2022\enterprise\common7\ide\commonextensions\microsoft\windows.forms\DesignToolsServer\Common'
[07:58:39.7878600] [WinFormsApp1]: Copying design tool server platform-specific files from: 'c:\program files\microsoft visual studio\2022\enterprise\common7\ide\commonextensions\microsoft\windows.forms\DesignToolsServer\x64'
[07:58:39.7938572] [WinFormsApp1]: Copying 'C:\Development\Personal\WinFormsApp1\obj\Debug\net6.0-windows\WinFormsApp1.designer.deps.json' to 'DesignToolsServer.deps.json'
[07:58:39.7988570] [WinFormsApp1]: Copying 'C:\Development\Personal\WinFormsApp1\obj\Debug\net6.0-windows\WinFormsApp1.designer.runtimeconfig.json' to 'DesignToolsServer.runtimeconfig.json'
[07:58:39.8448622] [WinFormsApp1]: Launching design tools server process...
[07:58:40.0698592] [WinFormsApp1]: info: Design Tools Server[0]
[07:58:40.0698592] [WinFormsApp1]:       Failed to launch design tools server process process
[07:58:40.0778643] [WinFormsApp1]: fail: Design Tools Server[0]
[07:58:40.0778643] [WinFormsApp1]:       System.Globalization.CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'culture')
[07:58:40.0778643] [WinFormsApp1]:       1033 (0x0409) is an invalid culture identifier.
[07:58:40.0778643] [WinFormsApp1]:          at System.Globalization.CultureData.GetCultureData(Int32 culture, Boolean bUseUserOverride)
[07:58:40.0778643] [WinFormsApp1]:          at System.Globalization.CultureInfo..ctor(Int32 culture, Boolean useUserOverride)
[07:58:40.0778643] [WinFormsApp1]:          at System.Globalization.CultureInfo..ctor(Int32 culture)
[07:58:40.0778643] [WinFormsApp1]:          at Microsoft.DotNet.DesignTools.Server.Program.<>c__DisplayClass2_0.<<Main>b__1>d.MoveNext()

WinFormsCache with flag set to true: https://github.com/bodrick/WinFormsApp1/blob/main/FlagTrue.7z
WinFormsCache without flag : https://github.com/bodrick/WinFormsApp1/blob/main/NotSet.7z

**Expected behavior:**
WinForm renders correctly

**Minimal repro:**
(https://github.com/bodrick/WinFormsApp1)

**Comment by dreddy-work** [comment]
@Shyam-Gupta , can you take a look at this and see if this is something that is already being tracked?

**Comment by Shyam-Gupta** [comment]
Seems related to VS locale Id changes. Requesting @RussKie to take a look.

**Comment by RussKie** [comment]
I confirm the issue is caused by `<InvariantGlobalization>true</InvariantGlobalization>` in the csproj. As an immediate workaround, please unset this flag, remove \bin and \obj folders, and rebuild the project.

**Comment by RussKie** [comment]
Thank you for the sample. I have a fix that will go out in 17.2 (hopefully in Preview 3).

**Comment by RussKie** [comment]
The fix will go out in 17.2 Preview3.
