### ISSUE TITLE
System.Runtime.InteropServices.MarshalDirectiveException pops up when executing MetaFile automation case

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#7099]
### .NET version

**.Net 7.0 SDK:** 7.0.100-preview.5.22227.7

### Did it work in .NET Framework?

No

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, it is a regression issue, cannot repro in .Net 6.0

### Issue description

System.Runtime.InteropServices.MarshalDirectiveException
  HResult=0x80131535
  Message=Cannot marshal 'parameter #5': Cannot marshal managed types when the runtime marshalling system is disabled.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

  This exception was originally thrown at this call stack:
    [External Code]
    WinFormsApp12.Form1.Form1() in Form1.cs
    WinFormsApp12.Program.Main() in Program.cs

### Steps to reproduce

[WinFormsApp12.zip](https://github.com/dotnet/winforms/files/8582038/WinFormsApp12.zip)
1. Put tested application to the C:\Test folder
2. Open that test application, build and run

**Comment by Olina-Zhang** [comment]
It seems not a Winforms issue, please triage

**Comment by RussKie** [comment]
@kant2002 could this be a fallout from of the comwrapper related changes?

**Comment by kant2002** [comment]
I think not. `Cannot marshal managed types when the runtime marshalling system is disabled.` this message indicates to me that `DisableRuntimeMarshalling` attribute applied to `System.Windows.Forms` assembly. I would guess that SDK automatically insert that attribute for some reasons (trimming for example).

LibraryImportGenerator would solve this kind of issues one and for all.

**Comment by kant2002** [comment]
Exception happens which I see when run with Debug mode is following
 
```
System.Runtime.InteropServices.ExternalException: 'A generic error occurred in GDI+.'
   at System.Drawing.Imaging.Metafile..ctor(String filename)
   at WinFormsApp12.Form1..ctor() in C:\Users\kant\Downloads\WinFormsApp121\WinFormsApp12\Form1.cs:line 12
   at WinFormsApp12.Program.Main() in C:\Users\kant\Downloads\WinFormsApp121\WinFormsApp12\Program.cs:line 14
```
```
>dotnet --info
.NET SDK:
 Version:   7.0.100-preview.5.22227.8
 Commit:    36f0f64cf5
```

**Comment by kant2002** [comment]
Oops, sorry. I repro reported error
```
This exception was originally thrown at this call stack:
    System.Drawing.SafeNativeMethods.Gdip.GdipEnumerateMetafileDestPointI(System.Runtime.InteropServices.HandleRef, System.Runtime.InteropServices.HandleRef, ref System.Drawing.Point, System.Drawing.Graphics.EnumerateMetafileProc, System.IntPtr, System.Runtime.InteropServices.HandleRef)
    System.Drawing.Graphics.EnumerateMetafile(System.Drawing.Imaging.Metafile, System.Drawing.Point, System.Drawing.Graphics.EnumerateMetafileProc, System.IntPtr, System.Drawing.Imaging.ImageAttributes)
    System.Drawing.Graphics.EnumerateMetafile(System.Drawing.Imaging.Metafile, System.Drawing.Point, System.Drawing.Graphics.EnumerateMetafileProc)
    WinFormsApp12.Form1.Form1() in Form1.cs
    WinFormsApp12.Program.Main() in Program.cs
```

but again, I see that issue should belongs to dotnet/runtime

**Comment by kant2002** [comment]
This is simplest repro
```
using System.Drawing.Imaging;

var b = new Bitmap(1000, 1000);
Graphics g = Graphics.FromImage(b);

Metafile metafile = new Metafile(@"FLOWER.WMF");
Point pt = new Point(0, 0);

g.EnumerateMetafile(metafile, pt, new Graphics.EnumerateMetafileProc(PlayMetafileRecordCallback));
    static Boolean PlayMetafileRecordCallback(EmfPlusRecordType recordType, int flags, int dataSize, IntPtr data, PlayRecordCallback callbackData)
{
    return true;
}

```

**Comment by RussKie** [comment]
Thank you @kant2002 for the investigation.
