### ISSUE TITLE
[dotnet-sdk-7.0.100-preview.5.22257.3] WinForm Apps thrown Object reference not set to an instance of an object when setting values to Label.Text

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/winforms#7159]
### .NET version

7.0.100-preview.5.22257.3

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

**Verify Scenarios:**
1). Windows10 RS5 x64+dotnet-sdk-7.0.100-preview.5.22257.3: Fail
2). Windows10 RS5 x64+dotnet-sdk-7.0.100-preview.5.22258.1: Fail
3). Windows10 RS5 x64+dotnet-sdk-7.0.100-preview.4.22252.9: Pass

### Issue description

**Application Name**:  pomodoroflavors, HeroesPowerPlant, GameofLife
**OS:** Windows 10 RS5
**CPU:** X64
**.NET Build Number**: dotnet-sdk-7.0.100-preview.5.22257.3

When testing the above 3rd party apps against dotnet-sdk-7.0.100-preview.5.22257.3, it fails with "Object reference not set to an instance of an object" when setting values to Label.Text.

**Findings:**

1. If we set Text from Properties window, then change the Text value from button click event, it works fine.
2. If original text string is number and changed string is characters, or original text string is characters and changed string is number,  and the length should be same before and after change, the issue will appear.

**StackTrace from Application:**
See the end of this message for details on invoking
just-in-time (JIT) debugging instead of this dialog box.
```
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.Layout.DefaultLayout.GetAnchorDestination(IArrangedElement element, Rectangle displayRect, Boolean measureOnly)
   at System.Windows.Forms.Layout.DefaultLayout.LayoutAnchoredControls(IArrangedElement container)
   at System.Windows.Forms.Layout.DefaultLayout.TryCalculatePreferredSize(IArrangedElement container, Boolean measureOnly, Size& preferredSize)
   at System.Windows.Forms.Layout.DefaultLayout.LayoutCore(IArrangedElement container, LayoutEventArgs args)
   at System.Windows.Forms.Control.OnLayout(LayoutEventArgs levent)
   at System.Windows.Forms.Form.OnLayout(LayoutEventArgs levent)
   at System.Windows.Forms.Control.PerformLayout(LayoutEventArgs args)
   at System.Windows.Forms.Control.PerformLayout()
   at System.Windows.Forms.Control.ResumeLayout(Boolean performLayout)
   at System.Windows.Forms.Label.OnTextChanged(EventArgs e)
   at System.Windows.Forms.Control.set_Text(String value)
   at PomodoroDesktop.Pomodoro.UpdateCountdownOnScreen() in F:\Onboardapps\pomodoroflavors-main\pomodoroflavors-main\PomodoroDesktop\ResultProject\PomodoroDesktop\Pomodoro.cs:line 66
   at PomodoroDesktop.Pomodoro.StartCountdownTimer(Int32 minutesToCountdown) in F:\Onboardapps\pomodoroflavors-main\pomodoroflavors-main\PomodoroDesktop\ResultProject\PomodoroDesktop\Pomodoro.cs:line 42
   at PomodoroDesktop.Pomodoro.btnPomodoro_Click(Object sender, EventArgs e) in F:\Onboardapps\pomodoroflavors-main\pomodoroflavors-main\PomodoroDesktop\ResultProject\PomodoroDesktop\Pomodoro.cs:line 25
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

```

### Steps to reproduce

**Minimal Repro steps:**
**The machine only has 7.0.100-preview.5.22257.3 installed. The Demo project is attached.
[WinFormsDemo.zip](https://github.com/dotnet/winforms/files/8660697/WinFormsDemo.zip)
 **

1. Create a default WinForm App with Visual Studio and target the app to .NET 7.0
2. Drag a Label and a Button control to the form.
3. Double click the button and add below code in Form1.cs file: 
```
        public Form1()
        {
            InitializeComponent();
            label1.Text = "aaa";
        }

        private void button1_Click(object sender, EventArgs e)
        {
            label1.Text = "123";
        }
```

4. Press F5 to launch the app.
5. Click button.

**Expected Result:** 
The Label's Text content will become "123".

**Actual Result:**
It will throw Object reference not set to an instance exception. The stack trace shows:
```
   at System.Windows.Forms.Layout.DefaultLayout.GetAnchorDestination(IArrangedElement element, Rectangle displayRect, Boolean measureOnly)
```

@dotnet-actwx-bot @dotnet/compat

**Comment by RussKie** [comment]
@dreddy-work this likely relates to your recent work, please investigate.

**Comment by dreddy-work** [comment]
Yes it is and is in this preview only. I am working on it.

**Comment by Olina-Zhang** [comment]
Similar issue: https://github.com/dotnet/winforms/issues/7090

**Comment by Olina-Zhang** [comment]
Verified it in the latest .Net 7.0 build from main branch: 7.0.100-preview.5.22267.11, it is fixed:
![issue7159_fixed](https://user-images.githubusercontent.com/26474449/169002896-78529570-9107-43ff-977e-73c950c1b444.gif)

**Comment by Cassie-Li01** [comment]
Verified this issue on .NET SDK 7.0.100-preview.5.22305.3 TP, it is fixed. Gif as above.
