### ISSUE TITLE
VS2022: The process cannot access the file 'Microsoft.DotNet.DesignTools.Protocol.resources.dll' because it is being used by another process. 

### ISSUE THREAD

**Issue by kslynn** [dotnet/winforms#7270]
### Environment

Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.2.3

### .NET version

dotnet5

### Did this work in a previous version of Visual Studio and/or previous .NET release?

I don't know, I am new for this company, I got a new pc, and copy the solution from my collages

### Issue description

![WinFormDesignerError](https://user-images.githubusercontent.com/12741901/172525228-9af24397-35d5-4d86-8161-eed91a02b198.png)

this occors in my old solution, it's converted from dotnet4.6

it's ok if I open it at the very begining, but after I clicked the debug button to run the program, then switch to the solution, 

error happened as the file attached while I tried to open the winform in designer

I restarted the vs2022, the error is still there

I restarted my computer, the error is still there

I don't know how to deal with it.

**Comment by kslynn** [comment]
nstances of this error (1)  
 
1.   Hide Call Stack 
 
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
at System.IO.File.OpenFile(String path, FileAccess access, SafeFileHandle& handle)
at System.IO.File.SetLastWriteTimeUtc(String path, DateTime lastWriteTimeUtc)
at System.IO.FileSystemInfo.set_LastWriteTimeUtc(DateTime value)
at Microsoft.WinForms.Utilities.Shared.ShadowCacheFolder.CopyIfNewer(FileInfo source, FileInfo target)
at Microsoft.WinForms.Utilities.Shared.ShadowCacheFolder.<>c__DisplayClass7_0.b__0()
at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.WinForms.Utilities.Shared.ShadowCacheFolder.d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Microsoft.WinForms.Utilities.Shared.ShadowCacheFolder.d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.WinForms.Utilities.Shared.ShadowCacheFolder.d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.DotNet.DesignTools.Client.Host.ServerLayout.d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.DotNet.DesignTools.Client.Host.ServerLayout.d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.DotNet.DesignTools.Client.Host.ServerProcess.d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.DotNet.DesignTools.Client.Host.ServerHostFactory.d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.DotNet.DesignTools.Client.DesignToolsClientLoader.d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.DotNet.DesignTools.Client.DesignToolsClientLoader.<>c__DisplayClass24_1.<<-ctor>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.DotNet.DesignTools.Client.DesignToolsClientLoader.d__26.MoveNext()

**Comment by RussKie** [comment]
@Shyam-Gupta can you please have a look?

**Comment by RussKie** [comment]
@kslynn can you please attach the full verbose log? See https://aka.ms/winforms/designer/troubleshooting.

**Comment by merriemcgaw** [comment]
@Shyam-Gupta to investigate once we have the logs.

**Comment by kslynn** [comment]
Yes, the log context is as the below:

[09:47:13.4044430] Added 'System'
[09:47:13.4044430] Loaded System.Drawing in 00:00:00.0000076 [thread 28]
[09:47:13.4044430] Processed 'System.Drawing' in 00:00:00.0000799
[09:47:13.4054399] Added 'System.Drawing'
[09:47:13.4054399] Loaded System.Design in 00:00:00.0000049 [thread 28]
[09:47:13.4273666] Creating VsDesignerLoader
[09:47:13.4592598] Processed 'System.Design' in 00:00:00.0531284
[09:47:13.4662365] Added 'System.Design'
[09:47:13.4662365] Loaded System.Drawing.Design in 00:00:00.0000090 [thread 28]
[09:47:13.4672331] Processed 'System.Drawing.Design' in 00:00:00.0000777
[09:47:13.4672331] Added 'System.Drawing.Design'
[09:47:13.5273875] [Thread 1] Creating design-time ITypeResolutionService.
[09:47:13.5787367] Current VS Version = 17.0
[09:47:13.5797358] Start processing enqueued assemblies
[09:47:13.5797358] Loaded Microsoft.WinForms.DesignTools.Protocol in 00:00:00.0000084 [thread 19]
[09:47:13.5807341] Processed 'Microsoft.WinForms.DesignTools.Protocol' in 00:00:00.0006629
[09:47:13.5827257] Added 'Microsoft.WinForms.DesignTools.Protocol'
[09:47:13.5827257] Loaded Microsoft.WinForms.DesignTools.Client in 00:00:00.0000064 [thread 19]
[09:47:13.5987672] Processed 'Microsoft.WinForms.DesignTools.Client' in 00:00:00.0159540
[09:47:13.5999860] Added 'Microsoft.WinForms.DesignTools.Client'
[09:47:13.6711168] [Thread 43] Launching server...
[09:47:14.8575378] Shadow cache base directory: C:\Users\housui\AppData\Local\Microsoft\VisualStudio\17.0_fdad75d7\WinFormsDesigner
[09:47:14.8619558] [LuK.PMI.Components.Alds.UI.Views]: Preparing shadow cache folder
[09:47:14.8639489] [LuK.PMI.Components.Alds.UI.Views]: Copying design tools server common files from: 'c:\program files\microsoft visual studio\2022\professional\common7\ide\commonextensions\microsoft\windows.forms\DesignToolsServer\Common'
[09:47:14.8814528] System.IO.IOException: The process cannot access the file '\\?\C:\Users\housui\AppData\Local\Microsoft\VisualStudio\17.0_fdad75d7\WinFormsDesigner\nc1cpnzt.ky4\cs\Microsoft.DotNet.DesignTools.Server.resources.dll' because it is being used by another process.
                      at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
                      at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
                      at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
                      at System.IO.File.OpenFile(String path, FileAccess access, SafeFileHandle& handle)
                      at System.IO.File.SetLastWriteTimeUtc(String path, DateTime lastWriteTimeUtc)
                      at System.IO.FileSystemInfo.set_LastWriteTimeUtc(DateTime value)
                      at Microsoft.WinForms.Utilities.Shared.ShadowCacheFolder.CopyIfNewer(FileInfo source, FileInfo target)
                      at Microsoft.WinForms.Utilities.Shared.ShadowCacheFolder.<>c__DisplayClass7_0.<CopyDirectoryAsync>b__0()
                      at System.Threading.Tasks.Task.Execute()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.WinForms.Utilities.Shared.ShadowCacheFolder.<CopyDirectoryAsync>d__7.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at Microsoft.WinForms.Utilities.Shared.ShadowCacheFolder.<CopyDirectoryAsync>d__7.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.WinForms.Utilities.Shared.ShadowCacheFolder.<CacheDirectoryAsync>d__5.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.DotNet.DesignTools.Client.Host.ServerLayout.<CopyServerToShadowCacheAsync>d__14.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.DotNet.DesignTools.Client.Host.ServerLayout.<CreateAsync>d__10.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.DotNet.DesignTools.Client.Host.ServerProcess.<CreateAsync>d__21.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.DotNet.DesignTools.Client.Host.ServerHostFactory.<CreateHostAsync>d__7.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.DotNet.DesignTools.Client.DesignToolsClientLoader.<CreateClientAsync>d__28.MoveNext()

                   For information on how to troubleshoot the designer refer to the guide at https://aka.ms/winforms/designer/troubleshooting.
[09:47:15.0077081] Cannot update selection in server process as Session is not connected.

                   For information on how to troubleshoot the designer refer to the guide at https://aka.ms/winforms/designer/troubleshooting.

**Comment by kslynn** [comment]
I have found something difference while I tried to skipped the error
I built a new solution which had contained a dotnet5 winform apps, and at the very beginning, it gave me the error of "Microsoft.DotNet.DesignTools.Server.resources.dll is used by another process"
, I could not open winform in dotnet5 what ever I tried, 
but, 
things changed after I added a new winform app in dotnet6, the dotnet6-winform can be opened normally, 
and after I restarted the solution, exiting things happend, the winform in dotnet5 can also be opened normally.

**Comment by kslynn** [comment]
It's also good at the dotnet 4.8

**Comment by kslynn** [comment]
Most important I think is , you need to start the vs as an administrator

**Comment by RussKie** [comment]
The fix is expected to be available in 17.3 Preview 3.

**Comment by kslynn** [comment]
Thats's great!
I am looking forward to it

**Comment by Shyam-Gupta** [comment]
@kslynn Thank you for reporting this issue. Fix for this bug will also be available in next 17.2 servicing update.

cc: @merriemcgaw

**Comment by kslynn** [comment]
@Shyam-Gupta Thank you sir,  it will be a great help for us.
