### ISSUE TITLE
ToolStripTextBoxControlAccessibleObject_Default_Role_IsExpected Failure

### ISSUE THREAD

**Issue by lonitra** [dotnet/winforms#7471]
### Test

System.Windows.Forms.Tests.ToolStripTextBox_ToolStripTextBoxControlAccessibleObjectTests.ToolStripTextBoxControlAccessibleObject_Default_Role_IsExpected(createControl: True, expectedRole: Text)

### Issue description

```
Error message
Assert.Equal() Failure\r\nExpected: Text\r\nActual:   Client


Stack trace
   at System.Windows.Forms.Tests.ToolStripTextBox_ToolStripTextBoxControlAccessibleObjectTests.ToolStripTextBoxControlAccessibleObject_Default_Role_IsExpected(Boolean createControl, AccessibleRole expectedRole) in /_/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTextBox.ToolStripTextBoxControlAccessibleObjectTests.cs:line 107
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)```

**Comment by RussKie** [comment]
We track repeated test failures with [Runfo app](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E14+definition%3A267+kind%3Arolling#build), which automatically updates the tracking issues (e.g., https://github.com/dotnet/winforms/issues/7365).
