### ISSUE TITLE
DragEnter_Set_DropImageType_Message_MessageReplacementToken_ReturnsExptected fails intermittently

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/winforms#7547]
### Test

System.Windows.Forms.UITests.DragDropTests.DragEnter_Set_DropImageType_Message_MessageReplacementToken_ReturnsExptected

### Issue description

Failed on debug x64:

```
Error message
Assert.InRange() Failure\r\nRange:  (287 - 289)\r\nActual: 208

Stack trace
   at System.Windows.Forms.UITests.ControlTestBase.MoveMouseAsync(Form window, Point point, Boolean assertCorrectLocation) in /_/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs:line 154
   at System.Windows.Forms.UITests.ControlTestBase.MoveMouseToControlAsync(Control control) in /_/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs:line 111
   at System.Windows.Forms.UITests.DragDropTests.<DragEnter_Set_DropImageType_Message_MessageReplacementToken_ReturnsExptected>b__4_1(DragDropForm form) in /_/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DragDropTests.cs:line 91
   at System.Windows.Forms.UITests.ControlTestBase.<>c__DisplayClass29_0`1.<<RunFormWithoutControlAsync>b__0>d.MoveNext() in /_/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs:line 277
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.Threading.JoinableTask.JoinAsync(CancellationToken cancellationToken)
   at System.Windows.Forms.UITests.ControlTestBase.RunFormWithoutControlAsync[TForm](Func`1 createForm, Func`2 testDriverAsync) in /_/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs:line 295
   at System.Windows.Forms.UITests.DragDropTests.DragEnter_Set_DropImageType_Message_MessageReplacementToken_ReturnsExptected() in /_/src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DragDropTests.cs:line 56
--- End of stack trace from previous location ---
```

**Comment by willibrandon** [comment]
Finicky. I'll see if I kind find a better way to move the mouse.
