### ISSUE TITLE
Everytime I create a new project the designer breaks

### ISSUE THREAD

**Issue by Chello1801** [dotnet/winforms#7755]
### Environment

Visual Studio 2022 17.3.3

### .NET version

I use NET 6.0, but it also affected 3.1 & 5.0.

### Did this work in a previous version of Visual Studio and/or previous .NET release?

It did work in the past, but suddenly i just get this error that breaks the form designer.

### Issue description

In every project I create, the form designer just doesnt work.
This is the error it gives me:

```
at Microsoft.DotNet.DesignTools.Client.Host.ProjectInfoProvider.NetCore.d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.DotNet.DesignTools.Client.Host.ProjectInfoProvider.d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.DotNet.DesignTools.Client.Host.ServerHostFactory.d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.DotNet.DesignTools.Client.DesignToolsClientLoader.d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.DotNet.DesignTools.Client.DesignToolsClientLoader.<>c__DisplayClass25_1.<<-ctor>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.DotNet.DesignTools.Client.DesignToolsClientLoader.d__27.MoveNext() 
```

### Steps to reproduce

Create any WinForms project, doesnt matter if its NET 3.1, 5.0 or 6.0.

![Screenshot (75)](https://user-images.githubusercontent.com/107318006/189385781-90266a43-95f6-4d78-b104-c5ce6a114e92.png)

**Comment by Chello1801** [comment]
´´´
[08:32:39.204060] info: Creating VsDesignerLoader
[08:32:42.852334] info: [Thread 1] Creating design-time ITypeResolutionService.
[08:32:44.264804] info: Start processing enqueued assemblies
[08:32:44.265802] trce: Loaded Microsoft.WinForms.DesignTools.Protocol in 00:00:00.0000255 [thread 72]
[08:32:44.436715] trce: Processed 'Microsoft.WinForms.DesignTools.Protocol' in 00:00:00.1714324
[08:32:44.441766] info: Added 'Microsoft.WinForms.DesignTools.Protocol'
[08:32:44.441766] trce: Loaded Microsoft.WinForms.DesignTools.Client in 00:00:00.0000120 [thread 72]
[08:32:44.615009] trce: Processed 'Microsoft.WinForms.DesignTools.Client' in 00:00:00.1727493
[08:32:44.617011] info: Added 'Microsoft.WinForms.DesignTools.Client'
[08:32:46.097993] info: Visual Studio culture: en-US (0x0409)
[08:32:46.097993] info: [Thread 44] Launching server...
[08:32:46.105984] info: Is processor architecture ARM64: False
[08:32:49.990985] trce: Processed 'System.Design' in 00:00:04.0487542
[08:32:50.016986] info: Added 'System.Design'
[08:32:50.016986] trce: Loaded System.Drawing.Design in 00:00:00.0000186 [thread 53]
[08:32:50.019983] trce: Processed 'System.Drawing.Design' in 00:00:00.0031940
[08:32:50.020984] info: Added 'System.Drawing.Design'
[08:32:53.511958] fail: OutputGroupService didn't return output group DesignerRuntimeImplementationProjectOutputGroup.

                        For information on how to troubleshoot the designer refer to the guide at https://aka.ms/winforms/designer/troubleshooting.
[08:32:53.543171] fail: Could not retrieve DesignerRuntimeImplementationProjectOutputGroup for current project.

                        For information on how to troubleshoot the designer refer to the guide at https://aka.ms/winforms/designer/troubleshooting.
[08:32:53.811171] fail: System.InvalidOperationException: Designer load encountered an error. Please ensure that the project can be built successfully.
                           at Microsoft.DotNet.DesignTools.Client.Host.ProjectInfoProvider.NetCore.<GetNetCoreProjectInfoAsync>d__6.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at Microsoft.DotNet.DesignTools.Client.Host.ProjectInfoProvider.<GetProjectInfoAsync>d__9.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at Microsoft.DotNet.DesignTools.Client.Host.ServerHostFactory.<CreateHostAsync>d__8.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at Microsoft.DotNet.DesignTools.Client.DesignToolsClientLoader.<CreateClientAsync>d__29.MoveNext()

                        For information on how to troubleshoot the designer refer to the guide at https://aka.ms/winforms/designer/troubleshooting.
[08:32:54.277639] warn: Cannot update selection in server process as Session is not connected.
´´´

**Comment by Chello1801** [comment]
> Please follow https://aka.ms/winforms/designer/troubleshooting and provide the verbose log.

```
[08:32:39.204060] info: Creating VsDesignerLoader
[08:32:42.852334] info: [Thread 1] Creating design-time ITypeResolutionService.
[08:32:44.264804] info: Start processing enqueued assemblies
[08:32:44.265802] trce: Loaded Microsoft.WinForms.DesignTools.Protocol in 00:00:00.0000255 [thread 72]
[08:32:44.436715] trce: Processed 'Microsoft.WinForms.DesignTools.Protocol' in 00:00:00.1714324
[08:32:44.441766] info: Added 'Microsoft.WinForms.DesignTools.Protocol'
[08:32:44.441766] trce: Loaded Microsoft.WinForms.DesignTools.Client in 00:00:00.0000120 [thread 72]
[08:32:44.615009] trce: Processed 'Microsoft.WinForms.DesignTools.Client' in 00:00:00.1727493
[08:32:44.617011] info: Added 'Microsoft.WinForms.DesignTools.Client'
[08:32:46.097993] info: Visual Studio culture: en-US (0x0409)
[08:32:46.097993] info: [Thread 44] Launching server...
[08:32:46.105984] info: Is processor architecture ARM64: False
[08:32:49.990985] trce: Processed 'System.Design' in 00:00:04.0487542
[08:32:50.016986] info: Added 'System.Design'
[08:32:50.016986] trce: Loaded System.Drawing.Design in 00:00:00.0000186 [thread 53]
[08:32:50.019983] trce: Processed 'System.Drawing.Design' in 00:00:00.0031940
[08:32:50.020984] info: Added 'System.Drawing.Design'
[08:32:53.511958] fail: OutputGroupService didn't return output group DesignerRuntimeImplementationProjectOutputGroup.

                        For information on how to troubleshoot the designer refer to the guide at https://aka.ms/winforms/designer/troubleshooting.
[08:32:53.543171] fail: Could not retrieve DesignerRuntimeImplementationProjectOutputGroup for current project.

                        For information on how to troubleshoot the designer refer to the guide at https://aka.ms/winforms/designer/troubleshooting.
[08:32:53.811171] fail: System.InvalidOperationException: Designer load encountered an error. Please ensure that the project can be built successfully.
                           at Microsoft.DotNet.DesignTools.Client.Host.ProjectInfoProvider.NetCore.<GetNetCoreProjectInfoAsync>d__6.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at Microsoft.DotNet.DesignTools.Client.Host.ProjectInfoProvider.<GetProjectInfoAsync>d__9.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at Microsoft.DotNet.DesignTools.Client.Host.ServerHostFactory.<CreateHostAsync>d__8.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at Microsoft.DotNet.DesignTools.Client.DesignToolsClientLoader.<CreateClientAsync>d__29.MoveNext()

                        For information on how to troubleshoot the designer refer to the guide at https://aka.ms/winforms/designer/troubleshooting.
[08:32:54.277639] warn: Cannot update selection in server process as Session is not connected.
```

**Comment by RussKie** [comment]
@Shyam-Gupta is there anything that rings a bell?

**Comment by Shyam-Gupta** [comment]
@Chello1801 Requesting you to share following information:

- How is the project getting created? Using Visual Studio or using dotnet.exe CLI?
- Once the project gets created, are you able to build it using Visual Studio without any error?
- Does this issue also reproes for a WPF .NET project?

**Comment by Chello1801** [comment]
while i was trying to build the project a error occurred telling me to restore the nuget packages, so i did that and now it works again.

thanks i guess

**Comment by Chello1801** [comment]
while i was trying to build the project a error occurred telling me to restore the nuget packages, so i did that and now it works again.

thanks i guess
