### ISSUE TITLE
System.NullReferenceException when using System.Speech 7.0.0-rc.1.22426.10 from Windows Forms 

### ISSUE THREAD

**Issue by Shkyrockett** [dotnet/winforms#7780]
### .NET version

.NET 7.0.0

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

.NET 6.0.0

### Issue description

When trying to use the latest version of [System.Speech](https://www.nuget.org/packages/System.Speech) from Windows Forms, it throws a System.NullReferenceException while trying to access the SpeechSynthesizer class.  

### Steps to reproduce

Run the attached project and click the button.

```csharp
        private void Button_Click(object sender, EventArgs e)
        {
            label.Text = string.Empty;
            using var speech = new SpeechSynthesizer();

            // System.Speech 7.0.0-rc.1.22426.10 throws System.NullReferenceException exception here.
            speech.SetOutputToDefaultAudioDevice();
            speech.SelectVoiceByHints(VoiceGender.Female);
            speech.SpeakProgress += (sender, e) => { label.Text += $"{e.Text} "; };

            speech.Speak("This is a test of the SpeechSynthesizer class.");

            label.Text += "\r\nFinished speaking...\r\n";
        }
```

Expected: The speech synthesizer should read out the contents of the string.

Actual: Accessing the newly created speech SpeechSynthesizer object throws a System.NullReferenceException exception.

Repro project:
[WinFormsSpeechRepro.zip](https://github.com/dotnet/winforms/files/9570983/WinFormsSpeechRepro.zip)

**Comment by RussKie** [comment]
I am afraid I can't repro the issue, I can hear a female voice reading the text.
![image](https://user-images.githubusercontent.com/4403806/190294662-0ce42585-45e2-4dbe-9d8f-606d097ac9a9.png)

Please provide the errors and the stack trace you're getting.

**Comment by Shkyrockett** [comment]
```text
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=System.Speech
  StackTrace:
   at Interop.WinMM.WAVEOUTCAPS.Marshaller.Native..ctor(WAVEOUTCAPS managed)
   at Interop.WinMM.WAVEOUTCAPS.Marshaller.ConvertToUnmanaged(WAVEOUTCAPS managed)
   at Interop.WinMM.waveOutGetDevCaps(IntPtr uDeviceID, WAVEOUTCAPS& caps, Int32 cbwoc)
   at System.Speech.Internal.Synthesis.AudioDeviceOut.GetDeviceName(Int32 deviceId, String& prodName)
   at System.Speech.Internal.Synthesis.AudioDeviceOut.GetDevicedId(String name)
   at System.Speech.Internal.ObjectTokens.SAPICategories.DefaultDeviceOut()
   at System.Speech.Internal.Synthesis.VoiceSynthesis..ctor(WeakReference speechSynthesizer)
   at System.Speech.Synthesis.SpeechSynthesizer.get_VoiceSynthesizer()
   at System.Speech.Synthesis.SpeechSynthesizer.SetOutputToNull()
   at System.Speech.Synthesis.SpeechSynthesizer.SetOutputStream(Stream stream, SpeechAudioFormatInfo formatInfo, Boolean headerInfo, Boolean closeStreamOnExit)
   at System.Speech.Synthesis.SpeechSynthesizer.SetOutputToDefaultAudioDevice()
   at WinFormsSpeechRepro.SpeechForm.Button_Click(Object sender, EventArgs e) in C:\Repos\shkyrockett\WinFormsSpeechRepro\WinFormsSpeechRepro\SpeechForm.cs:line 30
```

**Comment by Shkyrockett** [comment]
Capture of the exception from a release build:
```text
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Interop.WinMM.WAVEOUTCAPS.Marshaller.Native..ctor(WAVEOUTCAPS managed)
   at Interop.WinMM.WAVEOUTCAPS.Marshaller.ConvertToUnmanaged(WAVEOUTCAPS managed)
   at Interop.WinMM.waveOutGetDevCaps(IntPtr uDeviceID, WAVEOUTCAPS& caps, Int32 cbwoc)
   at System.Speech.Internal.Synthesis.AudioDeviceOut.GetDeviceName(Int32 deviceId, String& prodName)
   at System.Speech.Internal.Synthesis.AudioDeviceOut.GetDevicedId(String name)
   at System.Speech.Internal.ObjectTokens.SAPICategories.DefaultDeviceOut()
   at System.Speech.Internal.Synthesis.VoiceSynthesis..ctor(WeakReference speechSynthesizer)
   at System.Speech.Synthesis.SpeechSynthesizer.get_VoiceSynthesizer()
   at System.Speech.Synthesis.SpeechSynthesizer.SetOutputToNull()
   at System.Speech.Synthesis.SpeechSynthesizer.SetOutputStream(Stream stream, SpeechAudioFormatInfo formatInfo, Boolean headerInfo, Boolean closeStreamOnExit)
   at System.Speech.Synthesis.SpeechSynthesizer.SetOutputToDefaultAudioDevice()
   at WinFormsSpeechRepro.SpeechForm.Button_Click(Object sender, EventArgs e) in C:\Repos\shkyrockett\WinFormsSpeechRepro\WinFormsSpeechRepro\SpeechForm.cs:line 30
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.42610
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.0-rc.1.22426.10/System.Private.CoreLib.dll
----------------------------------------
WinFormsSpeechRepro
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Repos/shkyrockett/WinFormsSpeechRepro/WinFormsSpeechRepro/bin/Release/net7.0-windows/WinFormsSpeechRepro.dll
----------------------------------------
System.Runtime
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.42610
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.0-rc.1.22426.10/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.42604
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.0-rc.1.22427.1/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.42610
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.0-rc.1.22426.10/System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.42604
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.0-rc.1.22427.1/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.42610
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.0-rc.1.22426.10/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.42610
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.0-rc.1.22426.10/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.42610
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.0-rc.1.22426.10/System.Collections.Specialized.dll
----------------------------------------
System.Threading
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.42610
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.0-rc.1.22426.10/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.42610
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.0-rc.1.22426.10/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.42610
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.0-rc.1.22426.10/System.Collections.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.42610
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.0-rc.1.22427.1/System.Drawing.Common.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.42610
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.0-rc.1.22426.10/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.42610
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.0-rc.1.22426.10/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.42610
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.0-rc.1.22426.10/System.Threading.Thread.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 7.0.22.42604
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.0-rc.1.22427.1/Accessibility.dll
----------------------------------------
System.Memory
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.42610
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.0-rc.1.22426.10/System.Memory.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.42610
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.0-rc.1.22426.10/System.Numerics.Vectors.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.42610
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/7.0.0-rc.1.22427.1/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.42610
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.0-rc.1.22426.10/System.Collections.NonGeneric.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.42610
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.0-rc.1.22426.10/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.42610
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.0-rc.1.22426.10/System.ComponentModel.dll
----------------------------------------
System.Speech
    Assembly Version: 4.0.0.0
    Win32 Version: 7.0.22.42610
    CodeBase: file:///C:/Repos/shkyrockett/WinFormsSpeechRepro/WinFormsSpeechRepro/bin/Release/net7.0-windows/runtimes/win/lib/net7.0/System.Speech.dll
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.42610
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.0-rc.1.22426.10/System.Threading.ThreadPool.dll
----------------------------------------
Microsoft.Win32.Registry
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.42610
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.0-rc.1.22426.10/Microsoft.Win32.Registry.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.42610
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.0-rc.1.22426.10/System.Private.Uri.dll
----------------------------------------
System.Runtime.Loader
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.42610
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.0-rc.1.22426.10/System.Runtime.Loader.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.42610
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.0-rc.1.22426.10/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.42610
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.0-rc.1.22426.10/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.42610
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.0-rc.1.22426.10/System.Collections.Immutable.dll
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.22.42610
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/7.0.0-rc.1.22426.10/System.Text.Encoding.Extensions.dll
----------------------------------------

************** JIT Debugging **************
```

**Comment by RussKie** [comment]
This looks like the problem with System.Speech and not Windows Forms.
