### ISSUE TITLE
"Index was outside the bounds of the array" pops up when setting the BackgroundImage/Icon property in PropertyGrid runtime

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#7850]
### .NET version

.Net 8.0 SDK build: 8.0.100-alpha.1.22476.24

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, It cannot repro in .Net Core 3.1, .Net 5.0/6.0./7.0, caused by PR: https://github.com/dotnet/winforms/pull/7828

### Issue description

"Index was outside the bounds of the array" pops up when calling openFileDialog with custom setting.
![image](https://user-images.githubusercontent.com/26474449/192468276-8b66a971-2faa-4d4c-b6e7-ab31a0e3cd80.png)
![image](https://user-images.githubusercontent.com/26474449/192468312-98a36138-65a8-4ff6-805b-3763271b8905.png)
**Call Stack:**
System.IndexOutOfRangeException
  HResult=0x80131508
  Message=Index was outside the bounds of the array.
  Source=System.Windows.Forms
  StackTrace:
   at System.Windows.Forms.FileDialog.GetFilterItems(String filter)
   at System.Windows.Forms.FileDialog.SetFileTypes(IFileDialog dialog)
   at System.Windows.Forms.FileDialog.OnBeforeVistaDialog(IFileDialog dialog)
   at System.Windows.Forms.FileDialog.TryRunDialogVista(IntPtr hWndOwner, Boolean& returnValue)
   at System.Windows.Forms.FileDialog.RunDialog(IntPtr hWndOwner)
   at System.Windows.Forms.CommonDialog.ShowDialog(IWin32Window owner)
   at System.Windows.Forms.CommonDialog.ShowDialog()
   at WinFormsApp28.Form1.button1_Click(Object sender, EventArgs e) in C:\Users\xxx\source\repos\WinFormsApp28\WinFormsApp28\Form1.cs:line 22
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.ButtonBase.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, WM msg, WPARAM wparam, LPARAM lparam)

### Steps to reproduce

Repro steps1:
1.	Create a Winforms .Net 8.0 application
2.	Add a propertyGrid to form designer
3.	Associate the Form to propertyGrid as a selected object.
4.	Build and run application
5.	Focus on BackgroundImage/Icon property in PropertyGrid, and try to set this property

Repro step2:
1.	Create a Winforms .Net 8.0 application
2.	Add a button to form designer, and double-click it to generate event
3.	Add following code:
            _string imagePath = "";
            OpenFileDialog open = new OpenFileDialog();
            open.InitialDirectory = "C:\\Users\\Public\\Pictures\\Sample Pictures";
            open.Filter = "*.jpg,*.jpeg,*.bmp,*.gif,*.ico,*.png,*.tif,*.wmf|*.jpg;*.jpeg;*.bmg;*.gif;*.ico;*.png;*.tif;*.wmf";
            open.Title = "choose picture";
            if (open.ShowDialog() == DialogResult.OK)
            {
                MessageBox.Show("OpenfileDialog is opened");
            }_

4.	Build and run to click button

Or using attached simple repro application:
[WinFormsApp10.zip](https://github.com/dotnet/winforms/files/9653217/WinFormsApp10.zip)

**Comment by Cassie-Li01** [comment]
Verified on latest .NET 8.0.100-alpha.1.22512.27, issue is fixed. Screenshot and gif please check below:
![7850](https://user-images.githubusercontent.com/96758262/195484045-15311fed-04ce-4bd0-8671-c954be95a77b.gif)

**Click button1:**
![image](https://user-images.githubusercontent.com/96758262/195483844-a83838b2-7782-4da0-9208-22dea298e8f0.png)
