### ISSUE TITLE
 System.Windows.Forms.Tests.ListControlTests.ListControl_FormatInfo_Set_CallsRefreshItems fails intermittently

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/winforms#8046]
### Test

System.Windows.Forms.Tests.ListControlTests.ListControl_FormatInfo_Set_CallsRefreshItems

### Issue description

System.Windows.Forms.Tests.ListControlTests.ListControl_FormatInfo_Set_CallsRefreshItems has been failing periodically, in the instance I investigated this was the error:

```
Error message
Assert.Same() Failure\r\nExpected: en-US\r\nActual:   en-US

Stack trace
   at System.Windows.Forms.Tests.ListControlTests.ListControl_FormatInfo_Set_CallsRefreshItems() in /_/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListControlTests.cs:line 1406
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

`Same` doesn't seem right, even if we think it doesn't change it, from a consumption standpoint it shouldn't matter. Should probably change to `Equals`.

**Comment by RussKie** [comment]
👍  `Same()` has been causing us pain in the past. And it's incorrect to compare `CultureInfo` instances like that, we should use `Assert.Equal`.

**Comment by Tanya-Solyanik** [comment]
@dmitrii-drobotov - please search the codebase for similar cases where we compare cultures.
