### ISSUE TITLE
`BuildAssist` fails to load in Visual Studio Preview

### ISSUE THREAD

**Issue by elachlan** [dotnet/winforms#8471]
I get this error when visual studio tried to load `BuildAssist`. I believe this is stopping me from debugging any code in `Winforms`.
![image](https://user-images.githubusercontent.com/2433737/211244329-685728d2-a4a4-4d56-a801-8ddbcac9de25.png)
![image](https://user-images.githubusercontent.com/2433737/211244341-6896b171-46dd-4dbd-871c-342d21331792.png)

```
Microsoft Visual Studio Community 2022
Version 17.5.0 Preview 2.0
VisualStudio.17.Preview/17.5.0-pre.2.0+33209.295
Microsoft .NET Framework
Version 4.8.04084
Installed Version: Community
```

```
=====================
09-Jan-23 2:59:41 PM
LimitedFunctionality
System.AggregateException: Project system data flow 'UpToDateCheckConfiguredInputDataSource: 1270418' closed because of an exception.
Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.ProjectSystem.UpToDate.CopyItemAggregator.SetProjectData(ProjectCopyData projectCopyData)
   at Microsoft.VisualStudio.ProjectSystem.UpToDate.UpToDateCheckImplicitConfiguredInputDataSource.<>c__DisplayClass8_0.<<LinkExternalInput>g__TransformAsync|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.TransformBlockSlim`2.TransformBlockSlimAsync.<ProcessInputAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim`1.<ProcessInputQueueAsync>d__5.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.ProjectSystem.UpToDate.CopyItemAggregator.SetProjectData(ProjectCopyData projectCopyData)
   at Microsoft.VisualStudio.ProjectSystem.UpToDate.UpToDateCheckImplicitConfiguredInputDataSource.<>c__DisplayClass8_0.<<LinkExternalInput>g__TransformAsync|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.TransformBlockSlim`2.TransformBlockSlimAsync.<ProcessInputAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim`1.<ProcessInputQueueAsync>d__5.MoveNext()<---

===================
```

**Comment by elachlan** [comment]
Loads okay when opening via `Winforms.sln` with Visual Studio 2022 (non-preview).
![image](https://user-images.githubusercontent.com/2433737/211244625-64ba97e4-f6c0-4bb9-bf96-1f838930a785.png)

**Comment by elachlan** [comment]
Related: https://github.com/dotnet/project-system/issues/8721

**Comment by dreddy-work** [comment]
Both of these are closed.  We may want to open this issue in one of those repos if it still repro with latest preview builds.

**Comment by elachlan** [comment]
It's waiting on VS 17.5 preview 3.

**Comment by elachlan** [comment]
VS 17.5 preview 3 has been released and fixes the issue.
