### ISSUE TITLE
CopyFromScreen tests causing intermittent failures

### ISSUE THREAD

**Issue by mellinoe** [dotnet/winforms#8804]
```
System.Drawing.Tests.GraphicsTests.CopyFromScreen_ValidRange_AffectsGraphics(sourceX: 1, sourceY: 1, destinationX: 2, destinationY: 2, width: 3, height: 3) [FAIL]
20:39:03         System.ComponentModel.Win32Exception : The handle is invalid
20:39:03         Stack Trace:
20:39:03              at System.Drawing.Graphics.CopyFromScreen(Int32 sourceX, Int32 sourceY, Int32 destinationX, Int32 destinationY, Size blockRegionSize, CopyPixelOperation copyPixelOperation)
20:39:03              at System.Drawing.Graphics.CopyFromScreen(Int32 sourceX, Int32 sourceY, Int32 destinationX, Int32 destinationY, Size blockRegionSize)
```

I believe these tests are invalid, given that they are failing against the .NET Framework. We should give them some scrutiny, and potentially remove them.

**Comment by JeremyKuhne** [comment]
Closing this for now and re-enabling the tests. I don't see anything specifically wrong in the code and don't expect additional failures. I've added an additional check in `CopyFromScreen` that will throw if we can't get the screen HDC.
