### ISSUE TITLE
Every time i create a new project, the designer always gets stuck

### ISSUE THREAD

**Issue by benki111** [dotnet/winforms#8996]
### Environment

![image](https://user-images.githubusercontent.com/130839892/232219293-70c84fa0-819f-4627-b48e-cee7e731efb5.png)

### .NET version

7.0

### Did this work in a previous version of Visual Studio and/or previous .NET release?

no

### Issue description

every time i create a new project the designer immediately hangs up, and it stays like that for hours
![image](https://user-images.githubusercontent.com/130839892/232219691-b2dd479b-d364-4e7c-b8a0-096e614c7382.png)

### Steps to reproduce

create a new project, no matter what net version

### Diagnostics

```text
[19:48:57.383748] fail: OutputGroupService didn't return output group DesignerRuntimeImplementationProjectOutputGroup.

                        For information on how to troubleshoot the designer refer to the guide at https://aka.ms/winforms/designer/troubleshooting.
[19:48:57.384745] fail: Could not retrieve DesignerRuntimeImplementationProjectOutputGroup for current project.

                        For information on how to troubleshoot the designer refer to the guide at https://aka.ms/winforms/designer/troubleshooting.
[19:48:57.393783] fail: System.InvalidOperationException: Designer load encountered an error. Please ensure that the project can be built successfully.
                           at Microsoft.DotNet.DesignTools.Client.Host.ProjectInfoProvider.NetCore.<GetNetCoreProjectInfoAsync>d__6.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at Microsoft.DotNet.DesignTools.Client.Host.ProjectInfoProvider.<GetProjectInfoAsync>d__9.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at Microsoft.DotNet.DesignTools.Client.Host.ServerHostFactory.<CreateHostAsync>d__8.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at Microsoft.DotNet.DesignTools.Client.DesignToolsClientLoader.<CreateClientAsync>d__29.MoveNext()

                        For information on how to troubleshoot the designer refer to the guide at https://aka.ms/winforms/designer/troubleshooting.
[19:48:59.229331] warn: Cannot update selection in server process as Session is not connected.
```

**Comment by elachlan** [comment]
@Olina-Zhang can your team please verify this?

**Comment by RussKie** [comment]
I think this is @Shyam-Gupta's area of expertise.

**Comment by Olina-Zhang** [comment]
> @Olina-Zhang can your team please verify this?

We cannot reproduce it. Let's see if @Shyam-Gupta has any output or need more information to customer.

**Comment by Shyam-Gupta** [comment]
@benki111 Could you please confirm if project can be built successfully after creating it? Also, are you able to create a WPF .NET project successfully and launch the designer? This will help us determine if it is a WinForms specific issue or not. Thanks.

**Comment by Tanya-Solyanik** [comment]
@benki111 - what framework are you targeting?

**Comment by amasys46** [comment]
When creating a new app Winform desktop for .Net 7, I solved this "hang" problem by using this procedure:
1. Create new app, close designer (it hangs!)
2. Execute PM > dotnet restore
3. Exit Vs2022
4. Reload app
5. Rename Form1.cs to MainForm.cs (or basically do something new)
6. Debug or run app
7. You should see your MainForm designer screen after 10 seconds!
Mike McCullough mike@mccul.co

**Comment by RussKie** [comment]
> * Create new app, close designer (it hangs!)
> * Execute PM > dotnet restore
> * Exit Vs2022
> * Reload app
> * Rename Form1.cs to MainForm.cs (or basically do something new)

All of that shouldn't be necessary. What's the diagnostics output? https://aka.ms/winforms/designer/troubleshooting.
