### ISSUE TITLE
Exception pops up when executing Metafile.GetMetafileHeader(String fileName)

### ISSUE THREAD

**Issue by Olina-Zhang** [dotnet/winforms#9019]
### .NET version

8.0.100-preview.4.23220.10 + the  latest binaries built for Winforms main branch

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, it doesn't reproduced in .Net 7.0

### Issue description

An automation case: XMetafile, it failed for some scenarios when test Metafile.GetMetafileHeader, it may be caused by PR: https://github.com/dotnet/winforms/pull/8995

**Failed log:**
              _System.ArgumentException: Parameter is not valid.
   at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status) in C:\Users\xxx\Documents\Winforms\src\System.Drawing.Common\src\System\Drawing\Gdiplus.cs:line 83
   at System.Drawing.Imaging.Metafile.GetMetafileHeader(String fileName) in C:\Users\xxx\Documents\Winforms\src\System.Drawing.Common\src\System\Drawing\Imaging\Metafile.cs:line 575
   at XMetafile.GetMetafileHeader(TParams p, String fileName) in C:\Users\xxx\Desktop\XMetafile_p1\XMetafile_p1\XMetafile.cs:line 148
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)_
           

### Steps to reproduce

**Sample app:**
[WinFormsApp17.zip](https://github.com/dotnet/winforms/files/11291683/WinFormsApp17.zip)

**Tested metafiles**:
[work.zip](https://github.com/dotnet/winforms/files/11291714/work.zip)

**Repro steps:**
1. Build and run above provided app, 
2. Stop runtime when form is running

**Actual result**: application is in break mode
![image](https://user-images.githubusercontent.com/26474449/233524101-5b7a8180-4d9f-4ab3-927a-290529e63ce7.png)

**Expected result**: App works well when targeting .Net 7.0

**Comment by elachlan** [comment]
@JeremyKuhne

**Comment by Olina-Zhang** [comment]
> @Olina-Zhang I'm not having success in reproducing this with the current bits.

In today's latest .Net 8.0 SDK build, it cannot repro. Still repro using binaries built from Winforms repo main branch. Did you try them?

**Comment by JeremyKuhne** [comment]
@Olina-Zhang I'm not reproducing this in main. I've added a scratch project to the WinForms solution for testing this sort of thing. Can you get it to reproduce with the ScratchProject in the WinForms.sln?

**Comment by Olina-Zhang** [comment]
@JeremyKuhne I found the ScratchProject is an empty project without test Metafle, so it doesn't reproduce. And we copy the test code from my provided app in that ScratchProject, it just repro in Release mode, and not Debug mode.

Run our automation case: XMetaFile, it just reproduce in Release mode, there are several scenarios give the same error: System.ArgumentException: Parameter is not valid, for example:
```
<Scenario method="GetMetafileHeader(String fileName)" name="GetMetafileHeader(String fileName)">
                <Text>
                    System.ArgumentException: Parameter is not valid.
   at System.Drawing.Imaging.Metafile.GetMetafileHeader(String fileName)
   at XMetafile.GetMetafileHeader(TParams p, String fileName) in C:\Users\xxx\Desktop\XMetafile_p1\XMetafile_p1\XMetafile.cs:line 148
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
                </Text>
        </Scenario>
```

```
<Scenario method="GetFrameCount(FrameDimension dimensionID)" name="GetFrameCount(FrameDimension dimensionID)">
                <Text>
                    System.ArgumentException: Parameter is not valid.
   at System.Drawing.Bitmap..ctor(String filename)
   at ReflectTools.SafeMethods.CreateBitmap(String filename) in C:\Users\xxx\Desktop\WFCTestLib\WFCTestLib\WFCTestLib\WFCTestLib\ReflectTools\SafeMethods.cs:line 488
   at XImage.GetFrameCount(TParams p, FrameDimension dimensionID) in C:\Users\xxx\Desktop\XMetafile_p1\XMetafile_p1\AdditionalSources\XImage.cs:line 98
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
                </Text>
        </Scenario>
```

```
<Scenario method="SelectActiveFrame(FrameDimension dimensionID, Int32 frameIndex)" name="SelectActiveFrame(FrameDimension dimensionID, Int32 frameIndex)">
                <Text>
                    System.ArgumentException: Parameter is not valid.
   at System.Drawing.Bitmap..ctor(String filename)
   at ReflectTools.SafeMethods.CreateBitmap(String filename) in C:\Users\xxx\Desktop\WFCTestLib\WFCTestLib\WFCTestLib\WFCTestLib\ReflectTools\SafeMethods.cs:line 488
   at XImage.SelectActiveFrame(TParams p, FrameDimension dimensionID, Int32 frameIndex) in C:\Users\xxx\Desktop\XMetafile_p1\XMetafile_p1\AdditionalSources\XImage.cs:line 106
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
                </Text>
        </Scenario>
```

```
<Scenario method="GetThumbnailImage(Int32 thumbWidth, Int32 thumbHeight, GetThumbnailImageAbort callback, IntPtr callbackData)" name="GetThumbnailImage(Int32 thumbWidth, Int32 thumbHeight, GetThumbnailImageAbort callback, IntPtr callbackData)">
                <Text>
                    System.ArgumentException: Parameter is not valid.
   at System.Drawing.Bitmap..ctor(String filename)
   at ReflectTools.SafeMethods.CreateBitmap(String filename) in C:\Users\xxx\Desktop\WFCTestLib\WFCTestLib\WFCTestLib\WFCTestLib\ReflectTools\SafeMethods.cs:line 488
   at XImage.GetThumbnailImage(TParams p, Int32 thumbWidth, Int32 thumbHeight, GetThumbnailImageAbort callback, IntPtr callbackData) in C:\Users\xxx\Desktop\XMetafile_p1\XMetafile_p1\AdditionalSources\XImage.cs:line 656
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
                </Text>
        </Scenario>
```
```
<Scenario method="get_FrameDimensionsList()" name="get_FrameDimensionsList()">
                <Text>
                    System.ArgumentException: Parameter is not valid.
   at System.Drawing.Bitmap..ctor(String filename)
   at ReflectTools.SafeMethods.CreateBitmap(String filename) in C:\Users\xxx\Desktop\WFCTestLib\WFCTestLib\WFCTestLib\WFCTestLib\ReflectTools\SafeMethods.cs:line 488
   at XImage.get_FrameDimensionsList(TParams p) in C:\Users\xxx\Desktop\XMetafile_p1\XMetafile_p1\AdditionalSources\XImage.cs:line 683
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
                </Text>
        </Scenario>
```

I am not sure if it's a real product issue or test scenarios about test parameters need to updated. Could you please help look at?  I have uploaded our automation case in https://microsoft-my.sharepoint.com/personal/v-olzhan_microsoft_com/_layouts/15/onedrive.aspx?ga=1&id=%2Fpersonal%2Fv%2Dolzhan%5Fmicrosoft%5Fcom%2FDocuments%2FCase&view=0

**Comment by merriemcgaw** [comment]
@Olina-Zhang can your team check this when you have a chance with the latest bits?

**Comment by Olina-Zhang** [comment]
It doesn't reproduce in the latest bits. Closing this one.

**Comment by Tanya-Solyanik** [comment]
This looks like an intermittent issue that started to repro again in Main, reactivating.

**Comment by lonitra** [comment]
This actually is not reproing on main, my mistake.
