### ISSUE TITLE
environment name or value is too long build failures in 'official/dotnet/winforms/refs/heads/master' - '20190506.2'

### ISSUE THREAD

**Issue by robertborr** [dotnet/winforms#931]
@dotnet-mc-bot commented on [Mon May 06 2019](https://github.com/dotnet/core-eng/issues/6246)

There were a set of failures during this build. Here is a summary of these:
* https://dnceng.visualstudio.com/internal/_build/results?buildId=180847
  - **Agent:** 
  - **Error log:** ContinueOnError: False...

@robertborr

---

@robertborr commented on [Mon May 06 2019](https://github.com/dotnet/core-eng/issues/6246#issuecomment-489768288)

Unhandled Exception: Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: Environment variable name or value is too long.
=============
System.ArgumentException: Environment variable name or value is too long.
   at System.Environment.SetEnvironmentVariable(String variable, String value)
   at Microsoft.Build.BackEnd.InProcNode.HandleShutdown(Exception& exception)
   at Microsoft.Build.BackEnd.InProcNode.Run(Exception& shutdownException)
 ---> System.ArgumentException: Environment variable name or value is too long.
   at System.Environment.SetEnvironmentVariable(String variable, String value)
   at Microsoft.Build.BackEnd.InProcNode.HandleShutdown(Exception& exception)
   at Microsoft.Build.BackEnd.InProcNode.Run(Exception& shutdownException)
   --- End of inner exception stack trace ---
   at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Exception innerException, Object[] args)
   at Microsoft.Build.BackEnd.InProcNode.Run(Exception& shutdownException)
   at Microsoft.Build.BackEnd.NodeProviderInProc.InProcNodeThreadProc()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
1 more errors. Click on expand view in the context menu to view complete logs.

**Comment by robertborr** [comment]
variable is:##[warning]Environment variable 'BUILD_SOURCEVERSIONMESSAGE' exceeds the maximum supported length. Environment variable length: 42506 , Maximum supported length: 32766

**Comment by merriemcgaw** [comment]
This doesn't appear to have reproed recently.
