### ISSUE TITLE
Random AccessViolations in tests

### ISSUE THREAD

**Issue by Tanya-Solyanik** [dotnet/winforms#9374]
We should enable [gflags ](https://learn.microsoft.com/windows-hardware/drivers/debugger/gflags-details) locally and run unit tests to see exactly where the first invalid memory access happens.

xUnit.net Console Runner v2.4.2+f110e5bee5 (32-bit .NET 8.0.0-preview.7.23323.7)
  Discovering: System.Windows.Forms.Tests
  Discovered:  System.Windows.Forms.Tests
  Starting:    System.Windows.Forms.Tests
Process terminated. Encountered infinite recursion while looking up resource 'Arg_NullReferenceException' in System.Private.CoreLib. Verify the installation of .NET is complete and does not need repairing, and that the state of the process has not become corrupted.
   at System.Environment.FailFast(System.String)
   at System.SR.InternalGetResourceString(System.String)
   at System.SR.GetResourceString(System.String)
   at System.NullReferenceException..ctor()
   at System.Resources.ResourceManager.GetString(System.String, System.Globalization.CultureInfo)
   at System.SR.InternalGetResourceString(System.String)
   at System.SR.GetResourceString(System.String)
   at System.NullReferenceException..ctor()
   at System.Threading.Thread.get_CurrentThread()
   at System.Windows.Forms.Application+ThreadContext.OleRequired()
   at System.Windows.Forms.Application.OleRequired()
   at System.Windows.Forms.Application+ThreadContext.<get_ComponentManager>g__GetExternalComponentManager|43_0()
   at System.Windows.Forms.Application+ThreadContext.get_ComponentManager()
   at System.Windows.Forms.Application+ThreadContext.FormActivated(Boolean)
   at System.Windows.Forms.Application.FormActivated(Boolean, Boolean)
   at System.Windows.Forms.Form.WmActivate(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Form.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control+ControlNativeWindow.OnMessage(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control+ControlNativeWindow.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.Callback(Windows.Win32.Foundation.HWND, Windows.Win32.MessageId, Windows.Win32.Foundation.WPARAM, Windows.Win32.Foundation.LPARAM)
=== COMMAND LINE ===
"D:\a\_work\1\s\.dotnet\x86\dotnet.exe" exec --depsfile "D:\a\_work\1\s\artifacts\bin\System.Windows.Forms.Tests\Debug\net8.0-windows7.0\System.Windows.Forms.Tests.deps.json" --runtimeconfig "D:\a\_work\1\s\artifacts\bin\System.Windows.Forms.Tests\Debug\net8.0-windows7.0\System.Windows.Forms.Tests.runtimeconfig.json"  "D:\a\_work\1\s\.packages\xunit.runner.console/2.4.2/tools/netcoreapp2.0/xunit.console.dll" "D:\a\_work\1\s\artifacts\bin\System.Windows.Forms.Tests\Debug\net8.0-windows7.0\System.Windows.Forms.Tests.dll" -noautoreporters -xml "D:\a\_work\1\s\artifacts\TestResults\Debug\System.Windows.Forms.Tests_net8.0-windows7.0_x86.xml" -html "D:\a\_work\1\s\artifacts\TestResults\Debug\System.Windows.Forms.Tests_net8.0-windows7.0_x86.html" -notrait Category=IgnoreForCI -notrait Category=failing > "D:\a\_work\1\s\artifacts\log\Debug\System.Windows.Forms.Tests_net8.0-windows7.0_x86.log" 2>&1

_Originally posted by @dreddy-work in https://github.com/dotnet/winforms/issues/9362#issuecomment-1607936108_

**Comment by dreddy-work** [comment]
Thanks @Tanya-Solyanik .

**Comment by dreddy-work** [comment]
new one: https://dev.azure.com/dnceng-public/public/_build/results?buildId=322161&view=results

**Comment by Tanya-Solyanik** [comment]
Potential fix: https://github.com/dotnet/winforms/pull/9358

**Comment by dreddy-work** [comment]
I did not notice any new failures last week. May be it is safe to close now and reopen if we see nay.

**Comment by dreddy-work** [comment]
https://dev.azure.com/dnceng-public/public/_build/results?buildId=343823&view=logs&j=13abda86-2028-5de5-3254-ca63f887785e

**Comment by dreddy-work** [comment]
This is intermittent but often enough. We plan to experiment with gcflags in tests to get more details on this exception. Potential fix linked did not solve this issue.

**Comment by dreddy-work** [comment]
We are not seeing this issue anymore. Closing and we can revisit if this happens again.
