### ISSUE TITLE
Failed to launch design tools server process process

### ISSUE THREAD

**Issue by 8oris** [dotnet/winforms#9401]
### Environment

Microsoft Visual Studio Community 2022 (64 bits) - Current
Version 17.6.4

### .NET version

net 6.0

### Issue description

I can't open forms since today. I did no update. I tried to reinstall Visual Studio Community but it did nothing.
See errors log in diagnostics

### Steps to reproduce

Just opening a form by double clicking on it from the projet browser and it never loads.

### Diagnostics

```text
> [13:36:08.925333] fail: [Dumbow2]: Failed to launch design tools server process process
                        System.PlatformNotSupportedException: Access Control List (ACL) APIs are part of resource management on Windows and are not supported on this platform.
                           at System.Security.AccessControl.AuthorizationRule..ctor(IdentityReference identity, Int32 accessMask, Boolean isInherited, InheritanceFlags inheritanceFlags, PropagationFlags propagationFlags)
                           at System.Security.AccessControl.AccessRule..ctor(IdentityReference identity, Int32 accessMask, Boolean isInherited, InheritanceFlags inheritanceFlags, PropagationFlags propagationFlags, AccessControlType type)
                           at System.IO.Pipes.NamedPipeServerStream.Create(String pipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options, Int32 inBufferSize, Int32 outBufferSize, PipeSecurity pipeSecurity, HandleInheritability inheritability, PipeAccessRights additionalAccessRights)
                           at System.IO.Pipes.NamedPipeServerStream..ctor(String pipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options)
                           at Microsoft.DotNet.DesignTools.Server.Program.<>c__DisplayClass2_0.<<Main>b__1>d.MoveNext()

                        Pour plus d’informations sur la résolution des problèmes du concepteur, consultez le guide sur https://aka.ms/winforms/designer/troubleshooting.
[13:38:07.920584] fail: [Dumbow2]: Timed out while connecting to named pipe: DesignToolsServer.4c7fc87a-f873-4634-b66c-1cbf54f16c30

                        Pour plus d’informations sur la résolution des problèmes du concepteur, consultez le guide sur https://aka.ms/winforms/designer/troubleshooting.
[13:38:07.929585] fail: Microsoft.DotNet.DesignTools.Client.ServerException: Expiration du délai d’attente lors de la connexion au canal nommé.
                           à Microsoft.DotNet.DesignTools.Client.Host.ServerProcess.<ConnectToStreamAsync>d__35.MoveNext()
                        --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                           à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           à Microsoft.DotNet.DesignTools.Client.Host.ServerProcess.<LaunchAsync>d__28.MoveNext()
                        --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                           à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           à Microsoft.DotNet.DesignTools.Client.Host.ServerHostFactory.<CreateHostAsync>d__8.MoveNext()
                        --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
                           à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           à Microsoft.DotNet.DesignTools.Client.DesignToolsClientLoader.<CreateClientAsync>d__29.MoveNext()

                        Pour plus d’informations sur la résolution des problèmes du concepteur, consultez le guide sur https://aka.ms/winforms/designer/troubleshooting.
[13:38:08.584013] warn: Cannot update selection in server process as Session is not connected.
[13:38:08.687016] warn: Cannot update selection in server process as Session is not connected.
```

**Comment by 8oris** [comment]
I used multiple framework targetings
So, i changed 
<TargetFrameworks>net6.0-windows;net5.0-windows</TargetFrameworks>
to
<TargetFrameworks>net6.0-windows</TargetFrameworks>

And it solves the issue.
