### ISSUE TITLE
System.ArgumentOutOfRangeException: Value of '-22' is not valid for 'LargeChange'.

### ISSUE THREAD

**Issue by John-Qiao** [dotnet/winforms#9596]
### .NET version

8.0.100-rc.1.23377.5

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Yes, regression after PR https://github.com/dotnet/winforms/pull/9477

### Issue description

'LargeChange' must be greater than or equal to 0. But the 'LargeChange' value is '-22' in below test cases scneiaros:

```
<Scenario method="get_RestoreBounds()" name="get_RestoreBounds()">
            Uncaught exception or assertion failure: System.ArgumentOutOfRangeException
System.ArgumentOutOfRangeException: Value of '-22' is not valid for 'LargeChange'. 'LargeChange' must be greater than or equal to 0. (Parameter 'value')
   at System.Windows.Forms.ScrollBar.set_LargeChange(Int32 value)
   at System.Windows.Forms.PrintPreviewControl.&lt;LayoutScrollBars&gt;g__AdjustScroll|105_1(ScrollBar scrollBar, Int32 virtualDimension, Int32 displayDimension, Int32 offset)
   at System.Windows.Forms.PrintPreviewControl.LayoutScrollBars()
   at System.Windows.Forms.PrintPreviewControl.InvalidateLayout()
   at System.Windows.Forms.PrintPreviewControl.OnResize(EventArgs eventargs)
   at System.Windows.Forms.Control.OnSizeChanged(EventArgs e)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
   at System.Windows.Forms.Control.UpdateBounds()
   at System.Windows.Forms.Control.WmWindowPosChanged(Message&amp; m)
   at System.Windows.Forms.Control.WndProc(Message&amp; m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message&amp; m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
            <Result type="Fail">
                <ResultComments>
                    Uncaught exception or assertion failure: System.ArgumentOutOfRangeException
                </ResultComments>
            </Result>
</Scenario>

<Scenario method="set_RestoreBounds(Rectangle value)" name="set_RestoreBounds(Rectangle value)">
            Uncaught exception or assertion failure: System.ArgumentOutOfRangeException
System.ArgumentOutOfRangeException: Value of '-22' is not valid for 'LargeChange'. 'LargeChange' must be greater than or equal to 0. (Parameter 'value')
   at System.Windows.Forms.ScrollBar.set_LargeChange(Int32 value)
   at System.Windows.Forms.PrintPreviewControl.&lt;LayoutScrollBars&gt;g__AdjustScroll|105_1(ScrollBar scrollBar, Int32 virtualDimension, Int32 displayDimension, Int32 offset)
   at System.Windows.Forms.PrintPreviewControl.LayoutScrollBars()
   at System.Windows.Forms.PrintPreviewControl.InvalidateLayout()
   at System.Windows.Forms.PrintPreviewControl.OnResize(EventArgs eventargs)
   at System.Windows.Forms.Control.OnSizeChanged(EventArgs e)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
   at System.Windows.Forms.Control.UpdateBounds()
   at System.Windows.Forms.Control.WmWindowPosChanged(Message&amp; m)
   at System.Windows.Forms.Control.WndProc(Message&amp; m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message&amp; m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
            <Result type="Fail">
                <ResultComments>
                    Uncaught exception or assertion failure: System.ArgumentOutOfRangeException
                </ResultComments>
            </Result>
</Scenario>

<Scenario method="set_WindowState(FormWindowState value)" name="set_WindowState(FormWindowState value)">
            Setting WindowState from Normal to Minimized
            Uncaught exception or assertion failure: System.ArgumentOutOfRangeException
System.ArgumentOutOfRangeException: Value of '-22' is not valid for 'LargeChange'. 'LargeChange' must be greater than or equal to 0. (Parameter 'value')
   at System.Windows.Forms.ScrollBar.set_LargeChange(Int32 value)
   at System.Windows.Forms.PrintPreviewControl.&lt;LayoutScrollBars&gt;g__AdjustScroll|105_1(ScrollBar scrollBar, Int32 virtualDimension, Int32 displayDimension, Int32 offset)
   at System.Windows.Forms.PrintPreviewControl.LayoutScrollBars()
   at System.Windows.Forms.PrintPreviewControl.InvalidateLayout()
   at System.Windows.Forms.PrintPreviewControl.OnResize(EventArgs eventargs)
   at System.Windows.Forms.Control.OnSizeChanged(EventArgs e)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
   at System.Windows.Forms.Control.UpdateBounds()
   at System.Windows.Forms.Control.WmWindowPosChanged(Message&amp; m)
   at System.Windows.Forms.Control.WndProc(Message&amp; m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message&amp; m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)
            <Result type="Fail">
                <ResultComments>
                    Uncaught exception or assertion failure: System.ArgumentOutOfRangeException
                </ResultComments>
            </Result>
</Scenario>
```

### Steps to reproduce

1. Open the project [XPrintPreviewDialog.zip](https://github.com/dotnet/winforms/files/12192285/XPrintPreviewDialog.zip) in VS.
2. Build and run it.
3. Check the results.log in XPrintPreviewDialog\bin\Debug\net8.0-windows folder.

**Comment by elachlan** [comment]
Cc: @v-elnovikova

**Comment by merriemcgaw** [comment]
@LeafShi1 can your team take a look at this regression?

**Comment by LeafShi1** [comment]
> @LeafShi1 can your team take a look at this regression?

OK， we will do that.

**Comment by Tanya-Solyanik** [comment]
@Epica3055  - fair point. The aborted test runs is a serious problem that might have different root causes. Please search the issue (including the closed ones) for previous investigations. We had some changes related to global exception handlers in the base test class. If there is an open issue, please add your investigation notes to it. If there is no open issue, please open a new one. Because this PR is fixing a recent regression, I'd like to merge it with no unit test.

**Comment by Eudora-Li01** [comment]
Verified this issue on .NET 8.0.100-rc.1.23414.11, it was fixed. XPrintPreviewDialog case can be passed successfully.
![image](https://github.com/dotnet/winforms/assets/130345015/05b60d07-0189-4a9b-9d36-9e3778fae181)

**Comment by MelonWang1** [comment]
Verified with .NET SDK 8.0.100-rc.1.23421.2 test pass build, this issue was fixed, the case can run successfully, test result is same as above.
